### ISSUE TITLE
Mixed language projects restore broken with preview langversion

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#10033]
Repro can be found here:
https://github.com/NinoFloris/preview8packageissues

Try to restore the solution, it will fail for console.csproj because it cannot find 5.0.0-beta on nuget.

**Comment by tebeco** [comment]
Hello,

I was able to reproduce the issue, as the error points out, the restore process
(WIP)

**Comment by cartermp** [comment]
@KevinRansom looks like an unintended consequence of the automagic is that any referencing C# project no longer restores. This means that any solution with C# referencing F# will fail to restore if you try preview language features.

**Comment by KevinRansom** [comment]
Okay,

the root of this issue is a bug in the dotnet sdk issue here:https://github.com/dotnet/sdk/issues/13281


The issue is that the restore sources uris are not flowed from referenced projects back to the referencing project, and so the restore can't restore the packages that are not located on well known sources.

To work around this issue, we will publish a preview build to nuget.org that matches the FSharp.Core built alongside the preview releases of the dotnet SDK.

This package matches VS 16.8 preview 2:  https://www.nuget.org/packages/FSharp.Core/5.0.0-beta.20417.1

The project should now build and restore correctly.  

@NinoFloris , @tebeco . Please reopen if you still have issues with this.

Thanks for the report,

Kevin

**Comment by NinoFloris** [comment]
@KevinRansom thanks for the quick fix, it's much appreciated
