### ISSUE TITLE
Update FSI to net50

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10079]
We should probably update the FSI TFM to net50 before the .NET 5 release. Otherwise users won't be able to use types like `System.Half`.

Also would require us to build with the .NET 5 SDK though. eek

**Comment by abelbraaksma** [comment]
It appears to me, or at least on my system, that opening a command prompt and running `dotnet fsi` properly uses the .NET 5.0 libs. This is probably due to installing VS Preview editions, which also installs .NET 5.0 and forces the highest version.

However, the same is **not true** for the `fsi.exe` in the artifacts build. If I go to `artifacts\bin\fsi\Debug\netcoreapp3.1` and use `dotnet fsi.exe`, the type `System.Half` is _not available_. If I change the `fsi.runtimeconfig.json` to have the tfm `net5.0` I get immediate loading errors.

I'm not sure how to run the dotnet FSI build from artifacts with .NET 5.0. Which also begs the question whether the CI tests for FSI are ever run with .NET 5.0. Perhaps we need an additional target, next to `netcoreapp3.1`?

**Comment by KevinRansom** [comment]
The tfm that we build in the repo, is not the one we ship with.  The dotnet sdk already ships with fsc and fsi targetting the highest shipped tfm.

````
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\FSharp\fsc.deps.json
{
  "runtimeTarget": {
    "name": "net5.0",
    "signature": ""
  },
````
````
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\FSharp\fsi.deps.json
{
  "runtimeTarget": {
    "name": "net5.0",
    "signature": ""
  },
````

At some point we will likely update it, but almost certainly not until net5.0 has rtm'd.

**Comment by baronfel** [comment]
@KevinRansom is there any way that people working in this repo are able to build this net5.0-compatible FSI in order to test with .net 5.0?

**Comment by KevinRansom** [comment]
Use the dotnet sdk previews!,  That is the mechanism for evaluation the behavior of the latest bits.  I f you want to validate in place some developements you are working on in the F# repo then Install a dotnet sdk preview, build a release or debug build of 16.8 branch, and copy the build dll's and .exe into the sdk directory

%programfiles%\dotnet\sdk\{sdk version}\FSharp

On todays internal dogfood build that looks like:
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\FSharp


Files to copy
````
fsc.exe
fsi.exe
fsharp.dependencymanager.nuget.dll
fsharp.core.dll
fsharp.compiler.private.dll
fsharp.compiler.interactive.settings.dll
fsharp.build.dll
````
This is what I usually do, when I want to verify behaviour in place in the sdk, it works fine, performance is lower because we rely on the jit not crossgen.  It is worth noting that you should save a copy of the sdk/FSharp subdirectory.

I hope this helps.

**Comment by baronfel** [comment]
Thanks for the writeup, this makes sense when I think about what's happening here with regards to the packaging/dlls involved.
