### ISSUE TITLE
Use refemit to inherit from AssemblyLoadContext

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#10400]
To properly build only `netstandard2.0` of `Microsoft.DotNet.DependencyManager`, we need to refemit the `NativeAssemblyLoadContext` inheritance from `AssemblyLoadContext` [here](https://github.com/dotnet/fsharp/blob/a6fd66ef6660fc832fddc38daab260e308154026/src/fsharp/Microsoft.DotNet.DependencyManager/NativeDllResolveHandler.fs#L22) because that type comes from `System.Runtime.Loader` in `netstandard2.0` and that'll never be supported on desktop builds, which is how VS is running NGEN.

**Comment by teo-tsirpanis** [comment]
> we need to refemit the NativeAssemblyLoadContext inheritance from AssemblyLoadContext

This will unnecessarily complicate the build pipeline, and consequently the library's development experience. Specifying the type's inheritance via a custom tool is a temporary fix that hides the sad and inconvenient truth that __a .NET Core-only type such as `AssemblyLoadContext` is not available on .NET Standard__.

As I explained in dotnet/runtime#38503, the NuGet package `System.Runtime.Loader` is a mistake and should be unlisted and deprecated. And because .NET Framework and .NET Core have different APIs for loading assemblies, and supporting both is an absolute must, __the only solution to this problem is to multi-target `FSharp.Compiler.Services` and other relevant libraries to both frameworks__.

The biggest concern is "what about .NET Standard"? If FCS -a .NET Standard 2.0 library- runs in a .NET Framework app like Visual Studio and loads an assembly using `AssemblyLoadContext`, it will crash.

Still using `AssemblyLoadContext` and using the correct API by checking at runtime whether we are on .NET Framework or not is IMHO a code smell. We will also miss useful features like unloadability, which is available only on .NET Core 3+. Besides, the `System.Runtime.Loader` package brings lots of NuGet dependencies, cluttering `paket.lock` files.

---

As I see it, we have four sustainable options about .NET Standard:

1. __Target .NET Framework, .NET Core and .NET Standard 2.0__: Use `System.Reflection.Assembly.LoadFrom` to load assemblies. It is the least breaking change, but does not support isolation, unloadability or native dependencies (which is what the linked code fragment does).

2. __Target .NET Framework, .NET Core and .NET Standard 2.0__: Throw an exception when an external assembly is tried to be loaded. This is a breaking but honest solution and keeps .NET Standard 2.0 support for the assemblies that need it but don't have to load external assemblies.

3. __Drop .NET Standard 2.0 and target only .NET Framework and .NET Core 3.1__: The most legacy-free solution. FCS will no longer be available on .NET Standard, but will be correctly implemented on the two frameworks it supports.

4. __Like 3, but target .NET Core 2.1 as well__: To support the still-supported .NET Core 2.1, we can target it as well, and it will work with all its features except from unloadability.

Multitargeting core F# libraries at a time when targeting only .NET Standard 2.0 is the norm (like with `FSharp.Core`) might seem an uneasy step backwards, but `FSharp.Core` is an actual library, where FCS is like a librarized tool. Trying to make it target .NET Standard 2.0 will lead to more technical debt. And `Microsoft.Build` for example, does not target .NET Standard at all; only .NET Framework 4.7.2 and Core 2.1.

I also stumbled upon [this line](https://github.com/dotnet/fsharp/blob/a6fd66ef6660fc832fddc38daab260e308154026/src/fsharp/Microsoft.DotNet.DependencyManager/NativeDllResolveHandler.fs#L95), which is unfortunately wrong: `AssemblyLoadContext` does not exist in .NET Standard 2.1 either.
