### ISSUE TITLE
String interpolation dotnetFormatString with dashes

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#10474]
The following

```fsharp 
$"{System.DateTime.Today: yyyy-MM-dd}" 
```

produces the error
```
error FS0010: Unexpected symbol '-' in interaction. Expected interpolated string (final part), interpolated string (part) or other token.
```

**Comment by 8** [comment]
String Interpolation compilation bug 

**Repro steps**

The following function does not compile in F#:
````fs
let formatDate (date : DateTime) =
  $"{date:yyyy.MM.dd HH:mm:ss}"
````

The corresponding function in C# works without problems:
````cs
static string FormatDate(DateTime date) =>
  $"{date:yyyy.MM.dd HH:mm:ss}";
````

**Expected behavior**

Compilation works and produces the same output as in C#.


**Actual behavior**

Compilation fails with the error:

````
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0010	Unexpected symbol '.' in binding. Expected interpolated string (final part), interpolated string (part) or other token.	FormatDateFSharp	C:\projects\FormatDate\FormatDateFSharp\Program.fs	5	Active
````


Custom format strings by themselves seem to work, e.g.
````fs
let formatDateAlt1 (date : DateTime) =
  $"{date:yyyyMMddhhmmss}"
````
works fine. The issue seems to happen only for characters that are not custom format characters.

I have added a repro sample containing the failing f# and the working c# project: 
[formatdate.zip](https://github.com/dotnet/fsharp/files/6248639/formatdate.zip)

**Known workarounds**

I am using Triple Quoted Strings and calling DateTime.ToString() directly instead:

````fs
let formatDateAlt2 (date : DateTime) =
    $"""{date.ToString("yyyy.MM.dd HH:mm:ss")}"""
````

**Related information**

Provide any related information (optional):

* Operating system: Win10
* .NET Runtime kind: .NET Core
* Editing Tools: Visual Studio 16.9.2, VsCode, Rider


This time I searched the issues before raising a new one and found this issue, which looks to be same.
From what I can see, the error is not related to dashes specifically, it seems to an issue for any character that is not a custom formatter (eg. spaces and dots) and I also added a repro sample and a workaround.

Take care,
Martin

**Comment by mlaily** [comment]
Another cleaner workaround is to use a quoted identifier (` ``x`` `) around the format string :
```fsharp
let formatDate (date : DateTime) =
  $"{date:``yyyy.MM.dd HH:mm:ss``}"
```
```
> formatDate DateTime.Now;;
val it: string = "2022.01.08 16:37:29"
```

Tested in `Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0`

**Comment by dsyme** [comment]
I'm treating this as by design.  The RFC notes the workaround to use 

    ``yyyy-MM-dd``
