### ISSUE TITLE
Inconsistent handling of `System.ObsoleteAttribute` on type alias versus module alias

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#10528]
in context of https://github.com/fsprojects/FSharp.Data.SqlClient/issues/359 & https://github.com/fsprojects/FSharp.Data.SqlClient/issues/399, I was trying to use `[<Obsolete>]` attributes on type aliases.

It seems they can be defined but don't show as warning at usage places:

```fsharp
module A =
    type T() =
        class 
        end
    module M =
        let a = 1

module B =
    open System
    [<Obsolete("use `A.T` instead")>]
    type T = A.T
    //[<Obsolete("use `A.M` instead")>]
    module M = A.M

let t = B.T()
//let m = B.M.a
```

Few things with this code:
* I can't put an attribute on the module alias
* the module alias doesn't seem to do what I expected, it creates an empty module
* the warning doesn't show on usages of `B.T`

Having things work more naturally would be a way for library to evolve by defining type aliases and have their usage create warnings.

It allows client code to be source compatible and better tool for library author to move types.

Is the current behaviour by design?

**Comment by dsyme** [comment]
This is by design. Module aliases are very rarely used in F# and can't be used from outside the file that contains them.  This means they differ greatly from type aliases and this is one way in which they differ

TBH my recommendation is just don't use module aliases.

> the warning doesn't show on usages of B.T

This surprised me but it is because you are referring to the constructor, not the type.  For example

```fsharp
module A =
    [<System.Obsolete("use `A.T` instead")>]  
    type T () = class  end
    
let t = A.T()
```

does not give a warning, but this does:

```fsharp
module A =
    
    type T [<System.Obsolete("use `A.T` instead")>]    () = class  end
    
let t = A.T()
```
