### ISSUE TITLE
#r nuget should support nativeassts probing

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10571]
@fwaris has pointed out FSharp probing does not find files in the nativeassets branch from a nuget package.

https://github.com/dotnet/fsharp/issues/10136#issuecomment-735239943

Some descriptions:

NuGet/Home#2782
NuGet/Home#3027 (comment)
NuGet/NuGet.Client@aed1d51

**Comment by nhirschey** [comment]
I think that I am running into the same issue with TensorFlow.Net: https://github.com/SciSharp/TensorFlow.NET/issues/656 

Comparing VS and VScode since the different fsi and fsc may help debugging:
- Visual Studio 16.9.0 preview 1: Intellisense works but fsi does not find the dlls.
- Visual Studio Code Insider with Ionide 5.0 preview 2, fsi works and finds the dlls, but fsc does not do intellisense for the TensorflowNet code (it works for regular F# code though).

Additionally, I tried the fix in Visual Studio proper of using NativeLibrary load suggested by Don, but in VS 16.9.0 preview 1 I am getting Errors that NativeLibrary is not in in `System.Runtime.InteropServices`.

Code, with additional manual references to try to help finding things:

```fsharp
#r "nuget: TensorFlow.Net"
#r "nuget: TensorFlow.Keras"
#r "nuget: SciSharp.TensorFlow.Redist"
#r "nuget: NumSharp"

#r @"C:\Users\nicho\.nuget\packages\tensorflow.net\0.30.0\lib\netstandard2.0\TensorFlow.NET.dll"
#r @"C:\Users\nicho\.nuget\packages\numsharp.lite\0.1.9\lib\netstandard2.0\NumSharp.Lite.dll"
#r @"C:\Users\nicho\.nuget\packages\google.protobuf\3.11.4\lib\netstandard2.0\Google.Protobuf.dll"
#r @"C:\Users\nicho\.nuget\packages\methodboundaryaspect.fody\2.0.138\lib\netstandard1.0\MethodBoundaryAspect.dll"

System.Runtime.InteropServices.NativeLibrary.Load(@"C:\Users\nicho\.nuget\packages\scisharp.tensorflow.redist\2.3.1\runtimes\win-x64\native\tensorflow.dll")

open NumSharp
open Tensorflow
open Tensorflow.Keras


let tf = Binding.New<tensorflow>()
let W = tf.Variable(-0.06f,name = "weight")
tf.Variable()
```

.

**Comment by smoothdeveloper** [comment]
@nhirschey not sure if it applies, but for NativeLibrary, you may try a work around similar to what I used there:

https://github.com/matthewcrews/flips/issues/88#issuecomment-727067349

**Comment by nhirschey** [comment]
@smoothdeveloper, thank you for the tip. 

Turns out that if I use ionide 4.17.0 with --langversion:preview enabled, then everything works. So I just need to wait for VS and ionide 5.0 to fully update to F# 5.0 dotnet core. Ionide should be soon, VS should come along after the switch to dotnet fsi is complete.

**Comment by KevinRansom** [comment]
With netcore scripting in Preview 16.9 this works in both the IDE and FSI

![image](https://user-images.githubusercontent.com/5175830/109383723-2328b100-789d-11eb-9105-4ba8d33cb80c.png)
