### ISSUE TITLE
Can't run tests in FCS solution

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10719]
When trying to build the tests project, it fails:
```
FSharp.Compiler.Service.fsproj:
  [NU1105] Unable to find project information for 'C:\Developer\fsharp-main\src\fsharp\FSharp.DependencyManager.Nuget\FSharp.DependencyManager.Nuget.fsproj'.
If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
```

cc @KevinRansom

**Comment by cartermp** [comment]
Hmmm, with VS this does work for me on latest main. FCS solution, built tests, executed the ServiceUntypedParse tests (just as a quick check). Is there any additional environment information you could share?

Though the solution should also have the dependency manager project in it (IMO) since it is a project-level dependency.
