### ISSUE TITLE
Use .NET MemoryMapped files implementation instead of windows kernel api

### ISSUE THREAD

**Issue by enricosada** [dotnet/fsharp#1094]
The current memory mapped files implementation use [windows kernel api](https://github.com/Microsoft/visualfsharp/blob/1fb20e0e89a1d5404058bfc7a590bcc361c6de5b/src/absil/ilread.fs#L109-L125).

It should be converted to use [.net bcl MemoryMapped classes](https://msdn.microsoft.com/en-us/library/dd997372%28v=vs.110%29.aspx), so it should work on .net core/mono

The memory mapped files are supported from .NET 4

**Comment by enricosada** [comment]
That should also open a really good refactoring to use Stream, instead of byte array, and remove [BinaryFile](https://github.com/Microsoft/visualfsharp/blob/1fb20e0e89a1d5404058bfc7a590bcc361c6de5b/src/absil/ilread.fs#L100) implementation

That should help to inline a lot of calls (performance) so the read is faster, because lot of call are readByte in the pickler and are not inlined

**Comment by 7sharp9** [comment]
That has been a long known issue that would help mono F# speed too.

**Comment by smoothdeveloper** [comment]
@dsyme I'm not sure what was your metric to measure performance, but in VS (with VFPT + Resharper in process), the memory is very tight, in projects using lots of assembly references (I'm having 150+mb of .dll) those byte arrays show up at the top of memory usage, see #2345.

F# related stuff in profiling I did yesterday is at the top even with Resharper and a C#/VB heavy solution loaded with only 5 projects, I'm inclined to think keeping those arrays around is causing me stability issues in this context.

Maybe we should compile that command line language service profiling tool for 32bit, call a bunch of waste memory commands, and then compare performance of simple FCS commands before / after migration to MemoryMapped.

**Comment by dsyme** [comment]
@smoothdeveloper Let's continue the discussion on #2345.  This thread is about MemoryMappedFile.  greed that the BytFile memory usage is considerable.

**Comment by jack-pappas** [comment]
@dsyme You mentioned you'd tried this conversion once and didn't see much performance improvement; did you test on Mono (on Linux/Mac) as well?

Also, it seems like this could be a useful change even if there's *zero* performance improvement, just because it unifies the way we're reading files (i.e., we're getting rid of platform-specific code in favor of platform-independent code).

**Comment by smoothdeveloper** [comment]
@jack-pappas there is also the question if it helps in FCS / VFT wrt memory usage (see #2345)

**Comment by enricosada** [comment]
@jack-pappas this issue is just to convert pinvoke -> MemoryMapped . easier to discuss future improvement somewhere helps -> #2345

There is no need to change current code for read. I think this can be the starting point for future refactoring (small steps).
But just using bcl classes like proposed in this issue, we can use memory mapped in the xplat compiler (netcore/mono). dunno about improvements in speed, was just a cleanup

**Comment by cartermp** [comment]
Tagging this differently, as this is counting as the tracking issue for #2528

**Comment by cartermp** [comment]
@dsyme just to mention that calls to `ReadBytes` end up calling `Bytes.zeroCreate` in the current implementation, and it stands to reason that these buffers would be greater than 85k for any metadata of reasonable size. Since we now know the impact on the IDE process for these LOH calls, if it's an easy win (see #7944) to remove some of that, it's definitely worth doing.

(Also worth noting that I've seen `Bytes.zeroCreate` show up many times in ETL traces as a significant contributor to allocations, though this was mostly in the very large (2x 100k) buffers whenever `pickleObjWithDanglingCcus` was called.)

**Comment by cartermp** [comment]
Tagging as a perf tracking issue due to the use of `Bytes.zeroCreate`

**Comment by cartermp** [comment]
Implemented in #7944
