### ISSUE TITLE
ToolTips not showing in some cases

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#11022]
When using VisualFSharp.sln I'm seeing tooltips not showing in many places, it may indicate a broader range of problems, maybe to do with type abbreviations or missing assembly references. 

I'll compile up main and see if the problem is there too:

1. over "option" or "ref" here (both type abbreviations) IncrementalBuild.fs

                         syntaxTreeOpt: SyntaxTree option,
                         lazyTcInfoState: TcInfoState option ref) =

2, over "IsSome" here IncrementalBuild.fs

        let hasSig = this.BackingSignature.IsSome

3. over "StartLine" here in FSHarp.Editor QuickInfoProvider.fs

                    (declRange.StartLine, extLexerSymbol.Ident.idRange.EndColumn, extLineText, extLexerSymbol.FullIsland, FSharpTokenTag.IDENT)

4. over "Symbol" here in FSharp.Editor QuickInfoProvider.fs

                         Symbol = Some extSymbolUse.Symbol

5. over "fromZ" here in FSharp.Editor QuickInfoProvider.fs

            let fcsTextLineNumber = Line.fromZ textLinePos.Line

**Comment by dsyme** [comment]
As an aside, I notice that our unit tests test this helper function:

    static member ProvideQuickInfo(checker:FSharpChecker, documentId:DocumentId, sourceText:SourceText, filePath:string, position:int, parsingOptions:FSharpParsingOptions, options:FSharpProjectOptions, textVersionHash:int, languageServicePerformanceOptions: LanguageServicePerformanceOptions) =

However this isn't the actual implementation used by the actual editor, which goes via the much more complex `getQuickInfo` that handles cases to do with signature files and implementation files.

**Comment by dsyme** [comment]
(if this doesn't repro for others it may be some local issue on my machine and we can close it)

**Comment by cartermp** [comment]
It repros on my machine, horrible annoyance but never investigated

**Comment by cartermp** [comment]
This is indeed likely due to some interaction with signature files. Something changed a while back that caused this, since I've noticed it for many months. Mea culpa for not bothing to file an issue or investigate. I'll probably take a look since I'm the most active person in terms of bouncing back and forth between projects

**Comment by cartermp** [comment]
Okay, finally got around to investigating. This is a regression. The situation is:

* Project A has a source file with a backing signature file
* Project B references project A

In this case, hovering over a construct from A with a backing signature file from project B will not trigger QuickInfo.

I can't actually debug this yet though because we don't appear to deploy everything in debug builds that for loading and debugging an F# project. Only script files can be loaded in a debug instance right now.

**Comment by cartermp** [comment]
Got it :)

![Uploading image.png…]()
