### ISSUE TITLE
Operator Overloading Massively Broken

### ISSUE THREAD

**Issue by keldor314** [dotnet/fsharp#11056]
Operator overloading is breaking the type system in a spectacular fashion.  If I write a very simple bit of code like this:

```
let (+) (x:float) (y:float) = x+y
let b = 1+1
```

I expect that b=2, clearly.

What I get, however, is a compiler error.

```
  let b = 1+1
  --------^

stdin(32,9): error FS0001: This expression was expected to have type
    'float'    
but here has type
    'int'    
```

I can't imagine that this is expected behavior...

**Comment by cartermp** [comment]
This is by design. By re-defining `+`, you're changing any further (within scope) use of `+` to be only the one you've defined. You defined `+` to only work on floats, and so when you use it with ints you get a typecheck error.

What you're doing isn't overloading, it's redefining and shadowing the existing implement of  `+` (which is generic). If you want to work with only a redefined version of `+`, you can mark it as `inline` and make it generic like so:

```fsharp
let inline (+) x y = x + y
```

But that would be pointless since the existing `+` implementation is already generic.
