### ISSUE TITLE
Follow-up on FS-1091

### ISSUE THREAD

**Issue by pblasucci** [dotnet/fsharp#11189]
Hello team,

I just wanted to follow up on [FS-1091](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1091-Extend-Units-of-Measure.md) (or, if you prefer to look at PRs: #9978). 

Specifically, now that the work is properly available in preview, what steps (if any) need to be undertaken in order to get it "promoted" for the .NET 6 release? Or, if that's too soon a target, whatever the next available target is? And, in any case, is there anything else I can do to "move things along" (update docs, et cetera)?

Thanks!

**Comment by cartermp** [comment]
For the .NET 6 release, we'll likely do what we did for F# 5 and .NET 5:

* Preview enabled by default already, so anyone doing .NET 6 preview will have the feature available
* When we're locking down for the actual release, we move all preview language features we want into a proper F# language version that we create

That timeframe would probably be around September-October and would also align with a Visual Studio release, so everything would "line up" properly.

Since this and an overloads-for-CEs feature are the only F# vNext features that don't require more design work, these will be in the next F# langauge version. We just need to figure out when that will be and what it will be called.

**Comment by pblasucci** [comment]
Awesome! Thanks! 😊

Let me know if there's anything else you need on my end.

**Comment by cartermp** [comment]
If you've got some dank memes, you can send them our way. But otherwise I think we've got this handled well enough!


...he says, making famous last words.

**Comment by cartermp** [comment]
Will close out
