### ISSUE TITLE
Unexpected behavior of XML comment analyzer for functions returning lambda

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#11286]
**Repro steps**

Paste the following code snippets into the editor

```f#
///<param name="x"></param>
let f x =
    fun y -> false

///<param name="x"></param>
let g x =
    ()
    fun y -> false
```

**Expected behavior**

For both code snippets, the behavior of the XML comment analyzer is the same

**Actual behavior**

The first code snippet is accompanied by a warning about the lack of documentation for the parameter of the returned lambda
and there is no warning in the second code snippet

![image](https://user-images.githubusercontent.com/26364714/111900835-c6f12100-8a45-11eb-9af0-9b2f7879f7ad.png)

Is this a bug or is it by design?

**Comment by TheJayMann** [comment]
Not knowing the internals of the compiler, but making use of sharplab.io to see the code produced, what I can assume happening here is that the function `f` is being rewritten as ` let f x y = false` as the automatic currying feature means these two definitions are the same.  Meanwhile, with the extra statement in function `g`, the compiler cannot rewrite the function the same as the above, as now there is potentially code that would get executed simply by providing a value for `x` even if a value is not provided by `y`, thus requiring the use of `FSharpFunc` to ensure the extra code is executed at the expected times.  And, there does not appear to be an optimization in place to see that if the extra source code does not produce any actual executable code that it is able to safely rewrite the function in curried form.  Essentially, you could say that the compiler ends up treating `f` as `'a -> 'b -> bool`, while treating `g` as `'a -> ('b -> bool)`.

https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQFkBYAKFQAdsA7XAZQE8IAXbZEgeg4B4yBDAJx7JclQdgC8AIgAeEgHyc2vAclkkcjXGFxTcYkrgOaM1OrgC0szT2ARsJdlyWDhoyTPmL+g1cXW4A5tq6+oYAFACUIQZgxrimFlY22EA

**Comment by cartermp** [comment]
This is probably considered by design, since at all levels `y` is not considered a parameter of `g`.

Syntax: https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQD0PAPAA5UATlQC2YZGNgBeADqQAHvIB8vLoJGjls5DVgAXSmAVg5yCBHgBXcwE8wAWmWVa9HTp5cBwsRKlzFFTUNMW1dAzAAc2NTHQswAAoASjiLaztHZ2o6WEgQAF8gA

Typechecking:

![image](https://user-images.githubusercontent.com/6309070/111911703-d9f2f980-8a23-11eb-8e5f-baf398530f13.png)

vs.

![image](https://user-images.githubusercontent.com/6309070/111911712-e1b29e00-8a23-11eb-81c8-0dbee44dc44d.png)

and emit as mentioned

**Comment by cartermp** [comment]
Though this is certainly a quirk from the perspective of XML checking:

* If I do it "correctly" I also get a warning
* Tooling shows the parameter info and of course calling `g` with two parameters is correct

![image](https://user-images.githubusercontent.com/6309070/111911922-a2d11800-8a24-11eb-9bd1-d3058b1d1acc.png)

So I think there could be an improvement made here **only** for XML checking and it would have to dive a little deeper into the function body to pull out extra "parameters"?

**Comment by cartermp** [comment]
@dsyme your thoughts?

**Comment by dsyme** [comment]
THis is by design.

For better or worse, in F# the code

```fsharp
let f x =
    fun y -> false
```

is treated as if it is a method declaring two parameters `x` and `y`, covered in arity inference in the F# language spec, and a fixed decision since it affects what signatures the code matches.  This applies for lambdas directly on the right of a top-level definition. 
 This was a decision made early in F# 0.x to allow this style for top-level definitions, though we never particularly encourage it

**Comment by auduchinok** [comment]
Would it make sense to relax the XML analyzer only for this case?

In some cases it's hard to write a comment in a way the analyzer is fine with it, e.g. consider:

```fsharp
let f x y =
    if x then
        fun a -> ()
    elif y then
        fun b -> () // a different name here
    else
        ignore // an external function with its own parameter names
```
