### ISSUE TITLE
Generated Signature file omits namespaces, won't compile

### ISSUE THREAD

**Issue by l3m** [dotnet/fsharp#11473]
I have a project that didn't use signature files before. Following [StackOverflow](https://stackoverflow.com/questions/58781292/how-to-generate-f-signature-file-without-visual-studio), I added the --sig parameter to the build to generate the file. 

Signature file generation produces a file that cannot be compiled, since the types inside the signature file miss the root namespace. 

E.g. assume types RootNs.Sub1.TypeA, RootNs.Sub2.TypeB with TypeB as 

```fsharp 
namespace RootNs.Sub2 

open RootNs.Sub1 

type TypeB = {
    A: TypeA 
} 
```

The signature file will contain it as 

``` fsharp 
namespace RootNs.Sub2 
  type TypeB = 
    { A: Sub1.TypeA } 
```

and then fails to compile with 

```
  Sig.fsi(13, 18): [FS0039] The namespace or module 'Sub1' is not defined.
```

**Repro steps**

1. Add --sig parameter to build config 
2. Add the generated fsi to project
3. Compile project 

**Expected behavior**

The generated signature file should compile. 

**Actual behavior**

The generated signature file fails to compile. 

**System**

* Operating system: Win10
* .NET Runtime: .NET Core 3.1.408
* Tools: Rider,  dotnet cli

**Comment by pblasucci** [comment]
Out of morbid curiosity, could you provide some detail on the file structure? Specifically:

1. Are `Sub1` and `Sub2` modules or namespaces?
2. Is it safe to assume `Sub1` is in a different file from `Sub2`?

**Comment by l3m** [comment]
It's quite a large project, so the signature file is ~12k lines, and this happens in many places with different types. 

One case is where we have two fsprojs, both in the same root namespace but with different sub namespaces, and the second one refers to the first one. 

Another is where both are in the same fsproj, but again differ in the first sub ns (we merged some projects because it improved compile time by 25%). 

It's in different files in both cases, an the types are defined directly in namespaces, not in modules.

**Comment by pblasucci** [comment]
@l3m I just realized something... are you trying to use a single `.fsi` file for an entire project? Because that's definitely going to cause errors along the lines of: 

`[FS0039] The namespace or module 'Sub1' is not defined.`

There needs to be a 1:1 relationship between signature file and source file. So, typically, there are three approaches:

1. Hand-write the signature files (not pleasant on existing codebases).
2. Generate a single file for the whole project. Then _manually_ carve it into smaller files.
3. Iteratively, feed the compiler subsets of your source files in order to produce the individual signature files.

Note, even with the 3rd step, there's likely to be a bit of massaging you'll need to do to get the generated files just right.

At the end of the day, signatures are a very manual affair. I believe tooling could help this greatly.

**Comment by baronfel** [comment]
@pblasucci worth noting that yesterday a new 'allsigs' compiler option was merged that generates a single signature file pretty input fs file, to make step 2/3 easier.

**Comment by pblasucci** [comment]
Ooooo... Thanks, @baronfel! I somehow missed that one. :rocket:
