### ISSUE TITLE
Top level main and async main

### ISSUE THREAD

**Issue by bugproof** [dotnet/fsharp#11631]
In C# in .NET 5 we have top level statements and we can write code without defining `Main` and access `args` too. I think it would be a nice feature if we could define a certain file as an entry point e.g. `Program.fs` or `Main.fs` and write code as it was inside `main`

C# also allows to have async main and you can directly await from top-level statement too. In F# you need to do something like this https://stackoverflow.com/a/55210222 which is hard to remember

e.g. this is a valid code in C#

```cs
using System.Net.Http

using var httpClient = new HttpClient();
var str = await httpClient.GetStringAsync("https://example.com/");
Console.WriteLine(str);
```

If this feature was available in F# we could do:

```fs
open System.Net.Http

use httpClient = new HttpClient()
let str = httpClient.GetStringAsync("https://example.com/") |> Async.AwaitTask
printfn $"{str}"
```

**Comment by Szer** [comment]
Have you tried your own code?
Do you know that top level statements have been implemented in F# since I'm not sure when? :)

Your code already works in F#

**Comment by ChXIII** [comment]
F# has implicit entry points.
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/entry-point#implicit-entry-point

**Comment by cartermp** [comment]
This code works, sorta, but it's not a direct comparison due to (1) lack of implicit args, and (2) lack of implicit async-able `main`.

|thingie|access to command-line args|implicit async|
|-------|---------------------------|--------------|
|F# scripts|`fsi.CommandLineArgs`|no|
|"top-level" F# programs|no|no|

the C# code would have to actually look like this to be equivalent:

```fsharp
open System.Net.Http

let httpClient = new HttpClient()

let str =
    httpClient.GetStringAsync("https://example.com/")
    |> Async.AwaitTask
    |> Async.RunSynchronously

printfn $"{str}"
```

It's close, but not the same.

That said, this would be a language suggestion, since implicit async + access to command-line args are language-level things to consider.

If you could file an issue here, that'd be great @bugproof https://github.com/fsharp/fslang-suggestions
