### ISSUE TITLE
Visual Studio hangs/crashes when hovering over a nonexistent union case pattern

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#11667]
Visual Studio hangs/crashes when hovering over a nonexistent union case pattern.

**Repro steps**

1. Clone this repo's `main` (currently 4ce381be33818c148976f393c50050a1664a061e)
2. Run `build.cmd`
3. Open `FSharp.Compiler.Service.sln`
4. Under project `FSharp.Compiler.Service`, `ParserAndUntypedAST\SyntaxTree.fsi`, line 1138, change `Named` to `Name`
5. In `ParserAndUntypedAST\SyntaxTree.fs`, line 979, change `Named` to `Name`
6. In `ParserAndUntypedAST\FsYaccOutput\pars.fs`, line 5747, hover over `Named`
7. If Visual Studio doesn't hang, wait until type information fully loads
8. Visual Studio hangs (16.10.1) or crashes after a while (16.11p1)

**Expected behavior**

Visual Studio does not hang or crash.

**Actual behavior**

Visual Studio hangs (16.10.1) or crashes after a while (16.11p1).

**Known workarounds**

Nope.

**Related information**

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): N/A
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio 16.10.1 / 16.11 preview 1

**Comment by 0101** [comment]
This still reproduces. However it seems to only happen specifically in the generated `pars.fs`. Could be some edge case either related to the contents of the file or possibly to how it's included in the project.

Debugging shows StackOverflow exception which could indeed be the root cause
![image](https://user-images.githubusercontent.com/217092/214634196-90765f2f-334d-467a-a9c9-c5d896d021c7.png)

https://github.com/dotnet/fsharp/blob/dec4c916f3f0e8049069478e7799768e7cd70535/src/Compiler/Service/ServiceParsedInputOps.fs#L562
