### ISSUE TITLE
fsi: Microsoft.Win32.Registry is not defined

### ISSUE THREAD

**Issue by reneederer** [dotnet/fsharp#11678]
In a VS Interactive Window
`printfn $"{Microsoft.Win32.Registry.LocalMachine}"`
prints `HKEY_LOCAL_MACHINE`

Executing the same statement with ```cmd /c dotnet fsi``` gives me an error:
`stdin(1,28): error FS0039: The value, constructor, namespace or type 'Registry' is not defined.`

I also tried
```
#r "nuget: Microsoft.Win32"
#r "nuget: Microsoft.Win32.Registry"
printfn $"{Microsoft.Win32.Registry.LocalMachine}"
```
which gives the same error.

**Comment by cartermp** [comment]
The reason why `printfn $"{Microsoft.Win32.Registry.LocalMachine}"` doesn't work on `dotnet fsi` is because the type doesn't exist in the default set of references for .NET, but it does exist in legacy .NET Framework, which is the default FSI used in VS.

As for it not working when you have the package reference, that smells like a bug to me. We should be picking up that reference, since you can do the same in a .NET 5 app.

**Comment by dsyme** [comment]
This works for me with the package reference.  The other part is indeed by design
