### ISSUE TITLE
The error about the impossibility of inlining is not reported to IDE

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#11677]
**Repro steps**

```F#
module InlineTest =
    let private innerFunc x = x + 1
    let inline inlineFunc x = (innerFunc x) + 1


[<EntryPoint>]
let main _argv =
    InlineTest.inlineFunc 7 |> ignore
    0
```

It expectedly gives a compilation error:

**`[FS1113] The value 'inlineFunc' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible`**

But the error is not visible in IDE (Rider 2021.2 dev and Visual Studio 16.10)

![image](https://user-images.githubusercontent.com/26364714/121783588-2b8cc980-cbb8-11eb-98d7-2515ad7e1684.png)

![image](https://user-images.githubusercontent.com/26364714/121783550-ea94b500-cbb7-11eb-8141-b8dcd07f4de9.png)

**Comment by cartermp** [comment]
I suspect this is a quirk related to the difference in emitting an assembly vs running interactively. This code is perfectly valid in F# scripts and when evaluating (and running) in FSI. It would be good to differentiate between the two scenarios in tools.

**Comment by dsyme** [comment]
This was always intended - it's very hard to perform the check in the IDE without effectively re-running the optimizer at every file check, or adding an additional phase - so we decided to make this one of the very few deliberate "late emit" checks.

I'll close this as won't fix, because even if we list it as a feature improvement it's extremely unlikely we'll fix it.
