### ISSUE TITLE
Deadlock occurs after updating to FSharp.Core 5.0.2 in some rare cases

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/fsharp#11861]
### MCVE

.fsproj

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <TargetFramework>net5.0-windows</TargetFramework>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="5.0.2" />
  </ItemGroup>
</Project>
```

.fs

```fsharp
open System
open System.Windows
open System.Windows.Controls
open System.Threading.Tasks
open System.Collections.Concurrent
open System.Threading

let callOnUiThread f = 
    // works with TaskCreationOptions.RunContinuationsAsynchronously
    let tcs = new TaskCompletionSource<bool>()
    Application.Current.Dispatcher.BeginInvoke(Action(fun () ->
        try
            f()
            let res = string <| tcs.TrySetResult(true)
            ("res = " + res) |> printfn "%A"
        with exp ->
            let res = string <| tcs.TrySetException(exp)
            ("res = " + res) |> printfn "%A"
    )) |> ignore
    tcs.Task :> Task

type SomeView() =
    let bc = new BlockingCollection<int>()
    do bc.Add(90)
    let cs = new CancellationTokenSource()

    let lb = ListBox()
    let addItems c =
        callOnUiThread (
            fun () ->
                for i in 0..c do 
                    let lbl = Label(Content = string i, Margin = Thickness 5.0)
                    lb.Items.Add(lbl) |> ignore
        )

    let loop() =
        let mutable count = 0
        let mutable iter = 0
        let mutable flag = true

        let c = async {
            do! Async.Sleep 1000
            while flag do
                if bc.TryTake(&count, 800) then
                    do! addItems count |> Async.AwaitTask
                if iter > 1000 then
                    flag <- false
                iter <- iter + 1
            bc.CompleteAdding()
        }
        
        Async.Start(c, cs.Token)

    do loop()

    member _.View = lb

    interface IDisposable with 
        member _.Dispose() = 
            cs.Cancel()
            bc.CompleteAdding()
            bc.Dispose()

let view = new SomeView()
let win = Window(Height = 500.0, Width = 540.0, Content = view.View)

[<STAThread>]
Application().Run win |> ignore

(view :> IDisposable).Dispose()
```

The code above works fine until PR #11142 is merged where `TaskContinuationOptions.ExecuteSynchronously` option is specified to a continuation.

It seems like

```fsharp
tcs.TrySetResult(true)
```

line is blocking execution until async isn't finished its job.

Not sure whether it's a bug or not.

**Comment by dsyme** [comment]
Any chance you can check against main?  See #11799 though I don't think that will have fixed the above.

I am happy to remove the ExecuteSynchronously flag added in #11142, it is not necessary per [this comment](https://github.com/dotnet/fsharp/pull/11142#issuecomment-884294516).  In #11799 I considered doing that.

**Comment by FoggyFinder** [comment]
> Any chance you can check against main?

@dsyme the same, I've tested it this morning on main branch

**Comment by dsyme** [comment]
> @dsyme the same, I've tested it this morning on main branch

Thanks

**Comment by NinoFloris** [comment]
Effectively this is a trap in TaskCompletionSource (which they can't change due to BC), if you want to read more see: https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/

99% of the times you want to contstruct your tcs with the `TaskCreationOptions.RunContinuationsAsynchronously` option. There are some cases where synchronous execution is optimal but in cases where you're jumping to a dedicated thread be it a worker or a ui thread you probably want that to happen via a threadpool dispatch :)

@dsyme changing the Async.AwaitTask ContinueWith call to have ExecuteSynchronously is the * right * change and brings the behavior in line with async await (which has execute synchronously by default) however considering the amount of code depending on the original behavior (ContinueWith *always* dispatches) a revert might indeed be better.

**Comment by dsyme** [comment]
> @dsyme changing the Async.AwaitTask ContinueWith call to have ExecuteSynchronously is the * right * change 

Really?  We already check for synchronous completion here: https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/async.fs#L1940.  Why do we want ExecuteSynchronously when the task itself has not completed synchronously at this first check?  

Thanks
don

**Comment by NinoFloris** [comment]
Task continutions, especially those attached via awaiters by C#'s async await try to run inline as often as they can. 

The behavior before netcore3.1? even ran all awaiter attached continuations inline but that somewhat obviously serialized all the work too heavily and created hidden dependencies for (often) unrelated continuations. Status quo is to run the first continuation inline after completion, as this significantly improves perf, and to execute all other continuations via a threadpool dispatch.

**Comment by dsyme** [comment]
@KevinRansom I need your thoughts on this.

We have the option of treating  #11142 as a correct bug fix because of this logic, even if it changed some existing behaviour.

> changing the Async.AwaitTask ContinueWith call to have ExecuteSynchronously is the * right * change and brings the behavior in line with C# async await (which has execute synchronously by default) 

We could undo it. However:
1. it is in FSharp.Core already, so we'd be slamming around
2. has a performance impact
3. it brings our Async.AwaitTask out of line with C# async/await on tasks

The performance hit is probably negligible given other costs of F# async.  However I'm fairly sold on point (3). What do you think?

**Comment by KevinRansom** [comment]
I shall close the engineering issue.  @KathleenDollard will drive documentation.
