### ISSUE TITLE
  --noframework switch of fsi in VS .net core mode caused exceptions

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#11901]
**Repro steps**

1. turn on  --noframework in F# tool configuration page

**Expected behavior**

fsi in .net core mode should be with no error for code like "let a = 123"

**Actual behavior**

![image](https://user-images.githubusercontent.com/4289161/127232806-7a0637c4-61ea-4445-8d54-32d59ea723a9.png)

![image](https://user-images.githubusercontent.com/4289161/127232940-1264d399-ea8d-480f-be9a-b0d572a3d57e.png)

**Known workarounds**

None (not to use  --noframework switch ) 

**Related information**

Provide any related information (optional):

* Operating system : windows server 2019
* .NET Runtime kind (.NET Core, .NET Framework, Mono) : .net 5.0 (sdk 5.0.400-preview.21328.4)
* Editing Tools (e.g. Visual Studio Version, Visual Studio) vs2019 preview (16.11.0 preview 3.0)

**Comment by ingted** [comment]
Seems like #r @"FSharp.Core.dll" is required to be part of the beginning code...

**Comment by KevinRansom** [comment]
This is by design:

````
--noframework                            Do not reference the default CLI assemblies by default
````

--noframework, turns off our hunting for framework assemblies.  If it's used you need to provide references to every assembly that needs to be referenced.

By and large ... there are no valid scenarios for using it any longer, and probably were never any valid scenarios for fsi.

Kevin
