### ISSUE TITLE
Segmentation fault when passing byref parameters to tailcall methods

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#12085]
### Description

I came across a segmentation fault when working on some F# code. A minimal reproduction showcasing the bug can be found [in this repo](https://github.com/eiriktsarpalis/SegmentationFaultRepro/tree/master). The following error is thrown when trying to run the console app using release builds:
```
Fatal error. Internal CLR error. (0x80131506)
   at System.Array.GetEnumerator()
   at Program.<Main>$(System.String[])
Segmentation fault
```
I believe the issue is triggered by the F# compiler inserting a `tail` opcode in the [`Get` method](https://github.com/eiriktsarpalis/SegmentationFaultRepro/blob/cbf562954b969c44572086a1fe988b7a5dc4a768/ClassLibrary/Getter.fs#L7). Relevant IL:
```
.method public hidebysig 
	instance !FieldType Get (
		!DeclaringType 'instance'
	) cil managed 
{
	// Method begins at RVA 0x2064
	// Code size 16 (0x10)
	.maxstack 8

	// return getter(in instance);
	IL_0000: ldarg.0
	IL_0001: ldfld class ClassLibrary.Getter`2<!0, !1> class ClassLibrary.GetterWrapper`2<!DeclaringType, !FieldType>::getter
	IL_0006: ldarga.s 'instance'
	IL_0008: tail.
	IL_000a: callvirt instance !1 class ClassLibrary.Getter`2<!DeclaringType, !FieldType>::Invoke(!0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute))
	IL_000f: ret
} // end of method GetterWrapper`2::Get
```

### Configuration

* Which version of .NET is the code running on? _6.0.100-rc.2.21426.20_
* What OS and version, and what distro if applicable? Windows 10 21H1. Does not reproduce on Linux x64.
* What is the architecture? x64. Windows arm64 surfaces a nullref exception instead.
* Do you know whether it is specific to that configuration?
* If you're using Blazor, which web browser(s) do you see this issue in?

### Regression?

Not a regression, this reproduces in .NET 5 as well.

**Comment by dsyme** [comment]
@TIHan At a guess I'd suggest the problem is that we're specifically not checking for byrefs being passed to delegate.Invoke methods

https://github.com/eiriktsarpalis/SegmentationFaultRepro/blob/master/ClassLibrary/Getter.fs#L7

**Comment by eiriktsarpalis** [comment]
@jakobbotsch Thanks. The reason why I posted this in runtime in the first place is that I expected IL like this to be handled more gracefully (e.g. by throwing `AccessViolationException`/`InvalidProgramException`). This can often manifest as silent memory corruptions.

@dsyme does the F# compiler have a mechanism to suppress the `tail` opcode in specific methods during release builds?

**Comment by jakobbotsch** [comment]
It's not really possible for us to generally know if a byref will point to the local stack frame or not to be able to throw `InvalidProgramException`. Any such analysis will be an approximation so would potentially reject valid programs that never pass the address of a local. That's why we only do the approximate analysis when no tail. prefix is present and don't do fast tailcalls in that case.

This case is not much different than returning the address of a local from a function. That's valid IL but if you use the address then you will corrupt random parts of the stack and the way it fails is completely nondeterministic. In the same way, the failure mode for this particular issue would also be able to throw `AccessViolationException` in different circumstances (e.g. if you override the return address on the stack that would probably be the most likely outcome).

**Comment by dsyme** [comment]
The bug is that we don't notice the Byref because it's hidden under a cmod:

```
                  let hasByrefArg = mspec.FormalArgTypes |> List.exists (function ILType.Byref _ -> true | _ -> false)
```

I'll get a fix prepared

**Comment by dsyme** [comment]
> @dsyme does the F# compiler have a mechanism to suppress the tail opcode in specific methods during release builds?

There's no specific mechanism, though this works, there are bound to be simpler ways
```fsharp
    member _.Get (instance : 'T) = 
        let mutable x = 1
        let res = getter.Invoke &instance
        x <- 2
        res
```
