### ISSUE TITLE
Display of multidimensional array looks like list of lists

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#12115]
I thought the display or `sprintf "%A"` or `.ToString()` of a multidimensional array would look like an array of arrays.  Instead, it looks like a list of lists.

More specifically, consider these lines of F# interactive.

```fsharp
// 1
> [0];;
val it : int list = [0]

// 2
> [|0|];;
val it : int [] = [|0|]

// 3
> [[0]];;
val it : int list list = [[0]]

// 4
> [|[|0|]|];;
val it : int [] [] = [|[|0|]|]

// 5
> Array2D.zeroCreate<int> 1 1;;
val it : int [,] = [[0]]
```

I expected case 5 to look like case 4.

Actually, case 5 looks like case 3.

Is this intentional.  It feels like a bug to me.

**Comment by dsyme** [comment]
It's a bug, thank you

**Comment by dsyme** [comment]
I mis-commented here - I'm not sure why I said "it's a bug" - my apologies. See my reply here https://github.com/dotnet/fsharp/pull/12199#issuecomment-934244360

I see the inconsistency, which is currently by design.  However if anything we should print 

```
array2D [[0]]
```

perhaps with extra spacing (if we do that consistently for all lists)
```
array2D [ [ 0 ] ]
```

**Comment by TysonMN** [comment]
I like that because `array2D` is a function and the type of `array2D [[0]]` is `[,]`.  I think being able to parse/compile your own "to string" is a good property to have.

**Comment by dsyme** [comment]
We talked about this in #12199 and decided not to make any change, so will close
