### ISSUE TITLE
Compiler infers wrong DU type

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/fsharp#12131]
If you have two separate DU's that have a matching case name, then the compiler fails to properly infer the type in a match statement.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a new F# program
2. Add the following to Program.fs:
```fsharp
type A =
| Updating
| Done

type B =
| Updating
| Complete

type C = {
    Status:A
}

[<EntryPoint>]
let main argv =

    let c = { Status = Done }

    match c.Status with
    | Updating -> 0
    | Done -> 1
 ```   
3. Compile

**Expected behavior**

This should compile. The compiler knows that type `C` has a member which is of type `A`. The union case shouldn't think that it is type `B`.

**Actual behavior**

![image](https://user-images.githubusercontent.com/9649518/132587315-3bb1c01b-af5c-4162-a530-fbf890076971.png)

**Known workarounds**

You can fully qualify the name, so that the match statement looks like this:
```fsharp
    match c.Status with
    | A.Updating -> 0
    | Done -> 1
```

But this makes refactoring F# code *very* painful. The F# ordering already makes refactoring painful, but I can live with that. But now I have to go fix up all of the compiler errors b/c a type is now defined before a different one.

**Comment by dsyme** [comment]
This is by design as things stand, e.g. if you track through the rules of the F# language spec carefully.

Using RequireQualfiedAccess is recommended if you are going to overlap case names.

Please feel free to add a suggestion to https://github.com/fsharp/fslang-suggestions to infer union case names from known type information.  To my knowledge there is no suggestion for this at the moment.  We decided not to do this in F# 2.0 though it would be fairly consistent for the language design to do so
