### ISSUE TITLE
The type 'Async<'a>' does not support the operator 'GetAwaiter' error after updating Fsharp.Core to 6 version

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#12184]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

I've tried updating pulsar library to Fsharp.Core and removed TaskBuilder.fs dependency, then tried to build project.
[Link to commit](https://github.com/fsharplang-ru/pulsar-client-dotnet/commit/06f77713552ab8f7754c6410facf8431a0d245b1)
Branch **fsharpsix**
[Link to failed github action](https://github.com/fsharplang-ru/pulsar-client-dotnet/runs/3704772222?check_suite_focus=true)

**Expected behavior**

_dotnet build_ works fine on Pulsar.Client project (\src\Pulsar.Client)

**Actual behavior**

I'm getting errors [on this file](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/06f77713552ab8f7754c6410facf8431a0d245b1/src/Pulsar.Client/Internal/BinaryLookupService.fs)

  BinaryLookupService.fs(100, 9): [FS0001] The type 'Async<'a>' does not support the operator 'GetAwaiter'
  BinaryLookupService.fs(129, 9): [FS0001] The type 'Async<'a>' does not support the operator 'GetAwaiter'

**Known workarounds**

- Specify the returning type directly
- Reorder methods

**Related information**

Provide any related information (optional):

* Windows 10
* Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
* Jetbrains Rider

**Comment by vzarytovskii** [comment]
CC @dsyme @TIHan

**Comment by gsomix** [comment]
Error message is confusing, but it seems there is problem at the junction of type inference and method overload resolution in `TaskBuilderBase`.

Minimal repro extracted from @Lanayx repo:
```fsharp
open System

type TaskBug() =
    member this.AsyncComputation() =
        task {
            let! result = this.AsyncComputation(21)
            printfn "Result: %d" result
            return result
        }

    member internal _.AsyncComputation(value: int) =
        async {
            do! Async.Sleep 500
            return (value * 2)
        }

[<EntryPoint>]
let main args = 
    let tmp = TaskBug()
    tmp.AsyncComputation() |> ignore
    0
```

There is also workaround — provide hint for return type to the compiler:
```fsharp
member internal _.AsyncComputation(value: int): Async<int> = async { ... }
```

**Comment by Lanayx** [comment]
Thank you, @gsomix , this helped indeed, I'll update the issue

**Comment by gsomix** [comment]
I've updated minimal repo to make it clear issue has nothing to do with method overloading in user code.

**Comment by dsyme** [comment]
> I've updated minimal repo to make it clear issue has nothing to do with method overloading in user code. It's also worth noting that both TaskBuilder.fs and Ply handle this correctly.

Interesting, thank you.  I don't yet consider this a bug - given the overloading involved the need for stronger type information is not that surprising - so we are likely to be willing to accept the divergence from TaskBuilder.fs and Ply here.

Thank you
Don

**Comment by Lanayx** [comment]
@dsyme The error message doesn't give any clue of what went wrong and how to fix it, so the best thing a developer can do is to google the error and find this issue and then find the workaround and apply it.

**Comment by dsyme** [comment]
> @dsyme The error message doesn't give any clue of what went wrong and how to fix it, so the best thing a developer can do is to google the error and find this issue and then find the workaround and apply it.

This is true (and a general problem with failures in SRTP resolution)

**Comment by NinoFloris** [comment]
After taking a look in Ply it looks to be because TaskBuilder.fs and Ply both force the overload resolution to delay committing to an overload.

Given the following reduced set of overloads in Ply: 

```fs
    type Bind() =
        inherit Default1()

        static member inline Invoke (m: ^a, taskLike: ^b, cont: 't -> Ply<'u>) =
            ((^a or ^b) : (static member Bind : _*_*_ -> Ply<'u>) taskLike, cont, m)

        static member inline Bind(taskLike: ^taskLike, cont: 't -> Ply<'u>, [<Optional>]_impl:Default1) =
            Binder<'u>.GenericTpl<_,_,_>(taskLike, cont)

        static member inline Bind(async: Async<'t>, cont: 't -> Ply<'u>, [<Optional>]_impl:Bind) =
            Binder<'u>.Tpl<_,_>((Async.StartAsTask async).GetAwaiter(), cont)

        static member inline Bind(ply: Ply<'t>, cont: 't -> Ply<'u>, [<Optional>]_impl:Bind) =
            Binder<'u>.Ply(ply, cont)

        static member inline Bind(_: Id<'t>, _: 't -> Ply<'u>, [<Optional>]_impl:Bind) =
            failwith "Exists to force delayed resolution of the _impl = Bind overload set."

        // Removing one of these overloads (Id<'t> or Id2<'t> causes overload resolution to commit right away.)
        static member inline Bind(_: Id2<'t>, _: 't -> Ply<'u>, [<Optional>]_impl:Bind) =
            failwith "Exists to force delayed resolution of the _impl = Bind overload set."
```

Running this against the minimal repro given by @gsomix compiles, removing either the `Id<'t>` or `Id2<'t>` overload lets overload resolution commit eagerly on the SRTP `where impl = Default1` overload again causing the compilation error.

@dsyme would something in #6805 change the situation? For instance? https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1043-extension-members-for-operators-and-srtp-constraints.md#weak-resolution-no-longer-forces-overload-resolution-for-srtp-constraints-prior-to-generalizing-inline-code 
From the examples it does not look like it, given this delaying of resolution present in TaskBuilder/Ply * only * works with 2 or more unsealed classes involved in the overload set while the example just involves structs.

However if it does - or with additional changes could - improve the situation it sounds like an easy choice to let it be until that lands. If that's not the case would you want to change something in the CE before 6.0?

**Comment by dsyme** [comment]
@NinoFloris Thanks.  I'll take a look on Thursday and find a resolution.  We should either be leaving the type inference unresolved of committing to `Task<_>`.  At the moment it seems to be committing to `^TaskLike`, which I agree doesn't feel right.  This also applies in a case like

```fsharp
let TaskMethod(f) =
    task {
        let! result = f() 
        return result
    }
```

**Comment by dsyme** [comment]
@NinoFloris #12202 contains what a fix for part of this related to overload sets involving some SRTP constraints. This improves error messages when sufficient type annotations are missing and allows the code
```fsharp
    let TaskMethod t =
        task {
            let! result = t
            return result
        }
```
Previously this was giving a cryptic error because the SRTP constraints were being partially applied.

Note that the intended behaviour [according to the RFC](https://github.com/fsharp/fslang-design/blob/main/preview/FS-1097-task-builder.md#bind-returnfrom-support) is that the overloads have the following priority:

* Highest: `Task<'T>`
* Medium: `Async<'T>`
* Lowest: ` ^TaskLike `

With this design, overloads are resolved eagerly, and the highest priority one will be chosen based on available type annotations. So if you don't specify a type, `Task<_>` will be assumed.  For example

```fsharp
let TaskMethod t =
    task {
        let! result = t
        return result
    }
```
will compile and infer type
```fsharp
val TaskMethod: t: Task<'a> -> Task<'a>
```

I know this differs from TaskBuilder.fs but this seems like a reasonable design to me which prevents SRTP constrains floating everywhere throughout resolution (with their accompanying difficult error messages).

How problematic do you think it is to require the additional type annotations?  To be honest it feels good to me that we default to `Task<_>` in the absence of type information, and that we also avoid creating and propagating such complex SRTP constraints as those that arise for TaskLike overloads.
