### ISSUE TITLE
Auto-complete triggering keyword completions too often

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12317]
If we type this:
```fsharp
type Option(v)
```
then `void` appears as a completion - when we hit `:` this text is inserted

![image](https://user-images.githubusercontent.com/7204669/139530739-a28cac7f-480b-48a2-a3af-7b46720d06c7.png)

**Comment by smoothdeveloper** [comment]
Beside avoiding `:` to complete, what would be the ideal expected behaviour, beyond the bug fix?

Maybe it should only list things that are valid as binding pattern in this particular context ? maybe propose some of the attributes that are valid to put on method parameters (with the whole `[<` `>]` prefix/suffix baked in the intelisense list).

**Comment by dsyme** [comment]
Labelling this as a regression - it's been like this a while but not forever, and should never have been allowed to regress

**Comment by dsyme** [comment]
> Beside avoiding : to complete, what would be the ideal expected behaviour, beyond the bug fix?

I don't really know, I haven't looked at the FSharp.Editor completion code in quite a long time and it's a bit unclear what all the options are.

My first thought on a minimal fix is that this https://github.com/dotnet/fsharp/blob/b3d46d435eaf3aaf457b67e14f3634113e2f5888/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L54 should be `noCommitOnSpaceRules`?  Are you familiar with this code?

It seems this only affects keywords, and may be exactly what's needed?

**Comment by dsyme** [comment]
Fixed by https://github.com/dotnet/fsharp/pull/12318, manual testin so far

**Comment by dsyme** [comment]
Duplicate of https://github.com/dotnet/fsharp/issues/11145
