### ISSUE TITLE
Type variables escape analysis differs for records and classes

### ISSUE THREAD

**Issue by gsomix** [dotnet/fsharp#12343]
Compare following code samples:

```fsharp
type ArrayView<'T when 'T : (static member (+) : 'T * 'T -> 'T)> =
    { Values: 'T[] }
```

```fsharp
type ArrayView<'T when 'T : (static member (+) : 'T * 'T -> 'T)>
    (values: 'T[]) =  
    
    member val Values = values with get
```

**Expected behavior**

The second code sample compiles without error.

**Actual behavior**

Even though both samples should compile into similar IL code, the second one fails with error:
```
error FS0670: This code is not sufficiently generic. 
The type variable  ^T when  ^T : (static member ( + ) :  ^T *  ^T ->  ^T)
could not be generalized because it would escape its scope.
```

**Known workarounds**

Use records instead of classes when generic wrappers with constraints are needed.

**Related information**
```
> dotnet --version
6.0.100-rc.2.21505.57
```

**Comment by dsyme** [comment]
To be honest, this is by design.  

First, SRTP constraints shouldn't generally be used on classes. This is because they only really make sense in inlined code.  If they are used anywhere, they must be used in inlined code. 

Now, record fields are not code. So they van have SRTP type ok,

However `member val` properties are shorthand for a simple property `member x.v = _backingValue`. And that is code, even if it's very simple code.  So that code would need to be inlined, but `member val` can't be inlined. So all in all you so can't use SRTP in `member val`.

**Comment by gsomix** [comment]
Thank you for clarification!

**Comment by gsomix** [comment]
OK, I will leave note for myself. I can't manually inline property because it exposes internal backing value.

```fsharp
type ArrayView<'T when 'T : (static member (+) : 'T * 'T -> 'T)>
    (values: 'T[]) =  
    
    member inline _.Values = values
```
```
error FS1113: The value 'Values' was marked inline 
but its implementation makes use of an internal or private function 
which is not sufficiently accessible
```
