### ISSUE TITLE
Error "A protected member is called or 'base' is being used" in F# 6 new Task computation expression

### ISSUE THREAD

**Issue by sep2** [dotnet/fsharp#12448]
Base method call cannot be used in F# 6 task computation expression.

**Repro steps**
Using YARP direct proxy requires a `CustomTransformer` to inherit from `HttpTransformer`, and calling the base method in the overrided method.

https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

```f#
type CustomTransformer() =
    inherit HttpTransformer()

    override this.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix) =
        task {
            do! base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix)
            proxyRequest.Headers.Host <- null
        }
        |> ValueTask

```

**Expected behavior**

The above code should work as same as the async version in C#:

```c#
class CustomTransformer : HttpTransformer
{
    public override async Task TransformRequestAsync(HttpContext httpContext,
        HttpRequestMessage proxyRequest, string destinationPrefix)
    {
        await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
        proxyRequest.Headers.Host = null;
    }
}
```

**Actual behavior**

The F# version shows error at the call to the base method:

> A protected member is called or 'base' is being used. This is only allowed in the direct implementation of members since they could escape their object scope

**Known workarounds**
Put the base method in another method and call that instead:

```f#
type CustomTransformer() =
    inherit HttpTransformer()

    member this.BaseTransformRequestAsync(httpContext, proxyRequest, destinationPrefix) =
        base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix)

    override this.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix) =
        task {
            do! this.BaseTransformRequestAsync(httpContext, proxyRequest, destinationPrefix)
            proxyRequest.Headers.Host <- null
        }
        |> ValueTask
```

**Related information**

* Operating system: Linux
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .net6
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Rider

**Comment by dsyme** [comment]
This is by design - the same restrictions apply to all computation expressions, which are considered closures.  F# closures do not allow access to `base`

**Comment by sep2** [comment]
I understand this is by design, but don't understand why design it like this? Is there any implementation difficulty or limitation? I would like to know more about the reason behind the restriction, if possible. Any resource or link would be better, thanks!

**Comment by dsyme** [comment]
In F#, closures are not guaranteed to be generated into the enclosing class definition - they can be generated into a "Startup" class, for example, or similar.  In theory this restriction could be lifted but there are technical issues with doing that related to generics.

And base protected members are only accessible from the actual class definition.  So we have to limit base access within closures.

**Comment by auduchinok** [comment]
> In theory this restriction could be lifted but there are technical issues with doing that related to generics.

@dsyme Could you share more details about the issues or show an example, please? I'm really curious what blocks us here.

**Comment by deyanp** [comment]
Got hit by this, this is completely non-intuitive ...

**Comment by En3Tho** [comment]
Got hit by this too.

```fsharp
type FooHandler(innerHandler) =
    inherit DelegatingHandler(innerHandler)

    override this.SendAsync(request, cancellationToken) =
        base.SendAsync(request, cancellationToken)

type FooHandler2(innerHandler) =
    inherit DelegatingHandler(innerHandler)

    override this.SendAsync(request, cancellationToken) = task {
        // The member or object constructor 'SendAsync' is not accessible.
        // Private members may only be accessed from within the declaring type.
        // Protected members may only be accessed from an extending type and cannot be accessed from inner lambda expressions.
        // (FS0491)
        let! foo = base.SendAsync(request, cancellationToken)
        return foo
    }
```

I personally don't see how this is by design. It rather feels like a full fledged compiler bug.

**Comment by T-Gro** [comment]
The design flows from where the code inside `task{}` lands - it goes into a separate state machine type which is compiler generated. That type does not have access to any `protected` members, and would not be allowed by the rules of IL.

The design for how and where state machines are generated would have to change.
Part of it was attempted as part of `realsig`, but hit the problems with generics Don mentioned above - it is not as easy as it seems.

A possibility is to re-expose the protected member as an internal/public one, that it can be used within any closure or computation expression. Since this changes visibility, it is left to be an explicit action to be done by the programmer.
Even though it would be possible to generate such re-exposing wrapper by the compiler, it should be better treated as a new suggestion for F#.



Example of existing codegen and placement of state machine for code inside `task{}` :

https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWACh5l0tc8A6AOQW2NNUx3yoCUBXJbASzwRU0CAE68AhsF4AvcXxhJixbBkQoAshgDqCAEbsEAR04IcACgCUKALzEU9lLyQALUb2wod+oyfMWlRA4oMABuomIAJggo2M68EFTq9M4wEXZBDgDu7s4oAOb0ljYoAEQl6Rko4kgRKBD0KAD6xZYBQaHhvFExcQkGxqbYAKpixSO8ZiXO2NhwIAD088AwAMaSKTgl/kQVKIsoAPKxolW6OCLiKx4CeLqiEChmeE78knXYnGfb7WEikdGxeJUADi9H6vmwaGwIgQ4jwRWsKAu8WiZhoMGwAEk8HBgPhkLgIgBRAAeKwQcHkSEs3wcHT+XQBvRBYNMcAU9QRSPEKMe6KxOLxAh4CGJZIpVJpu3p/x6QIAgroYCJsFzWjtAg59gdfrLjig4CIMQgrqKUAJYqlpbrGXKEqDsAddAArE3YAAicnEZicYBgIHQbkkMjkvAUmKQfoANCgVgpcCTsAGoTC4U48gBheMIRNWWyayp4jy6Yq6cT1FmOl1uz3Yb2+mAxuMi3O7IJFmLFNuVGLlgDWAG9uz2tfMUGWKw6na6rrX65HG7Hs7nY9UkBjx9FOPVaq4YTG7mtt0zoitgOWHn6RD1ojg5NE8Jc4khovEUBFeGAwKICSgwEa8A0bQ9HBQZhxHewSwAX3A7AOFMThgGwIA=

**Comment by Happypig375** [comment]
C# has no problem generating an additional member when a base call is invoked in a closure. https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0BJA8gblg5aAcgKYAuucSKqASgK4B2pAlgLbGoDKxATswIYAbZgC9+LAPYMKeMIgDqxAEY1iARzrEAzqTkAuBctUbtpRAG9YsRDeQBmRBIBuvPgBNiBJAFkyACwk3C0QAczJsRC1wxABfKxhbe0cXHndPAFU+RGNNHUzmRABeAD5EBmIAd0R8gAoAIj9SUgAHPQB6NsEJAGMhAJ06gEoZBNsOxExSP15EfiUdHn5us3ZWJV4tRBrWZgY2IUjSOnnB61sQB2dXZg9ETlIeYn5WRABxMhzTe8fnmsGi0pTHgSKrlKqECSkdCsZqCYjsJjENwAUQAHt1iM1JAw/hREhdktdbooVNpmlIom8PmSKcQ/gDEECQWVKogIVCYXCEaQkWiMVjmFJcWcbASrqkbp4QAAWRAAQSUEh4pHp5liiHiiXGmBSaUZ00QzWBPOWSMQ7CmgRFhuNxFNQXFepAAA5kLL3qRMEoAFZ20gAEXE/Bq3D4QlE4kFDHQDAAZhJELt4wAaO4PJ47BghADCUh5qLM3TzxAL/0so0SNiU/CiqA9Xt9y0DpGDSYkqaLiNLeMrNmtiTBBDANXpJUQ1dr9Z9fubrbj7cQnfzpEGg2FFdisBiQA===

**Comment by T-Gro** [comment]
C#  generates the closure in an inner class, which then has access to a compiler generated wrapper for the base call.
F# does not always generate closures as inner classes and changing that would need to overcome bigger technical design changes and  limitations - the `realsig` implementation covered some of them. 

I don't think such a big change would be justified by the `protected` issue.
I am wondering if a codefix to generate an internal re-exposed wrapper for the base call wouldn't solve most of the problems here.
