### ISSUE TITLE
Could this be an index parsing bug? or is it expected?

### ISSUE THREAD

**Issue by thomasd3** [dotnet/fsharp#12549]
let's consider this code:

```
type T =
    {
        a: int
    }    

let d =
    [
        "a", [{a = 0}; {a = 1}; {a = 2}]
        "b", [{a = 3}; {a = 4}; {a = 5}]
    ] |> Map

```

If I want to access the data with a = 0:

```
d.["a"].[0].a  <- works
d["a"].[0].a   <- now works with F#6
d["a"][0]      <- returns {a = 0}
```

but

`d["a"][0].a    <- typecheck error This value is not a function and cannot be applied.
`
if I wrap the expression in parenthesis:

`(d["a"][0]).a  <- it works
`
Is this expected, or could it be a F#6 parsing bug?

**Comment by thomasd3** [comment]
for reference, the SO post, in case more info comes out there: https://stackoverflow.com/questions/70500857/could-this-be-a-f-6-indexer-bug

**Comment by dsyme** [comment]
For F# 6 this is by-design, for compatibility reasons, though we need to call it out explicitly in https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1110-index-syntax.md

From a compatibility perspective,

    d["a"][0].a

parses as a function application

    d["a"][0].a
    ^^^^^^+++++

And while this doesn't type-check, because `d["a"]` is not a function, in F# 6 there is no rule to allow the alternative interpretation as a left-associative series of index lookups for this case.  Thus for compatibility reasons the parentheses are required.

**Comment by dsyme** [comment]
Please feel free to open a language suggestion at https://gitub.com/fsharp/fslang-design.  Thanks!
