### ISSUE TITLE
FSI F# interactive add clear screen

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#12646]
Suggestion/idea add an alias to clear screen in F# interactive / dotnet fsi

like #clear;;

```fsharp
> #clear;;


/Users/admin/Repositories/scripts/test_url_check.fsx(1576,1): warning FS3353: Invalid directive '#clear '

> #clean;;


/Users/admin/Repositories/scripts/test_url_check.fsx(1577,1): warning FS3353: Invalid directive '#clean '

> #clscr;;


/Users/admin/Repositories/scripts/test_url_check.fsx(1578,1): warning FS3353: Invalid directive '#clscr '

> Clear all;;


/Users/admin/Repositories/scripts/test_url_check.fsx(1579,
val it: unit = ()

> 
```

we should add an alias to clear the screen for:

```fsharp
System.Console.Clear();;
```

**Comment by dsyme** [comment]
I'm fine with adding this.

**Comment by jkone27** [comment]
i have spotted this file, but cannot guess the place where I could add the alias for ```#clear``` in code, anyone could help me find where to add the alias to ```System.Console.Clear()```?
```src/fsharp/service/ServiceLexing.fs```

**Comment by baronfel** [comment]
Hi @jkone27 - all of the Hash-Directive handling is in [`fsi.fs`](https://github.com/dotnet/fsharp/blob/45518d21e1e135693ad3d9d32744792ba151aef4/src/fsharp/fsi/fsi.fs#L2613-L2685) if you want to add onto that.  It might not be _quite_ as simple as `System.Console.Clear()`, but there is a type `FsiConsoleOutput` in that same file that should be an appropriate place to add that functionality.

**Comment by jkone27** [comment]
isn't it safe to invoke System.Console.Clear()? 
it works in fsharp interactive already if you try it, why not using that?

**Comment by baronfel** [comment]
it's less about it being 'safe' to invoke System.Console.Clear, and more about a separation of concerns in my opinion. Since console output goes through FsiConsoleOutput right now, we should centralize all operations dealing with output there, IMO.

Your approach looks fine to me, but you probably don't need both `_.clear()` and `out.clear()` - one is enough. Then you'd invoke that from a new case in the match expression I linked earlier and you should be good-to-go!

**Comment by jkone27** [comment]
was merged! thank you so much, F# community is awesome!
