### ISSUE TITLE
Fails for newly installed dotnet: dotnet new console -lang F# project

### ISSUE THREAD

**Issue by FalkoSp** [dotnet/fsharp#12717]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: Windows 10 Enterprise

I just installed dotnet. The command

dotnet new console -lang F# -o fsharptest01 

creates the project, but then gives an error. 
The error message 
>>error NU1100: "FSharp.Core (>= 6.0.1)" kann für "net6.0" nicht aufgelöst werden.
  Fehler beim Wiederherstellen von "..\fsharptest01\fsharptest01.fsproj"<< 

translates as:

error NU1100: "FSharp.Core (>= 6.0.1)" can not get resolved for "net6.0". Error restoring ..\fsharptest01\fsharptest01.fsproj"

What can I do?

Complete output:

```
Willkommen bei .NET 6.0!
---------------------
SDK-Version: 6.0.102

----------------
Ein ASP.NET Core-HTTPS-Entwicklungszertifikat wurde installiert.
Um das Zertifikat als vertrauenswürdig einzustufen, führen Sie "dotnet dev-certs https --trust" aus (nur Windows und macOS).
Weitere Informationen zu HTTPS: https://aka.ms/dotnet-https
----------------
Schreiben Sie Ihre erste App: https://aka.ms/dotnet-hello-world
Neuigkeiten: https://aka.ms/dotnet-whats-new
Dokumentation: https://aka.ms/dotnet-docs
Probleme melden und Quelle in GitHub suchen: https://github.com/dotnet/core
Verwenden Sie "dotnet --help", um verfügbare Befehle anzuzeigen, oder besuchen Sie https://aka.ms/dotnet-cli.
--------------------------------------------------------------------------------------
Die Vorlage "Konsolen-App" wurde erfolgreich erstellt.

Aktionen nach der Erstellung werden verarbeitet...
"dotnet restore" wird auf ..\fsharptest01\fsharptest01.fsproj ausgeführt...
  Wiederherzustellende Projekte werden ermittelt...
..\fsharptest01\fsharptest01.fsproj : error NU1100: "FSharp.Core (>= 6.0.1)" kann für "net6.0" nicht aufgelöst werden.
  Fehler beim Wiederherstellen von "..\fsharptest01\fsharptest01.fsproj" (in "105 ms").
Fehler beim Wiederherstellen.
Fehler beim Posten der Aktion.
Manuelle Anweisungen: "dotnet restore" ausführen
```

**Comment by baronfel** [comment]
Hi! can you check the output of `dotnet nuget list source` on your command line? It may be that your NuGet sources are corrupted somehow. If they are, you should be able to run `dotnet nuget add source "https://api.nuget.org/v3/index.json"  -n "nuget.org"` to add the source back to your global configuration file.

**Comment by eriawan** [comment]
@baronfel 

I think I have a clue on what's going on.

Looking at the .NET SDK he used, he has .NET SDK 6.0.2.
I think this is a known bug in that version of 6.0.102:

- https://github.com/dotnet/winforms/issues/6663
- https://github.com/dotnet/runtime/issues/65018

After I isolate the 6.0.102 SDK, it seems affect FSharp.Core assembly as well. 
Basically, the Fsharp.Core is using `AssemblyVersionAttribute` of 6.0.0.0 in .NET SDK 6.0.100 and 6.0.101. 
But this was changed in 6.0.102, when it is using different `AssemblyVersionAttribute` version of "6.0.2.0".
And yes, you will have problems like the original post, and afaik it is reproducible.

Therefore, best way to solve this is _**to uninstall .NET SDK 6.0.102 and then install and use .NET SDK 6.0.101 instead**_, while wait for next emergency SDK fix. If the fix is within the timeframe for the upcoming 6.0.1xx SDK patch, the upcoming .NET SDK version will be 6.0.103. 

Unfortunately, there's no exact timeframe that I know when this 6.0.103 will be released.

PS, CMIIW and I welcome feedback.

**Comment by eriawan** [comment]
@baronfel 

One more thing, if my explanation above is confirmed, then this issue should be marked as bug, IMHO.

**Comment by FalkoSp** [comment]
@baronfel It says (in german :-) ) "No sources found"

**Comment by eriawan** [comment]
> @baronfel It says (in german :-) ) "No sources found"

🤦 
hmm, you're right, I admit it. 
Somehow it seems the version is not correct and it is related to other issue.

**Comment by FalkoSp** [comment]
@eriawan That's not it. Did it, and same error.

I'll be offline for some hours. (sleep :-) )

```
fsharptest01>dotnet restore

Willkommen bei .NET 6.0!
---------------------
SDK-Version: 6.0.101

----------------
Ein ASP.NET Core-HTTPS-Entwicklungszertifikat wurde installiert.
Um das Zertifikat als vertrauenswürdig einzustufen, führen Sie "dotnet dev-certs https --trust" aus (nur Windows und macOS).
Weitere Informationen zu HTTPS: https://aka.ms/dotnet-https
----------------
Schreiben Sie Ihre erste App: https://aka.ms/dotnet-hello-world
Neuigkeiten: https://aka.ms/dotnet-whats-new
Dokumentation: https://aka.ms/dotnet-docs
Probleme melden und Quelle in GitHub suchen: https://github.com/dotnet/core
Verwenden Sie "dotnet --help", um verfügbare Befehle anzuzeigen, oder besuchen Sie https://aka.ms/dotnet-cli.
--------------------------------------------------------------------------------------
  Wiederherzustellende Projekte werden ermittelt...
..\fsharptest01\fsharptest01.fsproj : error NU1100: "FSharp.Core (>= 6.0.1)" kann für "net6.0" nicht aufgelöst werden.
  Fehler beim Wiederherstellen von "..\fsharptest01\fsharptest01.fsproj" (in "191 ms").
```

**Comment by FalkoSp** [comment]
Anyway. Thank you for the fast response, both of you! 👍

**Comment by KevinRansom** [comment]
This is almost certainly as @baronfel alluded to an empty nuget.config file meaning there are no sources to serve .nuget packages.  The original poster reports a nuget package resolution error number and message.  The assembly version # for FSharp.Core is 6.0.0.0 and will remain 6.0.0.0 throughout the F# 6.0 release cycle, if that changes it will be a hair on fire moment for me, and I don't have that much hair, so burning any is undesirable :-)


From time to time we see the per user Nuget.config file is emptied out, it's never been narrowed down what causes it, I imagine there is some tool that sometimes empties it out, but I don't know what that tool is, or why it does this.  The fix is to ensure that the nuget.org source is correctly added back into the Nuget.config file.

on my machine here it can be found at:
````
C:\Users\codec\AppData\Roaming\NuGet\Nuget.config
````
please note by default AppData is hidden so you won't see it in explorer, I always configer explorer to show hidden files.

Ensure it contains an entry that looks like this:
````
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
````

If it already has entries please ensure that at least one of them is similar to this:
````
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
````
Thanks

Kevin

**Comment by FalkoSp** [comment]
@KevinRansom 

That was the cause, it seems. The file contained

```
<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

I needed your explanation, lacking knowledge about NuGet.

Thank you!, and all the best for you and your hair :-)
