### ISSUE TITLE
F# Interactive built in main is still net5.0 

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12733]
When running F# Interactive it can't load a .NET 6 DLL. because fsi.exe is still .NET 5.0

@brettfo This was the error I mentioned to you on teams.  Here the script is doing `#r` on a .NET 6 DLL.

This isn't a repro but an example of the kind of problem we get:
```
>\GitHub\dsyme\fsharp\artifacts\bin\fsi\Debug\net5.0\fsi.exe --legacyemit train.fsx --model cnn
System.TypeLoadException: Could not load type 'System.IO.DirectoryInfo' from assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Helpers.Utils.createDir(String dir)
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Stopped due to error
```

**Comment by KevinRansom** [comment]
The shipped SDK always contain fsi and fsc that are built to match the sdk shipped the build of the runtime contained in that specific SDK.  So the released bits will always be correct, however, the repo is always going to lag a bit, especially since previews of dotnet 7. are pretty soon going to be released.

I will chat with Brett and see if there is something interesting we can that makes this less of a problem

**Comment by KevinRansom** [comment]
now builds net6.0: https://github.com/dotnet/fsharp/pull/12769
