### ISSUE TITLE
Implement `abs` for `System.Numerics.Complex` as `Magnitude` property

### ISSUE THREAD

**Issue by mettekou** [dotnet/fsharp#12828]
**Is your feature request related to a problem? Please describe.**

In `FSharp.Core`, [`abs`](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/prim-types.fs#L6004-L6018) is not implemented for `System.Numerics.Complex`.

**Describe the solution you'd like**

Implement it as [the `Magnitude` property](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.complex.magnitude?view=net-6.0), since this is [the mathematical definition of the absolute value of a complex number](https://en.wikipedia.org/wiki/Magnitude_(mathematics)#Complex_numbers).

**Describe alternatives you've considered**

Do not implement `abs` for `System.Numerics.Complex`.

**Comment by Happypig375** [comment]
The underlying problem is that [the `abs` operator only searches for overloads of `Abs` that return the same type as the input](https://github.com/dotnet/fsharp/blob/517e054c9abc3d8676ac52c29f98a57a52caaa4d/src/fsharp/FSharp.Core/prim-types.fs#L6050), but [the `Abs` of `System.Numerics.Complex` returns a `double` given a `System.Numerics.Complex`](https://github.com/dotnet/runtime/blob/f82fe1d83f1a0e22025e186fdc6f4d86de0a83a1/src/libraries/System.Runtime.Numerics/src/System/Numerics/Complex.cs#L273) which does not fit that shape.

**Comment by Happypig375** [comment]
A new special case should be added.

**Comment by charlesroddie** [comment]
This is not the place where current work on numbers is being done. You should contribute to the discussion of `INumber` and related interfaces. https://github.com/dotnet/designs/pull/257 Absolute value are being discussed there. I'd suggest studying the existing comments on this and previous PRs and other languages first. I have been lazy and haven't left feedback on the current draft but will do so.

In the best case this ends up being good enough for F# to interface with in future. In the worst case we completely ignore it and then come back to issues like this.

**Comment by dsyme** [comment]
This is by design as things stand.
