### ISSUE TITLE
Remove or isolate WPF dependence of VS inegration

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12915]
Good for vs for mac

**Comment by cartermp** [comment]
Most of this is in the IDE settings and QuickInfo here https://github.com/dotnet/fsharp/blob/main/vsintegration/src/FSharp.Editor/QuickInfo/WpfNagivableTextRunViewElementFactory.fs

IDE settings is in a separate project and so that's fine.

It might be hard to isolate the quickinfo navigable links. I looked into this a while back because there are some Roslyn things to use. Unfortunately, they ultimately depend on `ISymbol` and it's going to be an enormous amount of work to support that. These links in quickinfo are absoultely wonderful though, would hate to see them go away.

**Comment by vzarytovskii** [comment]
I don't think it's relevant as of now.
