### ISSUE TITLE
Operator precedence for .&& and .||

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#13051]
The following fails to compile:
```fsharp
let (.&&) a b = a && b
1 = 2 .&& 2 > 1
```
with error
```
error FS0001: This expression was expected to have type
    'bool'    
but here has type
    'int'    
```

Based on the spec 

```
In the preceding table, leading . characters are ignored when determining precedence for infix
operators. For example, .* has the same precedence as *. This rule ensures that operators such as
.*, which is frequently used for pointwise-operation on matrices, have the expected precedence. 
```

I would expect `(.&&)` to be equivalent to `(&&)`.

**Comment by dsyme** [comment]
Yes the listed spec is not correct for `.&&` and `.||` specifically   I suppose we should adjust the implementation to match the spec - it is an appropriate consistent rule.  It would be a breaking change bug fix, and should be done under a language version switch because of this.  

@KevinRansom @vzarytovskii Can you double check that this is a reasonable fix to align to the intended spec?

Please open a language suggestion at https://github.com/fsharp/fslang-suggestions, consider it pre-approved, and then if you'd like please proceed to an RFC and PR if you wish

I think the fix would be to allow `ignored_op_char*` before this:

```
 | "&&" { AMP_AMP }

 | "||" { BAR_BAR }
```

However `AMP_AMP` and `BAR_BAR` would need to be extended to carry the actual text of the operator, and some other adjustments may need to be made.

**Comment by dsyme** [comment]
@kevmal  Because this needs to go through RFC and language version switch I will label as "Needs RFC".  We tend to eventually close these issues, once we have a link to the suggestion or RFC

**Comment by vzarytovskii** [comment]
@kevmal as per Don's comment, I'm closing this issue, please feel free to make a proposal over at https://github.com/fsharp/fslang-suggestions/issues
