### ISSUE TITLE
The `|` symbol is required for single-case generic Discriminated Unions

### ISSUE THREAD

**Issue by njlr** [dotnet/fsharp#13198]
This is a single-case DU:

```fsharp
type Foo = Foo
```

However, the `|` symbol is required for single-case generic DUs.

```fsharp
// Does not compile
type Bar<'t> = Bar 

// Compiles
type Bar<'t> = | Bar 
```

From [StackOverflow](https://stackoverflow.com/a/72379569/1256041):

>  I think there are two interesting cases here. The first one is:
> 
> ```
> type Foo = Foo
> ```
> 
> This looks like a self-referential type alias at first, but that's not allowed, so the compiler instead accepts it as a valid DU. This is correct, although subtle, behavior.
> 
> The second interesting case is:
> 
> ```
> type Bar<'t> = Bar   // Error: The type 'Bar<_>' expects 1 type argument(s) but is given 0
> ```
> 
> This also looks like a self-referential type alias at first, but with the wrong number of type parameters. Since the reference is invalid, the compiler issues an error before it has a chance to realize that it's actually looking at a valid DU definition. I think one could reasonably argue that this is a bug in the compiler, and I suggest submitting it as an issue to the F# compiler team. The expected behavior is that this is a valid DU, just like `type Foo = Foo` and `type Bar<'t> = | Bar`.
> 
> Note also that the following is (correctly) not allowed:
> 
> ```fsharp
> type Bar<'t> = Bar<'t>   // Error: This type definition involves an immediate cyclic reference through an abbreviation
> ```

**Expected behavior**

These should be equivalent:

```fsharp
type Bar<'t> = Bar 

type Bar<'t> = | Bar 
```

**Actual behavior**

This does not compile:

```fsharp
type Bar<'t> = Bar 
```

**Known workarounds**

Add the `|`

**Related information**

Ubuntu 20.04

```bash
dotnet --version
6.0.300
```

**Comment by nojaf** [comment]
> This is a single-case DU:

`type Foo = Foo`, that is a type alias actually.
Represented as [TypeAbbrev](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-syntypedefnsimplerepr.html#TypeAbbrev)

**Comment by njlr** [comment]
> `type Foo = Foo`, that is a type alias actually.

Hmm, but what is it a type alias to?

**Comment by nojaf** [comment]
Interestingly enough this does compile to a DU after all.

![image](https://user-images.githubusercontent.com/2621499/170469087-1446d223-7e92-4db4-961b-b88f2e1463ab.png)

I wasn't expecting that.

**Comment by njlr** [comment]
I put `type Foo = Foo` into Fantomas (as I assume you did too!) and it was considered a type alias, so this behavior must happen after parsing?

**Comment by nojaf** [comment]
Yes

**Comment by chkn** [comment]
> Existing cases where the compiler allows the vertical line to be omitted are unfortunate, and while they currently need to be there for backwards compat, they should be warned about eventually by analyzers.

I strongly disagree. This is a matter of coding style.

**Comment by dsyme** [comment]
There is a [special case](https://github.com/dotnet/fsharp/blob/main/src/Compiler/Checking/CheckDeclarations.fs#L4044) in the compiler for

    type A = Id

where `Id` doesn't resolve to any existing known type then this defines a union type.  The case is also extended specifically for

    type A = A

but not, for example, for 

    type A = B
    and B = A

This distinction is not present in the SyntaxTree, but resolved in the CheckDeclarations.fs

This is a historical relic (OCaml compat really). It's will be used fairly frequently to define strongly typed singletons. I'd be quite happy to deprecate it, since `type A = | Id` is much less ambiguous and robust. 

Evidently this can't be used on generic types.  We won't fix this, as this is best considered a historical relic.  

> Existing cases where the compiler allows the vertical line to be omitted are unfortunate

Certainly

```fsharp
type U = U of ...
```

is stylistically valid F# and unambiguously a union.   The only problem is with 
```fsharp
type U = Id
type U = U
```
and so on.
