### ISSUE TITLE
Support caching assembly paths resolved by the DependencyManager

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/fsharp#13236]
`#r nuget` performance can be improved by caching the paths to the resolved assemblies. 

Currently, when `#r nuget` is run, a temporary project is generated and `dotnet restore` is run against it using custom targets that emit the paths to the assemblies, which are then passed to FSI using `#r /path/to/the.dll`. This process does the following:

Currently, when a `#r nuget` is run, the following steps happen:

1. A `.fsproj` file is generated in a temp folder. Custom targets are included that will write the resolved assembly paths to stdout.
2. `dotnet restore` is run on the generated project file (allowing FSI to externalize calculation of the dependency graph.)
3. Packages are downloaded and extracted from the available NuGet sources.
4. DependencyManager returns the list of paths to the assemblies
5. Assembly paths are submitted to FSI using `#r`

Steps 1-4 include a number of performance-intensive operations, including starting a process, running `dotnet restore`, and downloading and extracting packages, but all of this can be avoided on subsequent requests for a given combination of packages at specific versions by caching of the assembly paths.

The proposal is to cache the outcome of steps 1-4 using a hash of the `.fsproj` contents and if this cache exists, proceed directly to step 5. This should shave several seconds off of all subsequent `#r nuget` invocations for a given package. Any change to the contents of the `.fsproj` will result in a different cache hash. This includes changes in the implementation details of the temporary project file's contents.

@KevinRansom

**Comment by nojaf** [comment]
This feels somewhat related, https://github.com/fsharp/fslang-suggestions/issues/1144.
I guess there they propose to go one step further.

**Comment by smoothdeveloper** [comment]
In case this would be useful for improving the nuget extension, the paket one has a caching mechanism, it leans on the the script file location and the paket caching itself (which I don't know much about impl details):

**https://github.com/fsprojects/Paket/blob/80d1c2cd598d6e891a958801533ae7fc6a3a6309/src/FSharp.DependencyManager.Paket/ReferenceLoading.PaketHandler.fs#L110-L113**

I haven't played with comparing perf of the nuget one to the paket one though.

**Comment by smoothdeveloper** [comment]
Also the "one step further the further step": https://github.com/dotnet/fsharp/discussions/8044

Everyone seems to want even faster F# nowadays :)

**Comment by KevinRansom** [comment]
@smoothdeveloper , the F# compiler can already compile scripts.   Why is that insufficient?

**Comment by auduchinok** [comment]
Maybe we could have an assertion that dependency manager isn't touched unless needed for reference directives?

**Comment by KevinRansom** [comment]
@definitely not going to cache binaries --- the nuget cache does a perfectly decent job of that.

Are you looking for a mechanism such that, when a script is compiled with fsc it copies the referenced assembly to the build directory and referenced native assemblies to the output\runtime directory?  If so, I think that would be possible to add, however, the caching mechanism would certainly be the wrong place.

If so add an issue, I think I wouldn't mind adding the feature, it seems like a pretty good idea, especially if it was supported by publish, because then we could imagine a dotnet script publishing scenario, which would be pretty fabulous when combined with dotnet interactive.

**Comment by KevinRansom** [comment]
In fact, I'm gonna chat with @jonsequitur see if he could use that.

**Comment by smoothdeveloper** [comment]
> Are you looking for a mechanism such that, when a script is compiled with fsc it copies the referenced assembly to the build directory and referenced native assemblies to the output\runtime directory? 

@KevinRansom I would love that invoking fsc on a .fsx puts the .exe and all the runtime dependencies into the directory of the output .exe, that would include the runtime dependencies pulled out of the DependencyManager, the raw `#r "Assembly"`, the others `#load "others.fsx"`, and maybe others that get implicitly embedded.

Otherwise, compiling an .exe out of a .fsx still leaves a lot of work to figure this out manually, making fsc not so useful with .fsx files.

I'm not able to understand implication of making this work, and not taking it for granted that it would be something that fsc supports.
