### ISSUE TITLE
Compiler does not infer string type for nameof pattern

### ISSUE THREAD

**Issue by niesmo** [dotnet/fsharp#13377]
When using `nameof` in a pattern match, I'd expect the compiler to infer the argument type as `string` since `nameof` returns a `string`. However, the argument is treated as generic and generates invalid IL.

**Repro steps**
```fsharp
// Expected:
//   FS0001: This expression was expected to have type 'int' but here has type 'string'
// Actual:
//   No compile error; InvalidProgramException at runtime.
match 3 with
| nameof int -> true
| _ -> false
```
```fsharp
// Expected inferred type:
//   val f : x:string -> bool
// Actual inferred type:
//   val f : x:'a -> bool
let f x = match x with nameof x -> true | _ -> false
```

[According to the RFC for the nameof pattern feature](https://github.com/fsharp/fslang-design/blob/bc295aef9a20ef9aa034bcec2955160342b4b284/FSharp-5.0/FS-1085-nameof-pattern.md?plain=1#L59), the `nameof expr` should be "equivalent to a literal string pattern" which is not being respected.

**Expected behavior**

Expect the compiler to infer argument type as `string` when `nameof` is used in a pattern match.

**Actual behavior**

Compiler infers argument type as generic argument when `nameof` is used in a pattern match.

**Known workarounds**

Explicit type annotation.
```fsharp
let f (x:string) = match x with nameof x -> true | _ -> false
```

**Comment by NinoFloris** [comment]
@dsyme this is indeed producing invalid IL, hit it today as well.

**Comment by dsyme** [comment]
Thanks, should be a simple fix

**Comment by dsyme** [comment]
@vzarytovskii this is a good first issue, happy to guide the fix

**Comment by edgarfgp** [comment]
I have also hit this . Happy to help fixing this with a little bit of guidance as I’m still new to the compiler . cc @dsyme

**Comment by ntovas** [comment]
I looked a bit into this  and to me it seems that the issue to be in `match` than in `nameof` implementation. 
I would like some guidance to make a fix for this, @vzarytovskii can you help?

**Comment by vzarytovskii** [comment]
> I looked a bit into this  and to me it seems that the issue to be in `match` than in `nameof` implementation. 
> I would like some guidance to make a fix for this, @vzarytovskii can you help?

Hey, @ntovas, I'm on vacation currently, without acces to my phone unfortunately :(

Perhaps someone from the team can chime in, and help you looking into it? @dotnet/fsharp-team-msft ping!

**Comment by T-Gro** [comment]
@ntovas :

This is the approach I would take:
Add a failing test into the Component.Tests suite, into \tests\FSharp.Compiler.**ComponentTests**\Language\**NameofTests**.fs .

Before starting it, sprinkle breakpoints around code in the TypeChecking state, so that you can step the execution and investigate the available parameters.

One of the places that seems to be related is \src\Compiler\**Checking**\**CheckPatterns**.fs . I would try to put a few breakpoints into that and trace it - e.g. to verify that the nameof is infered to be a constant expression, and also explicitely marked as constant expression of string type.

All nameof-related functionality is a behind a feature flag, which can also give you an idea at which places the compiler interacts with this feature:
```g.langVersion.SupportsFeature LanguageFeature.NameOf ```

**Comment by vzarytovskii** [comment]
I would also add that `nameof` is not your typical function, and has a special treatment in the compiler. That's why it behaves differently to all other functions.

**Comment by ntovas** [comment]
Hey @T-Gro ,
Maybe you can check the linked PR?

**Comment by T-Gro** [comment]
On it :)
