### ISSUE TITLE
op_Implicit incompatibility with arithmetic

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#13421]
This seems to be a bug:

```fsharp
[<RequireQualifiedAccess>]
type Number =
    | Int of int
    static member (+)(x:Number, y:int) =
        match x with
        | Number.Int i -> Number.Int(i + y)
    static member op_Implicit(z:int) = Number.Int z
    static member Ignore(_:Number) = ()

let x = Number.Ignore(1 + 1) // Squiggle on the second 1 with FS0001: the type Number does not match the type int
let x' = Number.Ignore(1 + 1: int) // OK

let addOne(i:int) = i + 1
let y = Number.Ignore(addOne 0) // this is OK
```

1+1 = 2 unambiguously, so the compiler should process 1+1 and know that the result is an int.
It should then see that there are no signatures of `Number.Ignore` matching `int`, and look for `op_Implicits` and find that there is one.
So `Number.Ignore(1 + 1)` should work.

**Comment by dsyme** [comment]
This is by design. As noted on the RFC the last-chance invocations of op_Implicit has many interactions with type inference - especially anything involving srtp constraint solving like "+". We aren't realistically going to try to force more eager solving of constraints nor incorporate op_Implicit invocations into the solving of srtp constraints.
