### ISSUE TITLE
Review component governance report for F# and update packages if necessary

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#13453]

**Comment by brettfo** [comment]
Most of the component governance issues were due to stale build definitions; I removed those from being tracked, now the only things remaining are:

1. Newtonsoft.Json 9.0.1 from the test SDK which will be internally handled by arcade
2. Dotnet.ProjInfo missing licence information

https://dnceng.visualstudio.com/public/_componentGovernance/123256?_a=alerts&typeId=11762278&alerts-view-option=active

**Comment by brettfo** [comment]
There are also some component governance failures being reported for the dotnet/fsharp repo, `master` branch in the internal devdiv/DevDiv instance, but that's not a repo being used for anything: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/123332?_a=alerts&typeId=934473&alerts-view-option=active

Not sure if it's possible to delete or archive that repo.

**Comment by vzarytovskii** [comment]
Dismissed most of them, last one depends on arcade, gotta close this one.
