### ISSUE TITLE
Incorrect serialization using fsi and Newtonsoft on dotnet 6.0.3xx

### ISSUE THREAD

**Issue by JonCanning** [dotnet/fsharp#13493]
Install dotnet 6.0.301 on Linux. I have tried Ubuntu and Debian on WSL.

`sudo apt install dotnet-sdk-6.0`

Run this script using `dotnet fsi`

```
#r "nuget:Newtonsoft.Json"

open Newtonsoft.Json

JsonConvert.SerializeObject {| x = 1 |}
|> printfn "%s"
```

or
```
type R = { x: int }
JsonConvert.SerializeObject { x = 1 } |> printfn "%s"
```

In either case output is

`{"x@":1,"x":1}`

Install 6.0.203

`sudo apt install dotnet-sdk-6.0=6.0.203-1`

output is

`{"x":1}`

Serialization is correct on Windows, and when using a regular class, only records in scripts are affected

### Workaround

Use `dotnet fsi --multiemit-`

**Comment by dsyme** [comment]
The problem is related to this line: https://github.com/dotnet/fsharp/blob/9df7080dd281d9d2b20f704bd8ad3b8b4aa5875a/src/Compiler/CodeGen/IlxGen.fs#L2079 which is active for multi-assembly emit.

In principle it should not be necessary to make the IL fields public when doing multi-assembly emit - making the IL properties alone public should really be sufficient.  However I think access is "optimized" to directly access the IL fields in what IlxGen.fs thinks is an intra-assembly access.  

There's a related line we need to check here: https://github.com/dotnet/fsharp/blob/main/src/Compiler/CodeGen/IlxGen.fs#L10675

**Comment by dsyme** [comment]
I think the best fix here for multi-emit is as follows

1. adjust IlxGen to always emit `ILMemberAccess.Assembly` for these backing record fields, reporting back when this has been done for an assembly fragment
2. adjust the Multi-emit code in `fsi.fs` to always emit `InternalVisibleTo` attributes for any such assembly fragments, that is for any assembly fragments that contain record definitions.
