### ISSUE TITLE
CurrentCulture is not preserved between submissions of desktop fsi

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#13701]
dotnet fsi appears to, but that may just be an accident.

Repro:
Start fsi
paste in this script
````
open System
open System.Globalization

System.Globalization.CultureInfo.CurrentCulture <- System.Globalization.CultureInfo.GetCultureInfo("nl-NL")

System.Console.WriteLine(System.Globalization.CultureInfo.CurrentCulture);;
System.Console.WriteLine(System.Globalization.CultureInfo.CurrentCulture);;
````

observe that currentculture is different in both submissions.
![image](https://user-images.githubusercontent.com/5175830/184854950-766c296e-e76d-4d24-ba20-17c72b0bf7ba.png)

dotnet fsi being right
![image](https://user-images.githubusercontent.com/5175830/184855079-73154387-4305-4472-9bad-d7687e0b252c.png)

**Comment by dsyme** [comment]
@KevinRansom This only happens when "--gui" event loop support is enabled, as in .NET Framework `fsi` but not in `dotnet fsi`.  I'm not sure it should be fixed.

I guess we should consider whether we want some kind of event loop support for `dotnet fsi`.  We haven't exactly documented this difference.

**Comment by KevinRansom** [comment]
There is no need to fix this.  It is how it has always worked.
