### ISSUE TITLE
Inconsistent type incompatible error range

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13876]
```fsharp
let f (i: System.IDisposable) = ()

let o = obj()
o |> f
f o
```

The highlighted range is different between cases when using a prefix application and a pipe operator: in one case the argument is highlighted and in another cases it's the function:

<img width="320" alt="Screenshot 2022-09-12 at 11 30 47" src="https://user-images.githubusercontent.com/3923587/189620584-aad31d76-9905-4810-a287-1127e5f2bf9f.png">

Maybe it'd be better (and feasible?) to highlight the same thing in both cases?

**Comment by charlesroddie** [comment]
I don't see a bug here. In the later case `|>` is the function, and it highlights the first input (the one to the right) which causes the types to be unreconcilable.

**Comment by auduchinok** [comment]
@charlesroddie The error is the same in both cases and is specifically about `obj` argument being incompatible with `IDisposable`, so it'd probably be nice to highlight the argument.

**Comment by charlesroddie** [comment]
It makes sense that the incompatibility is the same, but in the first case the first incompatible argument (of `|>`) is `f`, and in the second case the first incompatible argument (of `f`) is `o`.

In order to see `o` as "the argument" (presumably of `f`) in `o |> f` you would need to see it as if it were the implementation, and then match the implementation onto the written form. Seems like a big and complex language suggestion involving processing of inline error messages differently from non-inlines.

If we take operators out of it, are you suggesting the following?

```fsharp
let apply<'a>(x:'a, y:'a -> unit) = ()
let x = obj()
let y(_:IDisposable) = ()
apply(x, y) // This puts a squiggle on y. Are you suggesting that if `apply` is defined with `let inline`, that the squiggle should move to x?
```

**Comment by charlesroddie** [comment]
More practically, if I have a function `f` and I am sure I want to use it, then I will probably write `f(x)`, and if they are incompatible then `x` is wrong. If I know I have an `x` and I want to transform it, then I will probably write `x |> f`, and if they are incompatible then `f` is wrong. The propagation of type information from left to right leads to this approach, which then works with the current squiggles.

**Comment by dsyme** [comment]
This is not a bug - I agree with @charlesroddie's analysis here
