### ISSUE TITLE
Obsolete Attribute on AutoOpen Modules

### ISSUE THREAD

**Issue by matthid** [dotnet/fsharp#1391]
When you create an `[<AutoOpen>]` Module and later decide to mark it as obsolete, most of the time no warning will be triggered on the consumer side.
#### Repro steps

`lib.fs`:

``` fsharp
[<System.Obsolete("This is obsolete")>]
[<AutoOpen>]
module MyNamespace.MyModule

let testFun () = printfn "test"
```

`script.fsx`

``` fsharp
#r "lib.dll"

open MyNamespace

testFun ()
```
1. `fsc -a lib.fs`
2. `fsi test.fsx`
#### Expected behavior

```
script.fsx(3,6): warning FS0044: This construct is deprecated. This is obsolete
test
```
#### Actual behavior

```
test
```
#### Known workarounds

Mark all module members as obsolete...
#### Related information
- Operating system: Windows 10 x64
- Visual Studio 2015 Update 3
- Severity: Annoyance

IMHO the F# compiler should only warn when the obsolete module is actually used in the current context. It would even be fine when fsc would warn on the the first instance (as `fsc` is a single pass compiler).
Giving no warning at all feels like a bug...

**Comment by dsyme** [comment]
I think we should treat this is a suggestion rather than a bug.  I understand that it makes sense to give some kind of warning here, but the current approach is that warnings for Obsolete get given at the textual use of an obsoleted identifier reference.  Here there is no such reference.  So the workaround is currently the right way to deal with marking AutoOpen modules obsolete.

**Comment by edgarfgp** [comment]
I think this is fixed. See the liked test that validates this cc @vzarytovskii 
https://github.com/dotnet/fsharp/blob/589d350ac2831cb6d52049eeb4118a1af35bf9e1/tests/FSharp.Compiler.ComponentTests/Language/ObsoleteAttributeCheckingTests.fs#L705

**Comment by vzarytovskii** [comment]
Oh, nice, thanks, going to close it for now.
