### ISSUE TITLE
Inconsistent error message between .NET interactive notebooks and VS / FSI session

### ISSUE THREAD

**Issue by bmitc** [dotnet/fsharp#13921]
I'm having a lot of confusing issues with type inference when using type aliases with sequences. The behavior and errors reported differ between Visual Studio, .NET Interactive notebooks, and FSI.

**Repro steps**

[SequentialLogic.zip](https://github.com/dotnet/fsharp/files/9595208/SequentialLogic.zip)

1. See the attached `SequentialLogic.ipynb` notebook and note the error of
    > Error: input.fsx (9,5)-(9,9) typecheck error Value restriction. The value 'Not'' has been inferred to have generic type
    val Not': (Signal -> Signal)    
Either make the arguments to 'Not'' explicit or, if you do not intend for it to be generic, add a type annotation.

    The error does not make any sense to me because `Signal -> Signal` is exactly the intended type of `Not'` and is not generic.

2. See the attached `SequentialLogic` solution and open `Signal.fs` in the `CPUSimulator` project in Visual Studio 2022. Note that `Not'`, `And'`, and so on have no error but `Xor'` reports the error

    ![image](https://user-images.githubusercontent.com/65685447/190926846-5ccea771-ec33-49b4-b245-ecb19ca1bef2.png)

    I suppose this error may make a little sense to me given that `Signal` is a type alias of `seq<bit>` and that `seq` can have subtypes (such as `list` or `array`, is that correct?). But what doesn't make sense is that `Not'`, `And'`, and so on are defined identically but do not report the same error. Nor do they report the same error as the .NET Interactive notebook.

    Note: I just noticed that if I delete the code *after* `Xor'` in the project, the errors show up for all the `<operator>'` definitions. This is strange to me.

3. Enter the code into `FSI`, and you'll get yet another distinct error case for `Not'` as opposed to the .NET Interactive error and the Visual Studio non-error for `Not'`.

    ```fsharp
    > let Not' = liftToSignal1 Not;;

      let Not' = liftToSignal1 Not;;
      ----^^^^

    stdin(52,5): error FS0030: Value restriction. The value 'Not'' has been inferred to have generic type
        val Not': ('_a -> Signal) when '_a :> Signal
    Either make the arguments to 'Not'' explicit or, if you do not intend for it to be generic, add a type annotation.
    ```

**Expected behavior**

I would say the expected behavior is:

* Consistently reported errors
* Errors that make sense (in the case of the .NET Interactive error)
* Errors that do not adjust when code defined *after* the problematic code is removed
* I expected the use of the "lift" functions to be straightforward to avoid having to explicitly define parameters and/or provide additional type annotations. Note that the "lift" functions themselves are explicitly typed.

**Actual behavior**

Several inconsistent errors as described above.

**Known workarounds**

Either explicitly type all functions and/or provide parameters. For example, if I define `Not'` in the .NET Interactive notebook as

```fsharp
let Not' input = liftToSignal1 Not input
```

the error goes away. This doesn't quite make sense to me given `liftToSignal1` is explicitly type annotated, and I don't type annotate `input` here. Defining `Not'` as

```fsharp
let Not' : Signal -> Signal = liftToSignal1 Not
```

also gets rid of the confusing errors.

**Related information**

Provide any related information (optional):

* Operating system: Windows 11
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 6
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio Community 2022, Visual Studio Code with .NET Interactive Notebooks extension, and `dotnet fsi`

**Comment by abonie** [comment]
Hi @bmitc, what you encountered here is F#'s [value restriction](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/automatic-generalization#value-restriction) being conservative in what can be generalized to polymorphic type (which is how F# deals with having both mutability and polymorphism) combined with subtyping (as [seq<'T> is essentially IEnumerable<'T>](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seq-1.html)) which makes it more confusing, but it is still the expected behavior I believe (except for the error message in the notebook).

Regarding what behavior you expected:
> - Consistently reported error
> - Errors that make sense (in the case of the .NET Interactive error)

It seems to me that the error message in notebook might be a bug in .net interactive. And I don't think it has to do with type aliases, as this:
```fsi
let y = fun (x : seq<bool>) -> x
id y
```
also results in similarly incomplete error message:
```
Error: input.fsx (2,1)-(2,5) typecheck error Value restriction. The value 'it' has been inferred to have generic type
    val it: (seq<bool> -> seq<bool>)    
Either make the arguments to 'it' explicit or, if you do not intend for it to be generic, add a type annotation.
```

@jonsequitur ^

Otherwise, errors are reported consistently between VS and FSI.

___

> - I expected the use of the "lift" functions to be straightforward to avoid having to explicitly define parameters and/or provide additional type annotations. Note that the "lift" functions themselves are explicitly typed.

That's that value restriction in action. Even this simple code below will result in similar error in fsi
```fsi
> let f = id id;;
  let f = id id;;
  ----^

stdin(101,5): error FS0030: Value restriction. The value 'f' has been inferred to have generic type
    val f: ('_a -> '_a)
Either make the arguments to 'f' explicit or, if you do not intend for it to be generic, add a type annotation.
```
but this works fine:
```fsi
> let f x = id id x;;
val f: x: 'a -> 'a
```
___
> - Errors that do not adjust when code defined after the problematic code is removed

I suspect what happened there was that the removed code had information relevant for type checking. Going back to the previous example, note that this:
```fsi
> module F =
-   let f = id id
-   let x = f 1;;
module F =
  val f: (int -> int)
  val x: int = 1
```
is OK, but f has type `int -> int` and not `` `a -> `a``. If you remove let binding for x which uses f with a concrete type, you will get the same value restriction error from before.

**Comment by abonie** [comment]
I spoke briefly with @jonsequitur and it seems that the bug is on FSI side rather than .NET interactive. I was able to repro when calling FSI API in a similar way that .NET interactive calls it
<img width="404" alt="image" src="https://user-images.githubusercontent.com/20281641/192498610-d8cb59ae-fd09-47f4-a0d5-d20cdede295c.png">
