### ISSUE TITLE
Missing MEF export of IFSharpFindDefinitionService in VS

### ISSUE THREAD

**Issue by genlu** [dotnet/fsharp#14053]
I'm seeing a MEF error in VS main build.

```
 Microsoft.CodeAnalysis.ExternalAccess.FSharp.Internal.GoToDefinition.FSharpFindDefinitionService.ctor(service): expected exactly 1 export matching constraints:    Contract name: Microsoft.CodeAnalysis.ExternalAccess.FSharp.GoToDefinition.IFSharpFindDefinitionService
    TypeIdentityName: Microsoft.CodeAnalysis.ExternalAccess.FSharp.GoToDefinition.IFSharpFindDefinitionService
but found 0.
   part definition Microsoft.CodeAnalysis.ExternalAccess.FSharp.Internal.GoToDefinition.FSharpFindDefinitionService
```

And a quick search shows that this type is not implemented in F#. 

[IFSharpFindDefinitionService - grep.app](https://grep.app/search?q=IFSharpFindDefinitionService&filter[repo][0]=dotnet/fsharp)

**Comment by T-Gro** [comment]
We do implement the `[<Export(typeof<IFSharp**GoTo**DefinitionService>)>]`, that covers the F12 functionality.
What VS action is triggered by IFSharp**Find**DefinitionService, is this something different?
I see that the return types are different, I am just thinking on how to test this with F#.

**Comment by vzarytovskii** [comment]
> We do implement the `[<Export(typeof<IFSharp**GoTo**DefinitionService>)>]`, that covers the F12 functionality.
> What VS action is triggered by IFSharp**Find**DefinitionService, is this something different?
> I see that the return types are different, I am just thinking on how to test this with F#.

@T-Gro this is related Roslyn issue: https://github.com/dotnet/roslyn/issues/50391
Just a matter of implementing new service in 17.5 branch (and getting rid of old one, or rather refactor old one to the new one).

It's not super urgent since old service is still around.

If you'd like, I can take care of it once I'm back next week, I know exactly what to do and how to test it.

If you'd like to work on it, go for it, just drop it in current milestone.
