### ISSUE TITLE
Improve error reporting: using EntryPoint attribute in an F# script

### ISSUE THREAD

**Issue by anton-pt** [dotnet/fsharp#1431]
## What

Running the code:

``` fsharp
[<EntryPoint>]
let main argv =
    printfn "Hello, world!"   
    0
```

in FSI produces the output
`val main : argv:string [] -> int`
but doesn't actually invoke the function.
## Why

Some beginners may be unsure about how F# scripts and FSI work and may run some code from an application which has an `EntryPoint` into FSI. This happened recently to a former colleague.
## How

Using the `EntryPoint` attribute in FSI should produce a compiler warning indicating that it won't be invoked automatically.

**Comment by KevinRansom** [comment]
Agreed.

**Comment by isaacabraham** [comment]
@anton-pt can you suggest an error message that should be displayed - we should be able to come up with one easily, and then this can be marked as up for grabs.

**Comment by anton-pt** [comment]
How about something like this?

Warning: defined function [f] marked as EntryPoint was not invoked. Execute [f argv] in order to invoke [f] with the appropriate string array of command line arguments.

**Comment by bisen2** [comment]
It seems to me that FSI should implicitly run a method marked with the EntryPoint attribute. For example:
```fs
[<EntryPoint>]
let main argv =
    printfn "Hello, World!"
    0
```
should be equivalent to
```fs
let main argv =
    printfn "Hello, World!"
    0

main fsi.CommandLineArgs
```

**Comment by vzarytovskii** [comment]
We already have an implicit entry point created in scripts, adding some different behaviour, based on attribute would be confusing and, probably, a breaking change, for example consider the following code:

```fsharp
[<EntryPoint>]
let main argv =
    printfn "Hello, World!"
    0

#if !INTERACTIVE
main fsi.CommandLineArgs
#endif
```
`main` will be executed twice, since second one is going to be generated by compiler.

I think, a warning should be produced instead (as it was suggested originally).

**Comment by dsyme** [comment]
> I think, a warning should be produced instead (as it was suggested originally).

Yes, it makes sense

**Comment by KathleenDollard** [comment]
If we're just looking for text here, working from @anton-pt 's suggestion: 

`Function with [<EntryPoint>] are not invoked in FSI. [f] was not invoked. Execute [f <args>] in order to invoke [f] with the appropriate string array of command line arguments.`

I assume the [f] will be replaced with the fuction name. I think "argv" is confusing if the user needs to type args there, so the <args> will hopefully inspire the programmer to type real values there.
