### ISSUE TITLE
No error about tuple pattern structness mismatch

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#14473]
Consider the following match expression:

```fsharp
match struct (true, true) with
| true, true -> ()
```

No error is produced for reference tuple pattern when matching a struct tuple value:

<img width="272" alt="Screenshot 2022-12-15 at 13 20 22" src="https://user-images.githubusercontent.com/3923587/207857985-d067be0d-04c6-40c8-ab0f-4144081e82e5.png">

It does work correctly the other way, though:

```fsharp
match true, true with
| struct (true, true) -> ()
```

<img width="493" alt="Screenshot 2022-12-15 at 13 21 59" src="https://user-images.githubusercontent.com/3923587/207858184-2e50adb1-65a0-4db1-afd6-27331992513e.png">

**Comment by T-Gro** [comment]
If I set things up correctly and understood it correctly, it works as naively expected - it attempts to be a relief/help for matching struct tuples.
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgFxCgFcA7NAExAGoAfCABxjIAIBlAT1wJgFsAsACgMMAqwSTWACgIlGARhA9SYAtOAQIGVgCpWm7QEojMuYwBMIQzv02jAXlbDWr1nwCGBMAAtW5hVYAdwBLAj83Fzc6M1IYNH840zgAPlYUC1co1xiVEjVZOISCJNZU9IsM5yE3VhiENE5gnxYZBs5TJ3NM8oy+i2zWAHoh+qkglrZJBFYu+R606SNBmIB9MrT+/sHhUXEANw8MAEFsXigAWS9fELIAc1mJKWk8gpKSePeYE1iPtGwjrhvsJGFBbgRsGwAEQAUhCUNYhxOZxgl2uPlud2EQA= 


It makes sense to allow for an easier decomposition, otherwise this would be a common mistake to make.

But then of course, there is a point about consistency:

 If this should be a feature to make deconstruction of struct tuples easier, it should work for  let a,b = struct(1,2,) deconstruction.
If this is supported for pattern matching, it should be detected as a duplicate match ( (true,true) vs struct(true,true) both work, but are not detected as duplicated when used at the same time)

**Comment by T-Gro** [comment]
This is by design to make this construct easier, to avoid writing "struct" 

@auduchinok : Do you see any things that should be changed here?
We can revisit the struct tuple RFC.

**Comment by auduchinok** [comment]
@T-Gro Apparently, there're some other related inconsistencies. For example, extra parens are required in some cases, otherwise this auto-struct conversion doesn't happen:

```fsharp
let f (a: struct (int * int)) =
    a |> (fun ((x, y)) -> x + y)
```

The parens aren't required by syntax:
<img width="270" alt="Screenshot 2023-10-09 at 13 48 54" src="https://github.com/dotnet/fsharp/assets/3923587/44f8e642-8ba8-407a-9aaf-ce31908e222d">

An error is produced if parens are removed:
<img width="539" alt="Screenshot 2023-10-09 at 13 50 11" src="https://github.com/dotnet/fsharp/assets/3923587/79e5f681-01d5-4e5a-9f81-166ef6515845">

This is quite unfortunate, as parens analysis shouldn't know anything about expected types.

I think we can lift this extra parens requirement, as it's not a part of the initial feature design and looks like a bug to me. @vzarytovskii What do you think?

**Comment by auduchinok** [comment]
OK, this is already covered in https://github.com/fsharp/fslang-suggestions/issues/988.
