### ISSUE TITLE
Undercore is used for constructor type name

### ISSUE THREAD

**Issue by xp44mm** [dotnet/fsharp#14514]
**Is your feature request related to a problem? Please describe.**

I want to do this:

```fsharp
let x = ([]:int _)
let x = ([]:_<int>)
```

**Describe the solution you'd like**

Allow Undercore(`_`) as constructor type name.

**Describe alternatives you've considered**

an alternative solution:

```fsharp
let x = ([]:int list)
let x = ([]:list<int>)
```

**Additional context**

related fsharp compiler error: #FS0010

**Comment by T-Gro** [comment]
Can you give a meaningful self-contained use case please?

Definitely feels more like a language suggestions (with benefits unclear to me **so far**), but maybe I am missing a scenario where this hurts today already and why the FS0010 is being linked?

Also, if I got the issue correctly, it is basically asking for an alternative language feature set in order to express:
`let x = List.empty<int>`

Am I right?
(i.e. you do not want to type just "[]", because you want to be certain it will get inferred as a list of integers)

**Comment by vzarytovskii** [comment]
> Can you give a meaningful self-contained use case please?
> 
> Definitely feels more like a language suggestions (with benefits unclear to me **so far**), but maybe I am missing a scenario where this hurts today already and why the FS0010 is being linked?
> 
> Also, if I got the issue correctly, it is basically asking for an alternative language feature set in order to express: `let x = List.empty<int>`
> 
> Am I right? (i.e. you do not want to type just "[]", because you want to be certain it will get inferred as a list of integers)

Yep, it is a language suggestion, please create an issue in https://github.com/fsharp/fslang-suggestions/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by xp44mm** [comment]
Although very rare, there are some uses：

```fsharp
type T<'a> = 
    {
        ls: 'a list
    }

    static member zero =
        {
            ls = ([]:'a list)
        }

let rec loop t =
    if t = T<'a>.zero then
        ()
    else loop t

```
