### ISSUE TITLE
BenchmarkDotNet complains about non-optimized FSharp.Test.Utilities

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#14913]
After building the repo clean:
```
git clean -xdf -e .vs
build -c Release
```

I'm trying to run some benchmarks from the `tests\benchmarks\FCSBenchmarks` folder.

Trying to run for example
`dotnet run -c Release --filter  *ParseProjectWithChangingMiddleFile*`

gives:

```
// Validating benchmarks:
Assembly FSharp.Compiler.Benchmarks which defines benchmarks references non-optimized FSharp.Test.Utilities
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.WithOptions(ConfigOptions.DisableOptimizationsValidator)'.
```

I have no idea what's going on here.
As a workaround I can disable that validator.

**Comment by 0101** [comment]
The problem is, we use `FSharp.Test.Utilities` in benchmarks because it contains the `ProjectGeneration` framework, which is needed in both tests and benchmarks. And in `FSharp.Test.Utilites.fsproj` we have
https://github.com/dotnet/fsharp/blob/bae1ccd3a39eb761cb2ee26a8a87ee1390d4a71e/tests/FSharp.Test.Utilities/FSharp.Test.Utilities.fsproj#L11

Which I assume is needed/preferable for tests. But BDN doesn't like it. 

I don't know what's the best way to deal with the situation. So far when running benchmarks I've always just locally edited `FSharp.Test.Utilities.fsproj` and set
```xml
<Optimize>true</Optimize>
<Tailcalls>true</Tailcalls>
```

But it would be nice to somehow do this automatically. And also to figure out if it actually matters and we can instead just disable the validator.
