### ISSUE TITLE
Duplicated Find All References results

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#15191]
![image](https://user-images.githubusercontent.com/217092/236450537-0b3a8b5b-a5e6-43fe-aa0a-7d047b8b655f.png)

**Repro steps**

Find all references on this or other instance methods: https://github.com/dotnet/fsharp/blob/1d819b92435c955a50b0cf5d97104e6ad431fe1f/tests/FSharp.Test.Utilities/ProjectGeneration.fs#L108

**Expected behavior**

Results are shown once.

**Actual behavior**

Results are shown twice.

**Related information**

May be related to #3556

**Comment by sudqijawabreh** [comment]
I did some investigation. I was able to reproduce the issue by creating an fsharp project that targets both .netframework 4.7.2 and .net7.

 I wasn't able to reproduce the issue in a unit test inside  `fsharp\tests\FSharp.Compiler.ComponentTests\FSharpChecker\FindReferences.fs`.
 Or inside `fsharp\vsintegration\tests\FSharp.Editor.Tests\FindReferencesTests.fs`.
 
Which leads me to think the issue is in visual studio since as it was reported before for C# in this [link](https://developercommunity.visualstudio.com/t/search-feature-combine-results-for-multiple-target/1290760).
 When I tried it locally with C# it shows that the references for both .net 4.2.7 and .net6 so it seems to be fixed for C# but not for F#.
![image](https://github.com/dotnet/fsharp/assets/8886372/a9fea56e-4387-48ea-8c8a-97b5a3ee1a63)
But for F# project it shows each type separately which looks like as just duplicate references.
![image](https://github.com/dotnet/fsharp/assets/8886372/702d5ac2-b418-4ab3-86de-ce7875280c20)
