### ISSUE TITLE
Some user defined symbols started to get `DebuggerNonUserCode`

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#15298]
Starting with .NET 7, some user defined functions get `DebuggerNonUserCode` attribute, which is not expected. Consider `let` functions in types:

```fsharp
type T() =
    let f x = x + 1
```

It gets the attribute despite being a user defined method:
<img width="782" alt="Screenshot 2023-06-01 at 17 41 23" src="https://github.com/dotnet/fsharp/assets/3923587/5821f4e4-9fe9-4edc-a6e3-283105fbf14a">

This may affect analysis in tools like debugger and it actually breaks a part of analysis for us.
Can this change be reverted for user-defined compiled methods, please?

This issue has been extracted from https://github.com/dotnet/fsharp/issues/14858#issuecomment-1572298339.

**Comment by KevinRansom** [comment]
@auduchinok , I will fix this.

**Comment by KevinRansom** [comment]
@auduchinok -- what build of the compiler service do you see this with ...

It appears to be fixed in VS2022 - 17.6.2

![image](https://github.com/dotnet/fsharp/assets/5175830/a1e7a194-309a-41d4-a248-a91372841463)

I believe it was fixed with this pr:  https://github.com/dotnet/fsharp/pull/14682 on February 6th

**Comment by auduchinok** [comment]
@KevinRansom Thank you for checking it! I turned out I've tested it on 7.0.203 which did not contain the fix indeed.
