### ISSUE TITLE
dotnet 8 fsharp tuple reflection with 6 items throw exception when running in wasm release build

### ISSUE THREAD

**Issue by albertwoo** [dotnet/fsharp#16849]
Please provide a succinct description of the issue.

When I use FSharpValue.MakeTuple for **6** items it will throw exception when publish to wasm in release mode. But running correctly in debug mode and for 5 or 7 items it always works fine.

```fsharp
Reflection.FSharpValue.MakeTuple([| for i in 1..6 -> i |], typeof<int * int * int * int * int * int>)
```

```text
System.FormatException: Format_IndexOutOfRange at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider , String , ReadOnlySpan`1 ) at System.String.FormatHelper(IFormatProvider , String , ReadOnlySpan`1 ) at System.String.Format(String , Object[] ) at Microsoft.FSharp.Reflection.Impl.getTupleConstructorMethod(Type typ) at Microsoft.FSharp.Reflection.Impl.getTupleCtor(Type typ) at Microsoft.FSharp.Reflection.Impl.getTupleConstructor(Type typ) at Microsoft.FSharp.Reflection.FSharpValue.MakeTuple(Object[] tupleElements, Type tupleType) at <StartupCode$FSharpTupleReflectionIssueInWasm>.$Startup.main@()
```

Provide the steps required to reproduce the problem:

Reproduce repo: https://github.com/albertwoo/FSharpTupleReflectionIssueInWasm

**Expected behavior**

It should works for any number of items

**Actual behavior**

Not work for 6 items, but ok for 5 or 7 items.

**Known workarounds**

None

**Comment by vzarytovskii** [comment]
I don't known how wasm compiler works, but if it works in normal release IL build, then it's something which happens later, either it's getting trimmed or compiled incorrectly.

**Comment by vzarytovskii** [comment]
Also, exception is interesting - Format_IndexOutOfRange, so it's not a reflection issue, but a formatting issue

**Comment by vzarytovskii** [comment]
Exception is thrown because it seems there's no constructor for tuple of 6 (it probably got trimmed), 5 and 7 weren't trimmed since they might be used in other libraries. 
It's easy to prove, if you modify your `msgForTupleWith6Items` function:
```fsharp
let msgForTupleWith6Items =
        try
            let x = Tuple<int, int, int, int, int, int>(1,2,3,4,5,6)
            printfn "%A" x
            Reflection.FSharpValue.MakeTuple([| for i in 1..6 -> i |], typeof<int * int * int * int * int * int>) |> sprintf "%A"
        with ex ->
            sprintf "%A" ex
```
You will now see that everything works, when you used tuple explicitly.

This is what emitted in IL (roughly) for the `Reflection.FSharpValue.MakeTuple([| for i in 1..6 -> i |], typeof<int * int * int * int * int * int>) |> sprintf "%A"`:
```csharp
IL_0049: call instance !0[] valuetype [FSharp.Core]Microsoft.FSharp.Core.CompilerServices.ArrayCollector`1<object>::Close()
IL_004e: ldtoken class [System.Runtime]System.Tuple`6<int32, int32, int32, int32, int32, int32>
IL_0053: call class [netstandard]System.Type [netstandard]System.Type::GetTypeFromHandle(valuetype [netstandard]System.RuntimeTypeHandle)
IL_0058: call object [FSharp.Core]Microsoft.FSharp.Reflection.FSharpValue::MakeTuple(object[], class [System.Runtime]System.Type)
      
```

Please, reopen with illink/wasm team, so they can look why is it getting trimmed (though it's used in the `typeof`, which should use the type in the `ldtoken`).

The exception on the other hand is different issue, instead it should've said something along the lines "can't find tuple constructor for 'Tuple<int, int, int, int, int, int>'",
