### ISSUE TITLE
[VS] Solution Explorer displays some folders out of order

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#16943]
For example FSharp.Editor project:

`AutomaticCompletion` is first:

<img width="230" alt="image" src="https://github.com/dotnet/fsharp/assets/1760221/dc8eb478-09b7-4c67-ae53-6c8965140f76">

Should be before `Hints`:

![image](https://github.com/dotnet/fsharp/assets/1760221/adc9269b-302a-451e-bde2-62501fe56574)

VS 17.10.0 Preview 2.0
I don't recall seeing this in previous versions.

**Comment by brianrourkeboll** [comment]
I started seeing this as well.

**Comment by vzarytovskii** [comment]
I don't think we own that part. Unless we change ordering "in runtime" in targets, this should be investigated by project system. @KevinRansom I remember you've changed something regarding content includes in the past month or so.

**Comment by KevinRansom** [comment]
This is actually caused by the EnableDefaultNoneItems change.

It turns out that the project system discovers Folders as a consequence of <SomeItem Include="path to files" />
EnableDefaultNoneItems causes folders and .fsi files to be located in the solution folder, prior to the <Compile Include="" />

This causes folders and .fsi files to be displayed in the wrong order.
