### ISSUE TITLE
Better error recovery for unfinished result expressions in pattern matching clauses.

### ISSUE THREAD

**Issue by edgarfgp** [dotnet/fsharp#17079]
```fsharp
    let normalizeModuleOrNamespace(variant: StringVariant) =
        match variant with
        | Quoted identifier ->
            failwith "
        | Unquoted s -> s
        | TripleQuoted s -> s
        | BacktickQuoted identifier -> identifier
```

<img width="621" alt="Screenshot 2024-04-23 at 12 13 59" src="https://github.com/dotnet/fsharp/assets/31915729/325dbf9d-6126-40d8-839c-3602eb5103e8">

<img width="734" alt="Screenshot 2024-04-23 at 12 14 15" src="https://github.com/dotnet/fsharp/assets/31915729/1c545d02-27d2-49e2-b844-3124a9f95979">

<img width="613" alt="Screenshot 2024-04-23 at 12 14 33" src="https://github.com/dotnet/fsharp/assets/31915729/e39d6804-7254-477e-bfcd-e826847730a9">

<img width="594" alt="Screenshot 2024-04-23 at 12 16 52" src="https://github.com/dotnet/fsharp/assets/31915729/d1c26383-d6d7-4c1c-b027-fa937fb7deae">

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Ideally the compiler should be able to recover from this allowing the rest of the file to be analyzed.

**Comment by auduchinok** [comment]
@edgarfgp Do you remember how you ended up with only one double quote? I expect that they are added and removed together by an IDE during typing.

Unfortunately, in this particular case it looks like expected behavior: F# strings are always multiline, so everything after an unfinished string is considered a part of it, and this was a design choice in the language itself.

**Comment by edgarfgp** [comment]
> @edgarfgp Do you remember how you ended up with only one double quote? I expect that they are added and removed together by an IDE during typing.
> 

@auduchinok 
![Apr-23-2024 14-24-32](https://github.com/dotnet/fsharp/assets/31915729/bbffd07c-26d7-48d2-b6dd-a7e96e451ae0)

**Comment by T-Gro** [comment]
In the video, this is how strings work - you get them already doubled by the IDE, and you are expected to type in between them to get good recovery.

I do not see how this particular case could be changed throughout lexing, since strings are a legit part of the language.

Do you have a particular idea in which direction to improve this without breaking strings?
Also, why did you delete the double quote instead of typing in-between them?

**Comment by edgarfgp** [comment]
> In the video, this is how strings work - you get them already doubled by the IDE, and you are expected to type in between them to get good recovery.
> 
> I do not see how this particular case could be changed throughout lexing, since strings are a legit part of the language.
> 
> Do you have a particular idea in which direction to improve this without breaking strings? Also, why did you delete the double quote instead of typing in-between them?

@T-Gro I guess what I would expect is that when I delete a single pair of quotes it removes the other, leaving only the `failwith` ?

**Comment by T-Gro** [comment]
I am not sure if this would be the valid thing to do in all cases though.
