### ISSUE TITLE
Support TailCallAttribute in nested functions

### ISSUE THREAD

**Issue by esbenbjerre** [dotnet/fsharp#17274]
I often find myself embedding tail recursive functions inside other functions. Since F# 8.0 we can use the `[<TailCall>]` attribute, but it doesn't compile for nested functions. As an example I would like for the code below to compile.
```fsharp
let fib n
  =
  [<TailCall>]
  let rec loop i a b =
    if i = n then a
    else loop (i + 1) b (a + b)
  loop 0 0 1
```
but instead I get
```
error FS0010: Unexpected symbol '[<' in binding
```

**Comment by vzarytovskii** [comment]
That should be a language suggestion to support attributes on bindings inside bindings.

**Comment by Bananas-Are-Yellow** [comment]
My workaround is to use a private type.

In general, the resursive function is nested inside an outer function, and it references arguments and local values from the outer function. So, only the values that change during the recursion loop need to be supplied as arguments to the recursive function.

So instead of this:

```fsharp
module Text =
    let example arg1 arg2 arg3 =
        let val1 = ...
        let val2 = ...

        let rec loop a b c =
            ... // reference arg1, arg2, arg3, val1, val2 as needed here
            loop a' b' c'

        loop initA initB initC
```

You can do this:

```fsharp
module Test =
    type private Example (arg1, arg2, arg3) =
        let val1 = ...
        let val2 = ...

        [<TailCall>]
        let rec loop a b c =
            ... // reference arg1, arg2, arg3, val1, val2 as needed here
            loop a' b' c'

        member _.Result = loop initA initB initC

    let example arg1 arg2 arg3 = Example(arg1, arg2, arg3).Result
```

The `[<TailCall>]` attribute is allowed with this approach.
