### ISSUE TITLE
Can't reference static member in an interface, from another static member

### ISSUE THREAD

**Issue by thomasd3** [dotnet/fsharp#17599]
Here's the sample code:

```
#nowarn "3535"
type ITest =
    
    static abstract member a: string array
    static abstract member b: string
    
    
type Test =
    
    interface ITest with
        
        static member a = [|"hello"; "world"|]
        static member b = Test.a[1]    // Type Test doesn't define the field 'a' 
```

Using:

```
static member b = ITest.a[1]
```

Will work on the other hand. 

Since we are in the interface definition, it would make sense that the compiler sees 'a' as part of ITest as well. Or am I missing something?

**Comment by vzarytovskii** [comment]
This is sort of expected and was undecided when implementing this feature, I think the following covers it in the design:

https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md#alternatives-for-invoking-static-abstract-member-implementations-directly

It needs to be a separate suggestion how it should be dealt with since it goes against how things like this are handled in F# (for instance members we would require cast to interface, whereas with statics it won't work).

**Comment by abonie** [comment]
For this to work as you expect @thomasd3 option C or D from [the RFC](https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md#alternatives-for-invoking-static-abstract-member-implementations-directly) Vlad linked to above would need to be implemented and that requires a language suggestion [here](https://github.com/fsharp/fslang-suggestions)
