### ISSUE TITLE
Array comprehension no longer compiles on rc1

### ISSUE THREAD

**Issue by sayurin** [dotnet/fsharp#17708]
Please provide a succinct description of the issue.

**Repro steps**

Following code causes compile error on .NET 9 RC1.

```
let arr = [| for _ in Array.groupBy id [||] do 0 |]
```

**Expected behavior**

.NET 8 can compile it, successfully.

**Actual behavior**

.NET 9 RC1 fails with following error.

```
FSC : error FS2014: A problem occurred writing the binary 'obj\Release\net9.0\refint\FsConsoleApp3.dll': duplicate entry 'arr@1' in type index table
```

**Known workarounds**

split it.

```
let arr = [|
    let arr = Array.groupBy id [||]
    for _ in arr do 0
|]
```

**Related information**

Provide any related information (optional):

* Windows 11
* .NET 9 RC1
* Visual Studio Professional 2022 Preview 17.12.0 Preview 2.0

**Comment by brianrourkeboll** [comment]
This must be from one of my PRs. I will look into this.

**Comment by brianrourkeboll** [comment]
> **Known workarounds**
> 
> split it.
> 
> ```
> let arr = [|
>     let arr = Array.groupBy id [||]
>     for _ in arr do 0
> |]
> ```

It looks like this only happens when the `pat` in `for pat in expr …` is the wildcard `_`. So another workaround is to give it a name (prefixed by an underscore if you don't want to use it).

This compiles:

```fsharp
let arr = [| for _group in Array.groupBy id [||] do 0 |]
```

**Comment by vzarytovskii** [comment]
It's this `LowerSimpleMappingsInComprehensionsToFastLoops` feature which breaks it. I will have a PR in case if we won't have fix til monday (SDK lockdown), so we can quickly insert it last moment and then re-enable in 9.1

**Comment by sayurin** [comment]
@brianrourkeboll wildcard `_` is simplified case. pattern matching at `for` expression also causes FS2014.

```
// case 1: FS2014
let arr = [| for _ in Array.groupBy id [||] do 0 |]
// case 2: OK
let arr = [| for paired in Array.groupBy id [||] do 0 |]
// case 3: FS2014
let arr = [| for key, grouped in Array.groupBy id [||] do 0 |]
```

**Comment by brianrourkeboll** [comment]
...The real problem is actually a very simple one: I neglected to bind `srcArray` to a compiler-generated local in #17067 🤦‍♂️.

That means that the source array expression is evaluated multiple times (🤦‍♂️🤦‍♂️🤦‍♂️):

https://github.com/dotnet/fsharp/blob/aea757f2cb54798c3b6584a8e1297ca306bb0e9d/src/Compiler/Optimize/LowerComputedCollections.fs#L377

and

https://github.com/dotnet/fsharp/blob/aea757f2cb54798c3b6584a8e1297ca306bb0e9d/src/Compiler/Optimize/LowerComputedCollections.fs#L399

The equivalent optimization for lists does not have this problem, because it was already binding `srcList` to a compiler-generated local:

https://github.com/dotnet/fsharp/blob/aea757f2cb54798c3b6584a8e1297ca306bb0e9d/src/Compiler/Optimize/LowerComputedCollections.fs#L291-L297

Luckily, this is a very easy problem to fix.

Because I originally thought that this issue was related to pattern-matching and wildcards, I also found and have fixes for two issues related to those.

I'll be updating my PR once I have the baselines updated...

**Comment by brianrourkeboll** [comment]
Thank you @sayurin for trying out the release candidate today and opening this issue so that I could fix it!
