### ISSUE TITLE
Inline Rename does not work on non-private symbols on dirty buffers

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2204]
![image](https://cloud.githubusercontent.com/assets/873919/21766133/a680a858-d67d-11e6-8687-bbd43f0cc15e.png)

![image](https://cloud.githubusercontent.com/assets/873919/21766141/b61bb906-d67d-11e6-876d-0418a4a27c59.png)

**Comment by vasily-kirichenko** [comment]
The bug is reproduced on dirty buffers only.

The feature uses `ParseAndCheckProject` here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/SymbolHelpers.fs#L44, which reads file contents from disk (via `FileSystem` class):

![image](https://cloud.githubusercontent.com/assets/873919/21766484/e2fc40a6-d67f-11e6-9833-ea10cabf9a2b.png)

Project-wide diagnostics are not enabled due to the same bug, see https://github.com/Microsoft/visualfsharp/issues/1856 (I've no idea why it's closed).

**Comment by cartermp** [comment]
Good catch.  Hmmmm.  This is definitely an important one to fix, but looking at the discussion in #1856 it seems that this may not make it into release.  I'm still tagging as RTM though, since the importance of getting something like this fixed is high enough to warrant looking at it as an immediately-after-release issue.

**Comment by cartermp** [comment]
Updating to high severity since it makes rename useless for so many people. @TIHan has been investigating this.

**Comment by 0101** [comment]
Fix is available as an opt-in setting, see https://github.com/dotnet/fsharp/issues/14033
