### ISSUE TITLE
Pass cancellation token to Type Providers to allow them cancelling long running operations

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2327]
Type Providers do not aware of operation cancellations initiated by IDE, which results with UI freezes when user executes completion on a provided type and the type provider takes long time to generate types (network or DB access, etc)

See https://github.com/Microsoft/visualfsharp/pull/2315#issuecomment-275667133

**Comment by dsyme** [comment]
> ...which results with UI freezes ...

If the UI is implemented correctly then it should at least never freeze.  However language service features may become unresponsive or disabled.

Note that fixing this may require additions to the type provider APIs, which are going to be tricky to roll out in practice.  The type provider API is an implementation of the System.Type model, and in the current ways of implementing type providers every single property access and method call on every System.Type, Sytem.MethodInfo etc. may (and in practice sometimes does) involve computation and/or network access.  We can't easily pass in cancellation tokens to all of these without ridding ourselves of the use of both quotations and System.Type - it would require a complete overhaul of the API.

Interim solutions such as placing the active cancellation token in a thread local during the call may be possible.  Likewise using a single thread per type provider instance, so that a timeout policy can be enforced by the UI.

FWIW I don't think this issue is totally critical since it's been this way all along, and is somewhat inherent in the use of computation in type providers (c.f. Scala macros etc., all of which are tricky to sandbox and bound)
