### ISSUE TITLE
VS2017 colorization bug / generic argument becomes punctuation like

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#2585]
There is a discrepency in colorization:

![image](https://cloud.githubusercontent.com/assets/87944/23825803/0ebf28c0-0691-11e7-9b90-75f89691a58f.png)

When a type constructor is called with `new` the colorization of generic arguments changes, I think the correct color is the one when `new` is not used.

**Comment by cartermp** [comment]
Re-labeling. This is probably a bug in name resolution, where the `<_>` is getting resolved to be a part of the constructor. Classification does the right today and with https://github.com/dotnet/fsharp/pull/9511, but since the `<_>` is getting resolved incorrectly there's nothing to correct in terms of classification.
