### ISSUE TITLE
Find Usages: if there is single usage, jump right to it

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2938]
This is how Rider does it:

![1](https://cloud.githubusercontent.com/assets/873919/25523529/a5110cbe-2c0f-11e7-8424-1be9461ab2cd.gif)

**Comment by cartermp** [comment]
I like this a lot. 👍

**Comment by vasily-kirichenko** [comment]
I'm afraid Roslyn won't let us impl this :(

**Comment by cartermp** [comment]
cc @CyrusNajmabadi - I think this would be a great addition to the Roslyn behavior.

**Comment by CyrusNajmabadi** [comment]
This is challenging due to the async nature of find refs.  We don't know there is only one ref until the operation completes.  But, in the meantime, we've popped up the window to show you the progress of what's happening. We'd have to either make the computation synchronous (bad), or not poop up the window until there are two results (confusing), or dismiss the window and navigate you to the single result (strange). The latter would be especially awkward if the user was just about to click on something in find refs.

We could have the window appear, but navigate you to the single item on completion. But I don't think that would be a particularly great experience either

**Comment by CyrusNajmabadi** [comment]
One way we could try to do this would be to kick off the work to do find-refs with no UI, and also kick off a timer set to something appropriately short (like 1 second).  If the FindRefs work finished in that second, and only had a single result, then we could take you there.  If, however, the work did not complete, we'd immediately pop open the window.  That way the user could see that work was happening and could see the progress of the search.

**Comment by CyrusNajmabadi** [comment]
Also, as usual, PRs welcome :)

**Comment by slang25** [comment]
@CyrusNajmabadi 
> or not poop up the window

You definitely don't want to do that 😄

**Comment by vasily-kirichenko** [comment]
It's unlikely to be implemented.

**Comment by CyrusNajmabadi** [comment]
Not sure why this was closed.  I think it's a great idea :)

**Comment by dsyme** [comment]
OK, reopening

**Comment by obeobe** [comment]
My two cents: this is how Rider does it and I find it quite annoying and wish they didn't. The fact that I'm searching for usages doesn't necessarily mean that I want to go there. Maybe I just want to have a look at it at the preview window? Why throw me away from the context I'm at?

Also, in general, I find inconsistent behavior annoying. It doesn't make sense to me that the IDE would sometimes pop up a window, and sometimes navigate away from where I'm at, following the same exact action.

Navigation is intrusive and disruptive and should never happen automatically (or at least there should be a way to disable this behavior in the settings, which there might be but I couldn't find one...). For example, I believe that one of the most hated VS features is the one that automatically previews a file in the main work area when you merely select it in the solution window (and in other situations).

**Comment by vasily-kirichenko** [comment]
My two cents: I use Rider all the time and find this behavior awesome.

**Comment by obeobe** [comment]
@vasily-kirichenko nonetheless it should still be configurable. Anything that interacts with your work in intrusive ways (i.e. implicit navigation, live code refactoring, automatic completion of code like quotes, braces, etc...) - needs to be configurable.

**Comment by vasily-kirichenko** [comment]
Of course. Anyway, it's unlikely to be implemented, so this discussion is meaningless :)

**Comment by CyrusNajmabadi** [comment]
> Anyway, it's unlikely to be implemented, so this discussion is meaningless :)

Why is it unlikely to be implemented?  I already sketched out how it could possibly be done.  I think it would make sense to go behind an option, but i think it would be totally fine to do. 

The code that you would have to update would be around here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/FindReferences/FindReferencesCommandHandler.cs#L129

Basically, instead of calling directly into the presenter ot make the FindUsagesContext object to push results into, you would instead:

* Create your own FindUsagesContext subclass.  This type would buffer the results until one of the following things happened:
    * It got two results.  In which cases it would pop up the presenter window.
    * It got no results and the search signaled 'done'.  In which case it would pop up the presenter window.
    * It got one result, and more than one second had passed.  It would then pop up the presenter window and push the single result it had to it.  And future results woudl go into the presenter window.
    * It got one result, and got 'done' signaled before a second had passed.  It would immediately navigate to that single result.

(Of course, it would only do this if the option were set.  If it were not set, it would just go through the current codepath).

**Comment by CyrusNajmabadi** [comment]
Feel free to make such a change and submit it to Roslyn.  I think it would be taken.  Tagging @kaseyu for visibility here as I think she might like this change.

**Comment by vasily-kirichenko** [comment]
Thanks for explanation, I believe Visual F# team will implement it soon.

**Comment by CyrusNajmabadi** [comment]
Sounds good.  Let me know if you need any help/clarity here.  The toughest parts (afaict) will be writing your own 'buffering' FindUsagesContext that can act as a sink, and then flush itself appropriately to the real context.  This will also be a bit complex because the creation of the real context needs to happen on the UI thread.  However, due to the async nature of the context API it should not be hard to accomplish.

**Comment by Pilchie** [comment]
Note that it's @kuhlenh, not @KaseyU (sorry!)
