### ISSUE TITLE
debug version of FSharp.Core has some peverify failures

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#2940]
This doesn't cause problems for release mode but we should fix it in any case

```
C:\GitHub\dsyme\visualfsharp>peverify debug\net40\bin\fsharp.core.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\GitHub\dsyme\visualfsharp\debug\net40\bin\fsharp.core.dll : Mic
rosoft.FSharp.Core.Operators::castToString[T]][offset 0x00000002][found (unboxed
) 'T'][expected ref 'System.String'] Unexpected type on the stack.
[IL]: Error: [C:\GitHub\dsyme\visualfsharp\debug\net40\bin\fsharp.core.dll : Mic
rosoft.FSharp.Core.LanguagePrimitives::retype[T,TResult]][offset 0x00000002][fou
nd (unboxed) 'T'][expected (unboxed) 'TResult'] Unexpected type on the stack.
[IL]: Error: [C:\GitHub\dsyme\visualfsharp\debug\net40\bin\fsharp.core.dll : Mic
rosoft.FSharp.Core.BasicInlinedOperations::castclassPrim[T]][offset 0x00000007][
found ref (boxed) 'T'][expected (unboxed) 'T'] Unexpected type on the stack.
[IL]: Error: [C:\GitHub\dsyme\visualfsharp\debug\net40\bin\fsharp.core.dll : Mic
rosoft.FSharp.Core.BasicInlinedOperations::notnullPrim[T]][offset 0x00000003][fo
und (unboxed) 'T'] Non-compatible types on the stack.
[IL]: Error: [C:\GitHub\dsyme\visualfsharp\debug\net40\bin\fsharp.core.dll : Mic
rosoft.FSharp.Core.BasicInlinedOperations::iscastPrim[T]][offset 0x00000007][fou
nd ref (boxed) 'T'][expected (unboxed) 'T'] Unexpected type on the stack.
5 Error(s) Verifying debug\net40\bin\fsharp.core.dll

```

**Comment by abelbraaksma** [comment]
It's been a while, is this even still an issue? A lot of work has been done in the compiler since then.

Pinging here in general since I'm in a discussion with NCrunch creator Remco about the problem with instrumenting code that is not PE-verifiable; in this case leading to assemblies that cannot be loaded (after instrumenting, I mean). I know that it is possible to compile F# code into non-PE-verifiable code, but generally I experience that most code compiles just fine.

In another issue (can't find it now), I believe @cartermp (apologies in case I'm misquoting) said that PE-verifiability is now an outdated concept, but I struggle to get the full extend of the effect of that to existing tooling out there. I think the main issue would be that weaving and instrumenting becomes really, really hard if the IL is non-verifiable.

(side note: I know you can always deliberately create code that is non-verifiable, but that's not the point of the discussion here).

**Comment by cartermp** [comment]
Span breaks PEVerify, and it's now a core type throughout all of .NET Core. While that isn't related to this issue, I think that the instant you move off of .NET Framework, all bets are off w.r.t PEVerify. Unsure if this is still an issue with FSharp.Core, but I don't think it's a high priority one to resolve if it still is. We'd probably take a pull request though.

**Comment by dsyme** [comment]
It's a long time back, but it seems that somewhere between FSharp.Core 4.6.2 and 4.7.0 we seem to start to generate code in FSharp.Core.dll that gives further peverify errors

Now peverify is a somewhat old tool that doesn't cover everything that is now considered valid IL, so this may be expected for some reason.  But I wasn't expecting this

```
peverify \Users\Administrator\.nuget\packages\fsharp.core\4.6.2\lib\net45\FSharp.Core.dll
peverify \Users\Administrator\.nuget\packages\fsharp.core\4.7.0\lib\net45\FSharp.Core.dll
```

The second gives
```
[MD]: Error: Token 0x0200007d following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x2B000026]
[MD]: Error: Token 0x020007b8 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x2B0002B8]
[MD]: Error: Token 0x020008f1 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x2B00038C]
```

**Comment by abelbraaksma** [comment]
There's a new tool available that supersedes peverify. I forgot its name, and it still has some issues, but it's part of the official binaries and works with .NET 5 iirc.

**Comment by dsyme** [comment]
Closing out this old issue, it's not a problem in practice
