### ISSUE TITLE
Internal error FS0073: Undefined or unsolved type variable: 'TRange when compile in Release mode

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#31]
[From fsbugs] 

 When compiling below code with --optimize+, get internal error: 
 Program.fs(27,9): error FS0073: internal error: Undefined or unsolved type variable: 'TRange

``` fsharp
namespace QuotationsProblem

open Microsoft.FSharp.Quotations

type Class1() =

    member private this.CompileQuery<'T>() =
        let kernel = System.Activator.CreateInstance<'T>()
        kernel

    member this.X (query: Expr<'TRange ->'a>) =
        let rng = ref Unchecked.defaultof<'TRange>
        let getStarterFuncton qExpr =
            let rec go expr vars =
                match expr with
                | Patterns.Lambda (v, body) -> Expr.Lambda(v, go body (v::vars))
                | e ->
                    let arr =
                        let c = Expr.NewArray(typeof<obj>,vars |> List.rev
                            |> List.map (fun v -> Expr.Coerce (Expr.Var(v), typeof<obj>)))
                        <@@
                            let x = %%c |> List.ofArray
                            rng := (box x.Head) :?> 'TRange
                        @@>
                    arr
            1
        getStarterFuncton query
```

**Comment by vladima** [comment]
minified repro
```F#
namespace QuotationsProblem

type Class1() =
    static member A<'a>() = ()
    static member B(rng: 'TRange ref) =
        let rec go a =
            if a then go a
            else
            <@@ rng := box 1 :?> 'TRange @@>
        1

```

**Comment by dsyme** [comment]
@vladima discussed with me that the underlying cause is the reallocation of the reference cell in the Expr.Quote node by the "instExpr" operation inside ChooseTyparSolutionsForFreeChoiceTypars.  This means "check.fs" doesn't correctly fill in the AST value of the quotation for the untyped quotation.

    | Expr.Quote (a,{contents=None},isFromQueryExpression,m,ty) ->  
        Expr.Quote (remapExpr g (fixValCopyFlagForQuotations compgen) tmenv a,{contents=None},isFromQueryExpression,m,remapType tmenv ty)

I believe this node should not be reallocated in this pass. I suggest adding a new flag ``CloneAllKeepReferenceCells``  to ValCopyFlag:

    type ValCopyFlag = 
        | CloneAll
        | CloneAllKeepReferenceCells  <-- add this
        | CloneAllAndMarkExprValsAsCompilerGenerated
        | OnlyCloneExprVals

and adding a boolean flag into ``instExpr`` and ``ChooseTyparSolutionsForFreeChoiceTypars`` which activates this flag, and returning the original reference cell when this flag is active

    | Expr.Quote (a,({contents=None} as origRefCell),isFromQueryExpression,m,ty) ->  

We may have to review additional code paths at the callers to these two functions, though initially assume that the flag doesn't have to be set on any other code paths.

Cheers
Don

**Comment by vladima** [comment]
unfortunately after a deeper look this approach will not work. If ref cell is not reallocated then after running check phase on the node produced by `instExpr` then it might be filled with transient data that does not match the rest of the tree. i.e if `instExpr` can copy  some `Val` and this `Val` is captured in quotation then ref cell will save information about this copied Val and this will cause crash on other compilation steps later. As an option we can extract code that creates quotations from the `check` into the separate phase so it will always use consistent view of the tree

**Comment by KevinRansom** [comment]
Has been fixed.
