### ISSUE TITLE
If NuGet restore fails then build still continues

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#3218]
We should let the build fail if a restore doesn't work.

![image](https://user-images.githubusercontent.com/57396/27251089-8bd38734-533f-11e7-9d5a-5251dd67607a.png)

#### Repro steps

get on slow internet connection and run build.

**Comment by cartermp** [comment]
Thoughts @kevinransom?

**Comment by xdaDaveShaw** [comment]
Isn't is because nuget.exe is returning an errorcode other that 1? 

The code [here](https://github.com/Microsoft/visualfsharp/blob/master/build.cmd#L534) is only testing for `1` as an error. Shouldn't it be:

    @if NOT ERRORLEVEL 0 echo Error: Nuget restore failed  && goto :failure

**Comment by forki** [comment]
probanbly. @xdaDaveShaw could you please try to send a fix? thx

**Comment by xdaDaveShaw** [comment]
@forki -  yeah, I'll have a look now

**Comment by xdaDaveShaw** [comment]
I guess I was wrong, from [Old New Thing](https://blogs.msdn.microsoft.com/oldnewthing/20080926-00/?p=20743):

> The IF ERRORLEVEL n test succeeds if the error level is n or more...

From my debugging it looks like errorlevel is `0` after a failure, but only in the batchfile, creating a failure of nuget.exe in cmd returns an errorlevel of 1, just fine.

I suspect somewhere someone is doing a SET ERRORLEVEL=0, I'll keep looking

**Comment by xdaDaveShaw** [comment]
Hmm, I thought I had a way to repro it by passing `-Source http://somewhere.not.real` to nuget.exe - but that must have been a red herring, because that now fails the entire build (I have no idea what I did to make that repro the bug).

So, looks like I cannot find a way to repro this, it might be a nuget.exe issue, might be something else.

- I cannot repro with a 10mb connection, slowest I can make mine go.
- I cannot repro by changing a single package to a version that doesn't exist, e.g. setting MicroBuild.Core to version 22.22.22.

I think I might have to leave this for now.

**Comment by KevinRansom** [comment]
Does this still repro for you?

Please reopen if you notice issues

Kevin
