### ISSUE TITLE
Debugger doesn't show values of variables (computation exp, v 4.3.1)

### ISSUE THREAD

**Issue by denisnikolayev** [dotnet/fsharp#3360]
In some cases values of variables in vs 2017 aren't shown.

there is an error in watch toolbox:
error CS1705: Assembly 'FileProcessor' with identity 'FileProcessor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'FSharp.Core' with identity 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

it seems like it is somehow referenced to computation exp: gif with issue
![bug](https://user-images.githubusercontent.com/14340491/28465202-e51632bc-6df5-11e7-880f-1b304dcab718.gif)

Unfortunately I could not reproduce this issue on small repo

* Operating system
Windows
* Editing Tools (e.g. Visual Studio Version)
night builds (vs 2017)

**Comment by johnvanloon** [comment]
We are hitting the same issue. See a small repo in the gif.
This only occurs when using the new slimmed down fsproj format. But both when targetting netcoreapp2.0 and net461.
Same behavior occurs in all our Akka.FSharp actor-code. Which makes it a huge blocker for us.

![debug](https://user-images.githubusercontent.com/9896420/29631200-1b863596-883f-11e7-871c-da0de5c54040.gif)

If you need any more info I'm happy to dive into this further. Thanks.

**Comment by abelbraaksma** [comment]
@johnvanloon and @denisnikolayev,  I think it is caused because the computation expression is actually not in the same scope (though I have no idea of a solution).

For me, usually stepping into the computation expression shows at least those values that are used within it (and anything outside it, even at the same level, is shadowed / not available for evaluation during debugging). Sometimes I use a dummy statement or a `Debug.Assert` to force the values to be evaluated in computation expressions, even when not otherwise used, but I typically need to first jump past such statement, yet stay *inside* the computation expression, to be able to see them.

**Comment by johnvanloon** [comment]
@abelbraaksma I have seen that before when using the old project format. This however seems to a regression caused by the move to the new fsproj format (from the old fsproj, don't know about projects.json)

**Comment by cartermp** [comment]
@johnvanloon Could you file a separate bug for not seeing any locals with using the new .NET Core SDK-based projects?  Although those aren't fully supported yet, it's good to have a bug filed early on.

**Comment by johnvanloon** [comment]
@cartermp I will file a new issue if you want, but I'm curious how you know this is a different problem. I don't see any mention of project type in the original issue.  Also just to be clear, in my case it also only occurs in computational expressions.

@denisnikolayev : Does it occur on your machine in an old-style fsproj?

**Comment by 0x53A** [comment]
If it is different between old-sdk and new-sdk, then it is probably related to the pdb type.

New-Sdk defaults to portable-pdb; you could check if you get the same behavior with old-sdk and explicit portable-pdb.

**Comment by johnvanloon** [comment]
@0x53A That was the issue for us indeed. Changed to full-pdb and now the locals show up again. Thanks a lot, this really helps us!

**Comment by johnvanloon** [comment]
@cartermp  Should I still file a new issue for this?

**Comment by cartermp** [comment]
@johnvanloon Yes, please do.  As @0x53A mentioned (while I was sleeping 😄), your issue is related to Portable PDB generation, which are the PDBs we generate for cross-platform debugging.  I believe @denisnikolayev is working on a solution targeting .NET Framework with the traditional, Windows-only PDBs.

**Comment by abelbraaksma** [comment]
> Changed to full-pdb and now the locals show up again. Thanks a lot, this really helps us!

@johnvanloon, where is that setting? Or is this commandline only? I have similar issues (missing locals) in VS2017, but I can find the option for the PDB settings only for C# projects (under Advanced in project settings), but not for F#.

**Comment by johnvanloon** [comment]
@abelbraaksma 
Just edit the fsproj files. 
Add <DebugType>full</DebugType> to propertygroup

**Comment by cartermp** [comment]
This no long reproduces in the VS 16.10 builds:

![image](https://user-images.githubusercontent.com/6309070/110721427-66502180-81c5-11eb-95f6-cef364f023b7.png)

I suspect that 2.5 years ago there were just a lot more things missing in the F# compiler, build tools, and VS tools for .NET SDK-style projects that made this an issue. Now that considerably more work has gone into each of these areas, it seems to no longer reproduce.
