### ISSUE TITLE
No ".." folder in #r path completion

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3437]
![image](https://user-images.githubusercontent.com/873919/29328634-ea6913d2-81fb-11e7-8e48-0abb7c1f57cc.png)

**Comment by cartermp** [comment]
I can repro.  Also not present in C# Interactive:

![no-in-csx](https://user-images.githubusercontent.com/6309070/29332349-93ce68b6-81b4-11e7-824e-0191a090a628.PNG)

Although I can type "\packages" and get completion there, whereas in the F# script file, the completion is now gone.  So that seems to be throwing it off on our end somehow.

**Comment by vasily-kirichenko** [comment]
I'm absolutely sure `..` was presented in VS 2017.2

**Comment by vasily-kirichenko** [comment]
We use the Roslyn code (as far as I can remember), so it seems they've changed the list.

**Comment by cartermp** [comment]
Hmmm.  I also noticed that `#r "...\"` will trigger completion just fine.  @Pilchie are you aware of anything that may have changed in file system completion>?
