### ISSUE TITLE
TypeProvider or Strings designer file for resources?

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#3492]
@sergey-tihon  has a particularly groovy type provider for using resources from F# code here:

https://fsprojects.github.io/FSharp.Configuration/ResXProvider.html

We have added a resource template to the tooling, but accessing the resources will require manual coding until we provide a means to  access them.

C# produces a designer file.  But the TP above looks like it may be a more idiomatic tool.  Shall we include this TP in the standard tooling or go with a C# style designer file?

Kevin

**Comment by sergey-tihon** [comment]
For clarity, `ResXProvider` is not mine, as I see from [commit history](https://github.com/fsprojects/FSharp.Configuration/commits/master/src/FSharp.Configuration/ResXProvider.fs) it was initially created by @ptrelford and merged into `FSharp.Configuration` by @forki .

In short term, C# style designer is definitely an easier way to go.

I personally believe that we should go with TP. In may be slightly harder at the beginning, but it allows us to show that TPs are definitely production ready, we are not afraid to utilize them, will fix issues if any and maybe develop more best practices of TP design. 

_P.S. If you choose to use TP - I am ready to help to address issues if any 👷_

**Comment by KevinRansom** [comment]
@sergey-tihon I am inclined to start using the tp.

**Comment by abelbraaksma** [comment]
I'd very much welcome adding resource support for F# projects, it has been one of the most important features missing in language (well, IDE) support in my projects (esp. my XSLT 3.0 compiler, Exselt, which makes heavy use of resources).

I think the more idiomatic way is a type provider, even while type providers are not yet supported in .NET Core. But more importantly I think we should discuss what F#-style or functional style resource handling should look like.

The way I am currently doing it is: a separate C# project, compiled with [ResX Resource Manager](https://github.com/tom-englert/ResXResourceManager) to create parameter-safe (not typesafe) methods, which are consequently wrapped in a functional style. A rather clumsy approach I admit.

More idiomatic and hopefully not too hard to implement would be something that creates typesafe functions in a given resource module, similar to `sprintf`. To reach that, the resources should support either the `sprintf` PrintFormatter syntax, or a variant/combination of the .NET style format syntax (not sure how that would look like though).

This would not only show what @sergey-tihon mentions, that type providers are stable, useful and production ready, it also shows that we can leverage the power of type safety with inter-string handling and resources, much better than any other .NET language, even powered with RESX Resource Manager, has ever come to support.

But apart from this potentially becoming a showcase, the usability of typesafe resources should be the main argument for moving in that direction.

In case my text is too vague, say your resource string with id `AGE01` is `"Your age is %i, your name is %s."` should become `val Res.AGE01: int -> string -> string`, i.e., the body of whatever is auto-generated by the TP or otherwise, should be:

```
module Res =
    let AGE01 = printf "Your age is %i, your name is %s."
```

To create that as a designer file is probably trivial, to create that through a TP probably less so, I'm not sure.

**Comment by dsyme** [comment]
CLosing out this old suggestion
