### ISSUE TITLE
Attached VS debugger makes everything unbelievably slow with IntelliTrace on

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3625]
VS 15.3.5

![1](https://user-images.githubusercontent.com/873919/30757553-cecf826a-9fd7-11e7-8271-7d327803ad9d.gif)

Rider:

![1](https://user-images.githubusercontent.com/873919/30757281-c4092602-9fd6-11e7-9982-88064d15fbea.gif)

I have to words.

**Comment by vasily-kirichenko** [comment]
Solved: VS debugger become as fast as Rider's after turning off IntelliTrace.

**Comment by forki** [comment]
Haha

Am 22.09.2017 19:56 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@forki yes, it was very funny, thanks for your help.

**Comment by forki** [comment]
Can you please send a pull request to the readme. I'm sure others will have
the same problem and we should take it as opportunity to document.

Am 22.09.2017 20:02 schrieb "Vasily Kirichenko" <notifications@github.com>:

@forki <https://github.com/forki> yes, it was very funny, thanks for your
help.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/3625#issuecomment-331519312>,
or mute the thread

**Comment by dsyme** [comment]
Is IntelliTrace just as slow with C#, or is it an F# + IntelliTrace interaction?

**Comment by dsyme** [comment]
I'll reopen until we know the extent of the problem, I've had other people tell me informally about this

**Comment by vasily-kirichenko** [comment]
> Is IntelliTrace just as slow with C#, or is it an F# + IntelliTrace interaction?

No, for C# it's fast. I remember I debugger Roslyn and everything worked perfectly fast.

**Comment by dsyme** [comment]
@cartermp If this is F# only then this is quite a significant problem.  Can we repro it? And if neccessary add a tracking bug with the debugger team?  F# should not be hit disproportionately here? thanks

**Comment by cartermp** [comment]
@gregg-miskelly for FYI.  Is this something we know of for other langs?

**Comment by gregg-miskelly** [comment]
If you go to the events tab in the diagnostics tools window, do you see a ton of some kind of event? (ex: exceptions)

**Comment by dsyme** [comment]
Closing this old issue
