### ISSUE TITLE
error FS0193: internal error: Could not load type 'FSI_0002' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by mrakgr** [dotnet/fsharp#4041]
```
type Env0 =
    struct
    val mem_0: int64
    val mem_1: int64
    new(arg_mem_0, arg_mem_1) = {mem_0 = arg_mem_0; mem_1 = arg_mem_1}
    end
and Tuple1 =
    struct
    val mem_0: Env0
    new(arg_mem_0) = {mem_0 = arg_mem_0}
    end
and Env2 =
    struct
    val mem_0: (int64 [])
    val mem_1: Tuple1
    val mem_2: int64
    val mem_3: int64
    new(arg_mem_0, arg_mem_1, arg_mem_2, arg_mem_3) = {mem_0 = arg_mem_0; mem_1 = arg_mem_1; mem_2 = arg_mem_2; mem_3 = arg_mem_3}
    end
and Env3 =
    struct
    val mem_0: int64
    val mem_1: int64
    new(arg_mem_0, arg_mem_1) = {mem_0 = arg_mem_0; mem_1 = arg_mem_1}
    end
and Tuple4 =
    struct
    val mem_0: Env3
    val mem_1: Env3
    new(arg_mem_0, arg_mem_1) = {mem_0 = arg_mem_0; mem_1 = arg_mem_1}
    end
and Env5 =
    struct
    val mem_0: Env2
    val mem_1: Tuple4
    new(arg_mem_0, arg_mem_1) = {mem_0 = arg_mem_0; mem_1 = arg_mem_1}
    end

Env5((Env2([||], Tuple1((Env0(0L, 1L))), 0L, 2L)), Tuple4((Env3(0L, 2L)), (Env3(0L, 2L))))
```

This issue is similar to the one I opened [previously](https://github.com/Microsoft/visualfsharp/issues/3581) and was thought resolved. I can confirm that the previous issue was indeed resolved using F# Interactive 4.1 with the input given there, but I ran into the bug again with the input shown here.

**Comment by dsyme** [comment]
@mrakgr Thanks

In F# Interactive, these structs are dynamically generated using RefEmit as nested types of an implicit containing module type. 

Historically we've had persistent niggling problems where the process of dynamically generating recursively-referential nested struct types triggers a load fault in the .NET type loader where the completion of the implicit enclosing type is required before the process of generation is finished. This is tricky to nail down and feels a bit like a game of whack-a-mole: in each particular case we've made some progress but never quite nailed the problem

Is there a workaround you can use?  For example, generate these types into a namespace and statically compile  or ``#load`` that file?  That tends to solve the problem because the types are not nested types in an enclosing module type.

**Comment by mrakgr** [comment]
Well, it is not really a problem for me as I using this code in regular `.fs` files. I just encountered error this while testing my compiler's output in the Repl and decided to report it. In the Repl I can get it to run by sending the types to FSI first and then the actual code in two separate steps.

**Comment by dsyme** [comment]
@mrakgr OK, thanks.

**Comment by dsyme** [comment]
See also another instance of this at https://github.com/dotnet/fsharp/issues/5450

**Comment by dsyme** [comment]
This is fixed by `--multiemit+` which is on by default for .NET Core
