### ISSUE TITLE
About the state of the legacy MSBuild resolver in FCS

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#4254]
I was wondering if the legacy resolver is going to be dropped in Visual Studio?
I haven't seen many uses of `#r "Foo, Version=1.3.4"` in users' code and it is [said](https://github.com/Microsoft/visualfsharp/tree/master/fcs#the-two-other-nuget-packages) to be the only feature it's still needed for.
I'd like the resolve logic to work the same way across the editors/OS where's possible so we could disable such references (unless a special legacy compiler switch is passed) or show a warning when such reference is used.

**Comment by cartermp** [comment]
I will take the position that we can deprecate this for a few reasons:

1. I highly doubt people specify assemblies in scripts like (nor do I think they did that a lot back in MSBuild 12.0 days)
2. I agree that making it be the same across editors is good
3. Deprecation is easy to document here, and since we use semver we won't be violating assumptions

**Comment by dsyme** [comment]
I think people may have occasionally used this when simple references picked up the wrong assembly from installed Assembly folders, and hardwiring paths was not right for cross-machine use.

But I think we can deprecate this once we have nuget package references.

**Comment by cartermp** [comment]
I think we can close this out because with the recent FCS incorporation we have _not_ brought along the legacy stuff and have no plans to do so. So we can consider this deprecated, especially with `#r "nuget"` coming along in F# 5.
