### ISSUE TITLE
When running compiler on .NET Core, dependencies of TPDTCs in the same directory are not located

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#4579]
When loading a TPDTC (type provider design time component DLL), we have always used `Assembly.LoadFrom`.  This allows any dependencies to be loaded from the directory containing the TPDTC.

However, when the compiler runs on .NET Core, our "reshaped reflection" implementation only does what appears to be the equivalent of `LoadFile` (called `LoadFromAssemblyPath`)

For example, if a type provider package contains

    lib/netstandard2.0/MyProvider.dll

    typeproviders/fsharp41/netstandard2.0/MyProvider.DesignTime.dll
    typeproviders/fsharp41/netstandard2.0/SomeLibrary.dll

this will load into the compiler when running on .NET Framework, but not when running on .NET Core.

### Solution

I'd say we should just stop using `netstandard1.6` as the target for FSharp.Compiler.Private.fsproj and use `netstandard2.0`.  `Assembly.LoadFrom` is available as part of `netstandard2.0` for CoreCLR.

### Workaround 

Either

1. Don't have TPDTCs with dependencies

2. self-resolve any dependencies using ResolveAssembly events.  

3. Use [the workaround to use the .NET Framework/Mono compiler ](https://github.com/Microsoft/visualfsharp/issues/3303)

**Comment by dsyme** [comment]
@brettfo @KevinRansom AFAIK fixing this requires moving FSharp.Compiler.Private.ddll to `netstandard2.0`. Is there any technical reason we can't do that, e.g. after #4581 ?

thanks

**Comment by KevinRansom** [comment]
@dsyme I would prefer a more deterministic solution than moving back to Assembly.LoadFrom especially in fsi.  But there is not really a good technical reason to keep the compiler on netstandard1.6

**Comment by brettfo** [comment]
Visual Studio doesn't yet support `netstandard2.0`; `1.6 is the highest we can do right now.

**Comment by dsyme** [comment]
> Visual Studio doesn't yet support netstandard2.0; `1.6 is the highest we can do right now.

@brettfo How do you mean - AFAIK it loads `netstandard2.0` DLLs if the correct facades are available?

> @dsyme I would prefer a more deterministic solution than moving back to Assembly.LoadFrom especially in fsi. 

Anything specific on how we can do better than LoadFrom? (given the constraints we have - e.g. TPDTC run in-process in VS).  I'm ok with doing it differently, but as things stand right now people will start to role their own resolution with .NET Core's ResolveAssembly event...

**Comment by KevinRansom** [comment]
The problem with LoadFrom is the statement  "So it can load dependencies which are in the directory that contains the DTPC."

The ResolvingEventon the LoadContext probably the most deterministic solution, and it would allow us to Log the bind and even inject a #r to the script text so that if a developer is surprised by the outcome it is diagnosable.

Kevin

**Comment by KevinRansom** [comment]
So … netstandard 2.0 support and VS is orthogonal.

We ship VS with a desktop build of FSharp.Compiler.Private.dll.  And that won’t change any time soon , @Brett Forsgren<mailto:Brett.Forsgren@microsoft.com> is correct that VS is still on 4.6 of the desktop, which doesn’t automagically support netstandard2.0 … What @Don Syme<mailto:Don.Syme@microsoft.com>is asking for is can we build the compiler with netstandard 2.0 and switch back to LoadFrom… and the answer to that is yes we could do that.

However… Roslyn uses an assembly resolve event to ensure that analyzers load dependencies that are alongside them.  They do this because Assembly.LoadFrom is too broad a resolution mechanism.  I believe there was an endless stream of weird bugs due to having the wrong version of types, missing methods, because the loadfrom cotext was horrifically polluted with types.

As for the C# compiler, I believe the dependencies  are explicitly passed by the build task, so no compile time resolution

Anyway … I am working on a build task that understands TP’s, Because the F# compiler can resolve dpdts independent of I will also ensure that we have a resolution mechanism that will have a deterministic probing mechanism for TPDTCs on both desktop we should be able to use the LoadContext events to handle it.

Does this help?

Kevin

**Comment by dsyme** [comment]
> Roslyn uses an assembly resolve event to ensure that analyzers load dependencies that are alongside them.

That would be ok by me. 

> we should be able to use the LoadContext events to handle it

Yes, that's ok too

**Comment by dsyme** [comment]
@KevinRansom BTW I would like a fix that at the very least loads neighbouring-file dependencies in the pipeline to be included the .NET SDK as soon as possible, as this is a bug in the TP support for .NET SDK.

If it's ok I'll draft a fix to get us that far - I think we should aim for that in 15.7.

**Comment by KevinRansom** [comment]
Yes 15.7 is what I had in mind.

**Comment by cartermp** [comment]
Now that we're converted to the .NET SDK, how relevant is this issue? Any easier?

**Comment by dsyme** [comment]
This has been fixed long ago as we now again use `UnsafeLoadFrom`
