### ISSUE TITLE
It's impossible to inspect a variable in the debugger

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#5048]
There is absolutely no way to inspect the value of `completionContext` variable in

https://github.com/Microsoft/visualfsharp/blob/0b940a46e2a527d16500ef4fdd0389b8bcc44f13/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L195-L205

Even adding additional vars like this:
```fsharp
 if results.Count > 0 && not declarations.IsForType && not declarations.IsError && List.isEmpty partialName.QualifyingIdents then 
     let lineStr = textLines.[caretLinePos.Line].ToString() 
      
     let completionContext = 
         parseResults.ParseTree  
         |> Option.bind (fun parseTree -> 
              UntypedParseImpl.TryGetCompletionContext(Pos.fromZ caretLinePos.Line caretLinePos.Character, parseTree, lineStr)) 
       
     let xx = completionContext 
     let _x = xx

     match completionContext with 
     | None -> results.AddRange(keywordCompletionItems) 
     | _ -> () 
```
does not help. I ended up logging the value with `Logging.Logging`.

**Comment by smoothdeveloper** [comment]
This is due to the code being in `asyncMaybe` CE.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper so nothing is supposed to work inside a CE?..

**Comment by dsyme** [comment]
That is supposed to work in `Debug`.  It would be good to get a minimal repro

**Comment by dsyme** [comment]
@vasily-kirichenko I think that @smoothdeveloper's comment is based on the fact that in CEs the implicit use of closure-capturing continuations might cause some variables to drop out of scope in subsequent (implicit) closures.  However the code above is a synchronous part of the CE.

**Comment by cartermp** [comment]
This no longer repros, at least not when I pull this out into a call outside the `if` block:

![image](https://user-images.githubusercontent.com/6309070/110717354-bc20cb80-81bd-11eb-859f-007f188121fc.png)

That said, if you try to set a breakpoint on the `if` block it will say it doesn't work:

![image](https://user-images.githubusercontent.com/6309070/110717377-c5aa3380-81bd-11eb-9dc3-b67a10005ec2.png)

But then it actually does bind:

![image](https://user-images.githubusercontent.com/6309070/110717491-06a24800-81be-11eb-8fc0-f19204c2a911.png)

Except you can't set a breakpoint inside of it:

![image](https://user-images.githubusercontent.com/6309070/110717522-1588fa80-81be-11eb-9910-447d4ed7f413.png)

And this time you actually cannot have a resolved breakpoint.

From that point onward, you cannot step over calls because it lands in the guts of async, and you can't get out, so in practice you still can't observe the value of `completionContext` _specifically in this block_.

There are most definitely two bugs here:

1. You cannot set breakpoints, or it says you can't but you actually can
2. Existing issues around stepping into/over calls inside of a computation expression

**Comment by cartermp** [comment]
Unfortunately I can't figure out a repro that doesn't involve trying to debug VisualFSharp.sln itself. When I try the latter, it ultimately StackOverflows because it's in debug mode and there's a lot to deal with...
