### ISSUE TITLE
Equality operator causes boxing on value types

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#526]
Comparing value types with the equality operator (=) causes unnecessary boxing to occur. Tested on Visual Studio 2015 RC. I described the issue in this [StackOverflow question](http://stackoverflow.com/a/31283508/154766).

Example:

```
[<Struct>]
type MyVal =
    val X : int
    new(x) = { X = x }

for i in 0 .. 10000000 do
      (MyVal(i) = MyVal(i + 1)) |> ignore;;
Real: 00:00:00.077, CPU: 00:00:00.078, GC gen0: 38, gen1: 1, gen2: 0
```

My totally uninformed guess here is that the type is casted to IEquatable<_> before the strongly typed Equals is then called.

But it gets worse! If custom equality is defined:

```
[<Struct;CustomEquality;NoComparison>]
type MyVal =
    val X : int
    new(x) = { X = x }
    override this.Equals(yobj) =
        match yobj with
        | :? MyVal as y -> y.X = this.X
        | _ -> false
    interface System.IEquatable<MyVal> with
        member this.Equals(other) =
            other.X = this.X

for i in 0 .. 10000000 do
      (MyVal(i) = MyVal(i + 1)) |> ignore;;
Real: 00:00:00.497, CPU: 00:00:00.500, GC gen0: 77, gen1: 1, gen2: 0
```

Then the equality operator calls `Equals(obj)`, boxing both operands in the process! Nevermind the casts then required. As you can see this results in roughly twice the amount of GC pressure.

Even for reference types, this is suboptimal because casts are required.

The only workaround this problem is systematically avoid use of this operator, which may not be feasible when using generic code in third-party F# libraries. I see no reason why the compiler shouldn't generate a direct call to `IEquatable<T>.Equals` without boxing or casts; a call that could then be properly inlined by the CLR in many cases.

**Comment by manofstick** [comment]
FYI I'm attacking some boxing issues in #513, but this case is still kind of an issue (your second example no longer causes boxing with that change applied). As I've been playing around in the equality space for a while, I don't think there is a particularly easy answer to this (i.e. one that doesn't change existing code functionality) although I do offer some possibilities at the end of this posting.

The reason is that their are three classes of equality; "PER", "ER" and "Other" (basically how to deal with floating point NaNs, as well as just any old equality to want to throw at it.)

IStructuralEquatable deals with any of these by the IEqualityComparer that is passed in.
IEquatable<'a> is hardcode using "ER"
obj.Equals defers to the IEquatable

The problem is that by default "=" does so with PER equality, and to change it would be a breaking change. So you can't just have any old struct deferring it's equality to the Equals method without checking all it's members.

Here is an example of the issue:

    let nan1 = Double.NaN
    let nan2 = Double.NaN

    System.Console.WriteLine (if nan1 = nan2 then "nan1 = nan2" else "nan1 <> nan2")
    System.Console.WriteLine (if nan1.Equals nan2 then "nan1 = nan2" else "nan1 <> nan2")

    let nan1 = { Value = Double.NaN }
    let nan2 = { Value = Double.NaN }

    System.Console.WriteLine (if nan1 = nan2 then "nan1 = nan2" else "nan1 <> nan2")
    System.Console.WriteLine (if nan1.Equals nan2 then "nan1 = nan2" else "nan1 <> nan2")

With the results

    nan1 <> nan2
    nan1 = nan2
    nan1 <> nan2
    nan1 = nan2

So anyway, I said that your second version now doesn't cause boxing, and this is because it doesn't implement IStructuralEquatable, so it doesn't have to worry about this ER/PER split, and it does have the IEquatable<'a> so that is used.

Anyway, a potential solution to solve this problem fully could be to recursively check a value type to ensure that it has not floating point numbers in it or subtypes; which is a bit dirty; or alternatively a better solution, although a bit bloaty, might be to create a new interface IEquatablePER<'a> and have the compiler generate those for value types (and records) and then defer to those. Now I'm not a Microsoft employee, or on any committee that makes such decisions, so I can't tell you if this is likely to be done.

**Comment by asik** [comment]
Or take the breaking change and fix the nan inconsistency... Having to box structs in simple equality comparisons is a high price to pay to maintain what is anyway a bug. You think you're saving on GC pressure and you're actually causing a ton more, this makes using structs almost useless.

**Comment by latkin** [comment]
@asik -- scenarios like this are exactly why the `NonStructuralComparison` operators were added in F# 4.0.

```fsharp
[<Struct>]
type MyVal =
    val X : int
    new(x) = { X = x }
    static member op_Equality(this : MyVal, other : MyVal) =
        this.X = other.X

module Default =
    let test () =
        for i in 0 .. 10000000 do
              (MyVal(i) = MyVal(i + 1)) |> ignore

module NonStructural =
    open NonStructuralComparison
    let test () =
        for i in 0 .. 10000000 do
              (MyVal(i) = MyVal(i + 1)) |> ignore

// Real: 00:00:00.089, CPU: 00:00:00.093, GC gen0: 29, gen1: 1, gen2: 0
Default.test()

// Real: 00:00:00.003, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
NonStructural.test()
```

That's not to say we should ignore potential perf improvements to the default operators, certainly not. But at least there is a fairly straightforward workaround available with 4.0.  You just need to define `op_Equality`, similar to how you need to implement `==` in C#.

**Comment by asik** [comment]
@latkin Good to know! I'll update my Stackoverflow answer with this information.
"open NonStructuralComparison" does have the unfortunate effect of disabling equality for DUs and Records across the module (the code ceases to compile). It's a workaround all right, but it doesn't seem to play nice with standard F# features.

**Comment by latkin** [comment]
Yes, simply opening `NonStructuralComparison` is a bit blunt. See [this convo](https://twitter.com/LincolnAtkinson/status/593592474838257664), and an approach for encapsulating `NonStructural` in dedicated operators [here](https://gist.github.com/latkin/361c59a7582e390167c7).

**Comment by manofstick** [comment]
@asik 

An alternative to NonStructuralComparison could be

    module EquatableModule =
        let inline eq<'a when 'a :> System.IEquatable<'a>> (x:'a) (y:'a) = x.Equals y
        let inline (==) x y = eq x y
        let inline (!=) x y = not (eq x y)

Which would mean you wouldn't need to implement op_Equality, rather just use the c#esq operators (not sure if that is a good choice or not! Name them what you will...)

**Comment by manofstick** [comment]
@asik 

Oh, and you're still going to run into lots of trouble using value types anyway. Using them as keys to containers, embedding them in other objects, in the 64-bit JIT when they are greater than 64-bits and used as parameters in a function that uses the "tail" IL instruction (this is due to calling conversion rules), using things like List.find on a list of structs...

#513 resolves many of these issues, but they should still be used knowing that there are potential pitfalls all over the shop...

**Comment by asik** [comment]
@manofstick Looks like your (==) does the right thing for everything that's structurally equatable (records, DUs) as well as for structs. Might as well rename it (=), ignoring the compiler complaints, <AutoOpen> it as the first module in your project and use it everywhere? After that it's perhaps just a matter of avoiding library functions that use the default (=), like using List.exists rather than List.contains.

**Comment by manofstick** [comment]
@asik,

Will I wouldn't really recommend it, but each to their own; and whoever has to support the code in the future! As overriding = would mean that they couldn't use it for structural equality on containers, including arrays. Plus the subtle change of meaning for floating point numbers doesn't help.

And most of the time the performance just doesn't matter. I agree that when it does, it certainly does, but that can just be profiler guided.

Anyway, this is really a stackoverflow discussion, rather than an issue here. So I will end it here.

**Comment by asik** [comment]
I disagree that this should resolved as by design. This is surprising behavior and a performance trap. It affects all library code that uses this operator or structural equality, like Array.contains, Array.except, Array.distinct (and the same in Seq, List); causing N allocations for an input of size N is not a small performance problem, especially for larger value types (for ex. a 4x4 matrix of floats). There is no way to know which functions to avoid except through benchmarking. This reduces F#'s appeal in low-latency or high performance applications.

**Comment by dsyme** [comment]
OK, reopening. As mentioned above much of the impact is reduced by the combination of #513 and the dilegent use of NonStructuralComparison.

**Comment by OnurGumus** [comment]
I have encountered this issue while making some research on F# equality. To me, this is surprisingly frightening. Any love for this?

**Comment by asik** [comment]
I'm getting the same performance numbers on the current Visual F# 2017 nightly.
This has also become more relevant with struct tuples, struct records and struct DUs.

```
for i in 0 .. 10000000 do
      (struct(i, i) = struct(i + 1, i + 1)) |> ignore;;
Real: 00:00:01.367, CPU: 00:00:01.375, GC gen0: 107, gen1: 107, gen2: 0
```

**Comment by manofstick** [comment]
@OnurGumus

The Phoenix of #513 will rise again at some stage, but i have been on a bit of a round about adventure which sees me currently in #2587

Although I do see that @dsyme had given this the "urgency soon" and "bug" labels; so maybe they have some alternative thoughts on this?

**Comment by OnurGumus** [comment]
I think the correct solution here is to define a new equals operator dedicated to structs. And compiler should give a  warning for the old usage. This way nothing breaks and people can gradually fix their code.

**Comment by OnurGumus** [comment]
Here's a script file demonstrating the problem for List.contains

```
[<Struct>]
type MyVal =
    val X : int
    new(x) = { X = x } 

let s = [for i in 0 .. 1000000 do
            yield MyVal(i)]

System.GC.Collect()
#time

for i in 0 .. 10000000 do
    List.contains (MyVal(4)) s |> ignore
```

and the output is:
```--> Timing now on

Real: 00:00:01.259, CPU: 00:00:01.250, GC gen0: 572, gen1: 0, gen2: 0
val it : unit = ()```

And none of the above fixed will prevent this problem.

**Comment by manofstick** [comment]
@onurgumus

It's not quite that simple. Internally in library functions such as groupBy or the list element comparisons or tuples etc. what you have suggested just doesn't work. This was the reason why #513 existed.

**Comment by OnurGumus** [comment]
@manofstick Sorry but I fail to see how #513 is relevant to this issue at all. Correct me if I am wrong but #513 is about an optimization regarding value types with generic type parameters. Here we don't have that. 

Finally  I don't get why it is not simple to fix the below code for List.contains in F# Core:

```
 [<CompiledName("Contains")>]

        let inline contains e list1 =

            let rec contains e xs1 =

                match xs1 with

                | [] -> false

                | h1::t1 -> e = h1 || contains e t1

            contains e list1
```

There is a single e = h1 expression leading to boxing. We just need to get rid of it with a proper equality checking.

**Comment by manofstick** [comment]
@onurgumus

Short answer: you'll just have to believe me!

Longer answer: there are more complex rules around how f# handles equality than straight IEquatable and they have to be honoured.

**Comment by OnurGumus** [comment]
@manofstick, And is there a longer answer ? 😄

**Comment by OnurGumus** [comment]
Similarly the comparison only considers IComparable and not IComparable<'T> causes boxing as in below code:
```
[<Struct; CustomComparison; CustomEquality>]
type MyVal  =
    val X : int
    new(x) = { X = x }

    override this.Equals other = 
        match other with
        | :? MyVal as y -> this.Equals y
        | _ -> false

    override this.GetHashCode() = this.X

    member this.CompareTo (other:MyVal) = this.X.CompareTo(other.X)
    member this.Equals (other:MyVal) = other.X = this.X
    with 
        interface System.IComparable with
           member this.CompareTo other =
             match other with
             | :? MyVal as y -> this.CompareTo y
             | _ -> failwith "not comparable"

        interface System.IComparable<MyVal> with
            member this.CompareTo other = failwith "never comes to here"

        interface System.IEquatable<MyVal> with
            member this.Equals other =  failwith "never comes to here"

let s =[for i in 0 .. 1000 do
            yield MyVal(i)]

System.GC.Collect()
#time

for i in 0 .. 1000 do
    List.filter (fun item -> item > (MyVal(4))) s |> ignore
```
with the output:
```
--> Timing now on

Real: 00:00:00.133, CPU: 00:00:00.140, GC gen0: 19, gen1: 2, gen2: 1
```

So much for the struct performance in F#!

**Comment by manofstick** [comment]
@OnurGumus 

Yes, #513 looked after IComparables as well.

OK, the problem is that f# views equality/comparison as structural, which means that things  

    let a = [ for i = 0 to 9  do yield i + 1 ]
    let b = [ for i = 2 to 11 do yield i - 1 ]
    
    if not (obj.ReferenceEquals (a, b)) then  printfn "nothing up my sleeve!"
    if a = b then printfn "equality for all!"

work. Or on generic record types that you create:

    type X<'a> = {
        A : 'a 
    }

    let a = { A = 1 }
    let b = { A = 1 }

    if not (obj.ReferenceEquals (a, b)) then  printfn "nothing up my sleeve!"
    if a = b then printfn "equality for all!"

But the point is that in library code you are not aware of *what* types are going to be passed. i.e. you mightn't have a type which supports equality stored within an array. Or it's rules are different from normal equality - such as the way that arrays are handled.

Anyway. As I have said about half a dozen times, that is what #513 was for. It needs to be fixed - and needs confirmation from #dsyme that it will be accepted; it does dynamically create types which is not compatible with .net native, which may be a showstopper. But, I'm currently busy. I hope to get back to it at some stage in the not too distant future. If you want to help, then help me finish #2587 so that I can get back to this. Thanks.

**Comment by manofstick** [comment]
#5307 affects this (sprinkling breadcrumbs...)

**Comment by christian-clausen** [comment]
We just experienced this issue using a Dictionary with Guid keys. 630 MB of Guids were allocated in our scenario. We are now reviewing our code for uses of '=' on structs in general. A compiler warning to find such usages would be greatly appreciated.

**Comment by manofstick** [comment]
@christian-clausen 

It is a shame. It's not just `=` though, it's usage through containers, to members in records - especially then you have to consider generics. It's quite nasty. So making a warning would be difficult (impossible?) to cover all usages; so would it really be a good warning? (Maybe some code analyser could at least offer *some* hints, albeit in a limited form)

I've [tried](https://github.com/dotnet/fsharp/pull/513), and [tried](https://github.com/dotnet/fsharp/pull/9404) to get something suitable to fix this but I just didn't get into the fsharp early enough in it's lifecycle, and now any change is going to be a breaking one - it appears that it's unacceptable to prefer `IEquatable<>.Equals(...)` over `object.Equals(...)` and technically this is a breaking change. But sad.

Anyway, it has lost me as an fsharp developer, which is a shame as I really love writing code in fsharp, but with advancements in csharp over the years, it's, for the type of code I write, a lesser worse option. (I mean most people probably just don't care about performance at this level, so it's mostly a non-issue, which is why it's never found enough traction to solve, and I understand that. But does make me sad.)

**Comment by manofstick** [comment]
...as a caveat, adding Guids is probably reasonable and sensible (been a long time since I delved into the code, but I thought they already did, but obviously not from your discovery), as they can guarantee Equality there. But I extensively use NodaTime (as anyone who write multi-timezone code should!), which mainly has value types, and they can't obviously extend out handling to arbitrary libraries.

**Comment by bent-rasmussen** [comment]
Having analyzers for a trap like this would be great. One mitigation we are trying is to annotate all (many) structs with [<NoEquality; NoComparison>] as well as a custom IEquatable<_> implementation (and ignore the warning - and hope that mechanism doesn't get forbidden) and then use the '==' operator as defined above to ensure IEquatable<_>.Equals is used to avoid boxing. Structs from external libraries is a different situation. IL-rewriting?

**Comment by bent-rasmussen** [comment]
@En3Tho The only reason for adding `[<NoEquality; NoComparison>]` was to get compiler errors so as to know what code to fix to use '==', as there is no compiler, analyzer or analyzer tooling for VS proper to find these cases otherwise. Using these attributes unfortunately but understandably removes the default `IEquatable<_>` implementation though, and so you have to reimplement manually - and for all types wrapping these types as well. A more sensible approach is perhaps to put all `[<NoEquality; NoComparison>]` declarations inside a conditional compilation directives which can be switched on for checking purposes.

**Comment by OnurGumus** [comment]
Again I am checking this and the following code is significantly superior to builtin implementation
```fsharp
open System.Collections.Generic

[<Struct; CustomComparison; CustomEquality>]
type MyVal  =
    val X : int
    new(x) = { X = x }

    override this.Equals other = 
        match other with
        | :? MyVal as y -> this.Equals y
        | _ -> false

    override this.GetHashCode() = this.X

    member this.CompareTo (other:MyVal) = this.X.CompareTo(other.X)
    member this.Equals (other:MyVal) = other.X = this.X
    with 
        interface System.IComparable with
           member this.CompareTo other =
             match other with
             | :? MyVal as y -> this.CompareTo y
             | _ -> failwith "not comparable"

        interface System.IComparable<MyVal> with
            member this.CompareTo other = failwith "never comes to here"

        interface System.IEquatable<MyVal> with
            member this.Equals other =  other.X = this.X
            
let comp = EqualityComparer<MyVal>.Default;
let inline contains e list1 =

            let rec contains e xs1 =

                match xs1 with

                | [] -> false

                | h1::t1 -> comp.Equals(h1,e)|| contains e t1

            contains e list1

let count = 5000
let s = [for i in 0 .. count do
            yield MyVal(i)]

System.GC.Collect()
#time

for i in 0 .. count do
    List.contains (MyVal(4999)) s |> ignore
#time
printf "done"
```
Despite many years passed, no progress even not a single explanation F# uses = operator for structs instead of  EqualityComparer<T>.Default;

**Comment by ShalokShalom** [comment]
When implementing a new operator, or using EqualityComparer.Default, a warning when using `=` is definitely appropriate. 

People will use `=` in a lot of cases, because it is the most natural choice. 

_So, is there ANY possibility, that the equals sign becomes performant in this case?_

Cause, without that, there is no reason why we couldnt implement the warning right now. 
That would be appropriate then, regardless of how we success besides that.

**Comment by gdar91** [comment]
Reducing unnecessary allocations is one critical cornerstone of runtime performance. I can't imagine a functional-first programming language having these kinds of issues sitting unresolved for years. It can't be "inefficient by design". And if it was, then it's time to rethink this.
Of course, overriding and shadowing the default inefficient versions will help, but it will only do on a surface, where you have control. But you can't do this to a library code. You don't have to go far and give examples like list comparison, etc... Just take a nested type structure. When you call your version of equals on it, it will not box that type, but when that equality comparison goes down the sub-properties, it will still use the default inefficient comparer.

**Comment by En3Tho** [comment]
@gdar91 nested equality doesn't use "=" operator and doesn't use generic equality. Compiler does a good job generating good .Equals code. If you know cases where it doesn't then share your examples please.

**Comment by En3Tho** [comment]
@gdar91 thanks. Afaik it is not the case with records but seeing your example I think I need to recheck it.

**Comment by gdar91** [comment]
This boxing thing is also a big problem when AOT compiling your code (for Xamarin, iOS, etc...). The thing is as JITting is not supported on platforms like iOS the linker must generate all possible generic instantiations that might be used at runtime - at compile time. And sometimes it can miss some vague cases, so you need to add a dummy code somewhere else, that uses those generic instantiations explicitly.
When we use equality methods without generic instantiations that makes it more probable for a linker to miss those instantiations and cause crashes and misbehavior at runtime.
I had the exact same problem with the ValueOption<T> type and solved it by adding some dummy code.

**Comment by Happypig375** [comment]
Maintaining backcompat here for some unknown tiny amount of people, versus making most F# projects run better.
Preferring the first one is actively making F# worse.

https://github.com/dotnet/fsharp/issues/526#issuecomment-1045552667
> Anyway, it has lost me as an fsharp developer, which is a shame as I really love writing code in fsharp, but with advancements in csharp over the years, it's, for the type of code I write, a lesser worse option

We should consider a feature switch, something like `<FastFSharp>true</FastFSharp>` that switches implementations of FSharp.Core functions for performant but breaking alternatives, with unknown tiny amount of people actually affected by the break that you can't even list a known example of someone depending on this behaviour.

**Comment by Happypig375** [comment]
addendum: an alternative is FSharp.Core adding `net9.0` as a new target framework and switch to new implementations there.

**Comment by vzarytovskii** [comment]
Probably worth just fixing it with the way to rollback to earlier behaviour (new module with backcompat?).

**Comment by hyazinthh** [comment]
I've run into this issue (again) recently and tried to circumvent it by using integers directly (my struct was a simple wrapper around an integer). However, this did not improve anything to my suprise. It turns out the F# equality also leads to boxing when used in non-inlined generic code with primitive data types such as `int32`:

```fsharp
let genericFSharpEquality (value : 'T) (data : 'T[]) =
    let mutable found = 0

    for i = 0 to data.Length - 1 do
        if data.[i] = value then
            found <- found + 1

    found

let genericEqualityComparer (value : 'T) (data : 'T[]) =
    let cmp = EqualityComparer<'T>.Default
    let mutable found = 0

    for i = 0 to data.Length - 1 do
        if cmp.Equals(data.[i], value) then
            found <- found + 1

    found
```

|           Method |  Count |        Mean |      Error |    StdDev |      Gen0 | Allocated |
|----------------- |------- |------------:|-----------:|----------:|----------:|----------:|
|   FSharpEquality | 100000 | 3,151.67 us | 384.587 us | 21.080 us | 1527.3438 | 4800012 B |
| EqualityComparer | 100000 |    66.21 us |   0.918 us |  0.050 us |         - |         - |

This is absolutely horrifying.

**Comment by OnurGumus** [comment]
> addendum: an alternative is FSharp.Core adding `net9.0` as a new target framework and switch to new implementations there.

6 years ago me:
```
I think the correct solution here is to define a new equals operator dedicated to structs. And compiler should give a warning for the old usage. This way nothing breaks and people can gradually fix their code

And yes, the code for FSharp.Core also has to change for the things like List.contains which also would do boxing by default for user defined value types.
```

**Comment by brianrourkeboll** [comment]
@hyazinthh

> I've run into this issue (again) recently and tried to circumvent it by using integers directly (my struct was a simple wrapper around an integer). However, this did not improve anything to my suprise. It turns out the F# equality also leads to boxing when used in non-inlined generic code with primitive data types such as `int32`

...That is pretty surprising. Kind of funny that it actually _does_ do what you would expect when it's a local function instead of a module-bound function—sometimes.

E.g., the following

```fsharp
let f () =
    let genericFSharpEquality (value : 'T) (data : 'T[]) =
        let mutable found = 0

        for i = 0 to data.Length - 1 do
            if data.[i] = value then
                found <- found + 1

        found

    let _ = genericFSharpEquality 1 [|1..1_000_000|]
    ()
```

[gives](https://sharplab.io/#v2:DYLgZgzgPsCmAuACMiAUBKRBeAsAKEUMTiQHNYA7WAJwEsBjAMQGUALAQ2oAcBRARwCu7YLXgBPNADdhA2IhCIA5ABVMqACbt47eUuUBtALqZcBIuZKIAtgO0AjOMgD2AiuuyIADPnznzYJ2pEWg9PRHgnRE1tADoAGUpSeFZEAFpEAEYop18/PNoUaPYY/VpDD2lgWXDWSly8hudXdwAedIDmxABqTJ8zPI63PosERAB9D3IqOiY2Tl5BYVEJLP0oDJiYjLHPXZ3dqEN6tHQgA=)

```csharp
using System.Reflection;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;

[assembly: FSharpInterfaceDataVersion(2, 0, 0)]
[assembly: AssemblyVersion("0.0.0.0")]

[CompilationMapping(SourceConstructFlags.Module)]
public static class @_
{
    public static void f()
    {
        int[] array = SeqModule.ToArray(Operators.CreateSequence(Operators.OperatorIntrinsics.RangeInt32(1, 1, 1000000)));
        int num = 0;
        int num2 = 0;
        while (num2 < array.Length)
        {
            if (array[num2] == 1)
            {
                num++;
            }
            num2++;
        }
    }
}

namespace <StartupCode$_>
{
    internal static class $_
    {
    }
}
```

while this—which _looks_ like it should be _identical_

```fsharp
let f () =
    let genericFSharpEquality (value : 'T) (data : 'T[]) =
        let mutable found = 0

        for i = 0 to data.Length - 1 do
            if data.[i] = value then
                found <- found + 1

        found

    ignore (genericFSharpEquality 1 [|1..1_000_000|])
```

[gives](https://sharplab.io/#v2:DYLgZgzgPsCmAuACMiAUBKRBeAsAKEUMTiQHNYA7WAJwEsBjAMQGUALAQ2oAcBRARwCu7YLXgBPNADdhA2IhCIA5ABVMqACbt47eUuUBtALqZcBIuZKIAtgO0AjOMgD2AiuuyIADPnznzYJ2pEWg9PRHgnRE1tADoAGUpSeFZEAFpEAEYop18/PNoUaPYY/VpDD2lgWXDWSly8hudXdwAedIDmxABqTJ8zPI63PvNaUgpAuVRyKjomNk5eQWFRCSz9KAyYmIyAfU99vf2oYyA===)

```csharp
using System.Reflection;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;

[assembly: FSharpInterfaceDataVersion(2, 0, 0)]
[assembly: AssemblyVersion("0.0.0.0")]

[CompilationMapping(SourceConstructFlags.Module)]
public static class @_
{
    internal static int genericFSharpEquality@2<T>(T value, T[] data)
    {
        int num = 0;
        int num2 = 0;
        while (num2 < data.Length)
        {
            T x = data[num2];
            if (LanguagePrimitives.HashCompare.GenericEqualityIntrinsic(x, value))
            {
                num++;
            }
            num2++;
        }
        return num;
    }

    public static void f()
    {
        int num = genericFSharpEquality@2(1, SeqModule.ToArray(Operators.CreateSequence(Operators.OperatorIntrinsics.RangeInt32(1, 1, 1000000))));
    }
}

namespace <StartupCode$_>
{
    internal static class $_
    {
    }
}
```

It is kind of crazy that such a super-subtle, semantically-indistinguishable difference in source code could invisibly have such a massive effect on perf. I just tried it out locally and the one with `let _ = … ()` is at least ~5–10× as fast as the one with `ignore …`.

**Comment by vzarytovskii** [comment]
Main issue with that is still a backwards compatibility and we don't exactly know how to solve it and don't have approval from @dsyme for an opt-out approach.

**Comment by dsyme** [comment]
I'm not sure how widespread knowledge is of `open NonStructuralComparison`.  This switches all the core operators to use `op_Equality` static member overloads etc. and is a great way of finding many places in your code you are relying on structural equality.  You can then make uses of structural equality explicit using `===` or some other self-defined operators

This approach doesn't solve the issue generally:
- requires the definition of the C#-style operator methods manually,
- doesn't allow structural comparison on lists, tuples etc. that recursively do operator-constrained comparison on leaf types.  
- doesn't redefine FSharp.Core primitives that implicitly do structural comparison (List.contains etc.) , though in theory it could.

Despite that it can certainly help root out problems and I think deserves to be much better known

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-operators-nonstructuralcomparison.html

**Comment by dsyme** [comment]
@brianrourkeboll It looks to me the huge difference you notice is really due to something else: the reduction of the integer sequence to a fast for-loop is not occurring in the first example.  This has the flow on effect of boxing in equality - but solving the second problem wouldn't solve the first problem for this particular example.

I think (not sure, it's been a while) this is because this particular "optimization"  is done during type checking, and full type information is not known to allow it to proceed.  I believe (not sure) that this can be "fixed" by also doing the reduction doing optimization if necessary (it still has to be done in type checking as well because the optimization is visible in quotations, when it applies).

**Comment by brianrourkeboll** [comment]
@dsyme

> @brianrourkeboll It looks to me the huge difference you notice is really due to something else: the reduction of the integer sequence to a fast for-loop is not occurring in the first example.

Hmm, I'm not sure I follow. The `for i = 0 to data.Length - 1 do` seems to be translated to a (fast) `while` loop for both. To remove the (slow) array initialization from the comparison:

```fsharp
#time "on"

let fast (xs : int array) =
    let genericFSharpEquality (value : 'T) (data : 'T[]) =
        let mutable found = 0

        for i = 0 to data.Length - 1 do
            if data.[i] = value then
                found <- found + 1

        found

    let _ = genericFSharpEquality 1 xs
    ()

let slow (xs : int array) =
    let genericFSharpEquality (value : 'T) (data : 'T[]) =
        let mutable found = 0

        for i = 0 to data.Length - 1 do
            if data.[i] = value then
                found <- found + 1

        found

    ignore (genericFSharpEquality 1 xs)

let xs = [|1..1_000_000|]
```

then:

```fsharp
fast xs // Real: 00:00:00.002, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
```

```fsharp
slow xs // Real: 00:00:00.024, CPU: 00:00:00.015, GC gen0: 0, gen1: 0, gen2: 0
```

**Comment by dsyme** [comment]
@brianrourkeboll You're correct, my bad.

**Comment by dsyme** [comment]
I see.  The difference is that `genericFSharpEquality` has been inlined (and thus type-specialized) in one and not the other.   I believe the inlining has happened because it the first has an "immediate" use of `genericFSharpEquality`.   That said there's no real reason why the second couldn't also do the inlining given it's the only use of the local generic function.


Anyway, when it occurs this kind of inline+type-specialization is indeed a **huge** performance gain and can transform expensive generic equality calls to very inexpensive integer comparisons.  

No matter how generic equality is implemented you tend to get this kind of thing.  That said, it may be possible to make dramatic improvements to the generic equality non-inlined implementation, e.g.
* type-specializing it for integer types. 
* type-specializing it for floating-point types. 
* type-specializing it for tuple, list and array types. 

By type specializing I mean something like `if typeof<T>.Equals(typeof<int>) then ...`.  IIRC some variation on this is now statically reduced in .NET code  as the JIT specializes generic code - at least  my understanding is .NET Core now has many techniques now for declaring type specializations within implementations and it may be worth looking at using these within `LanguagePrimitives.HashCompare.GenericEqualityIntrinsic`

Again this doesn't fully address the boxing problem by any means.

**Comment by asik** [comment]
Could the optimizer be made smart enough to look at struct types recursively and inline the comparison if it doesn't contain any members that require structural comparison? That would at least solve the problem in many common cases, with e.g. Matrix and Vector types in game engines.

**Comment by ScottArbeit** [comment]
Issue mentioned in [F# developer stories: how we’ve finally fixed a 9-year-old performance issue](https://devblogs.microsoft.com/dotnet/fsharp-developer-stories-how-weve-finally-fixed-a-9yearold-performance-issue/).

**Comment by gdar91** [comment]
Boxing still happens in some cases. Take this code snippet for example, when a record is generic and it's takes type of another struct record/union:

```
open System.Runtime.CompilerServices

type [<IsReadOnly; Struct>] MyRecord<'a> =
    { MyString: string;
      MyInt: int
      A: 'a }

type [<IsReadOnly; Struct>] MyNestedRecord =
    { MyNestedValue: int }

let test =
    let record1 = { MyString = "MyString 1"; MyInt = 10; A = { MyNestedValue = 10 } }
    let record2 = { MyString = "MyString 2"; MyInt = 10; A = { MyNestedValue = 10 } }
    let mutable i = 0
    let mutable result = 0
    while i < 1000000000 do
        let record = { MyString = "MyString 1"; MyInt = 10; A = { MyNestedValue = 10 } }
        let result1 = if record = record1 then 1 else 0
        let result2 = if record = record2 then 1 else 0
        result <- result + result1 + result2
        i <- i + 1
    result

let result = test

printfn $"Result: %d{result}"

```

When comparing, it will still box the nested `MyNestedRecord` structs (but not the top-level one).

**Comment by chtenb** [comment]
@gdar91 I think that warrants a new issue
