### ISSUE TITLE
Expose F# concepts in a more visible/interopable way

### ISSUE THREAD

**Issue by tannergooding** [dotnet/fsharp#5287]
Today, there are several F# concepts (such as the `unmanaged` constraint) which do not get encoded in CLR metadata. Instead, they are encoded as a resource blob that the F# compiler knows to look for.

In order to promote better cross-language support, I propose that F# additionally expose these concepts via CLR metadata (likely via attributes or `modreq`).

In the cases where the concept directly matches a corresponding concept (with the same rules/semantics/etc) exposed by another language (such as `C#`), it would be ideal if F# represented their metadata in the same way.

The compiler would ideally also be updated to look for this metadata if the resource blob did not exist.

Not only would this allow other languages to consume F# features more easily, but it would allow libraries to express any additional language specific concepts to F# even if it was authored in a different language.

**Comment by tannergooding** [comment]
FYI. @TIHan

**Comment by TIHan** [comment]
This is interesting.

I would definitely make this same post here: https://github.com/fsharp/fslang-suggestions

All F# suggestions need to go there.

**Comment by 7sharp9** [comment]
Problem is this would probably require adjustments to other languages and
their tooling, it would be common to see code such as `if lang == "fsharp"
then return null` in some C# addins etc :-)

Do you know off hand which F# features exist as metadata variants in other
languages?

**Comment by tannergooding** [comment]
> Problem is this would probably require adjustments to other languages and
their tooling, it would be common to see code such as `if lang == "fsharp"
then return null` in some C# addins etc :-)

Yes, much in the same way the F# has to update in order to support interop with new/existing C# language features (such as those that require `modreq`, etc).

> Do you know off hand which F# features exist as metadata variants in other
languages?

Working on compiling a list.

**Comment by tannergooding** [comment]
> I would definitely make this same post here: https://github.com/fsharp/fslang-suggestions

Talked with @TIHan, turns out that even features that don't touch the language need to be logged there. Will update after I get a list together...

**Comment by cartermp** [comment]
Also cc @alfonsogarciacaro since I don't think off-hand that this would be an issue since Fable is an AST -> AST compiler, but I honestly don't know if this sort of thing would impact it.

**Comment by alfonsogarciacaro** [comment]
As long as the typed AST remains the same this shouldn't affect Fable (adding extra metadata as attributes shouldn't be a problem either, removing certain attributes on the other hand could be). We don't enter in the IL generation phase :)

**Comment by zpodlovics** [comment]
@tannergooding The F# unmanaged constraint is a bit different than C# blittable constraint (this was the original name). Please see the details here: https://github.com/fsharp/fslang-suggestions/issues/493

**Comment by zpodlovics** [comment]
@tannergooding Why not expose the language metadata as an api similar to language service for IDEs? Standardized binary metadata will have the same problem as binary serialization - the language will not able to evolve (change the representation or interpretation) because the representation and the interpretation is now fixed and cannot be changed for compatibility reasons. How the metadata representation and interpretation evolution supposed to work? Each language creator will have a vote how things should be represented and interpreted ? I am not against the standardization for the common and well established things for easier interoperability, but these should be used as secondary metadata (so the primary metadata could be evolved independently of other language metadata representation and interpretation), otherwise unique language features will not be possible in the future.

Java binary serialization "experience":
"[Serialization] was a horrible mistake in 1997," he said. "Some of us tried to fight it, but it went in, and there it is. ...We like to call serialization 'the gift that keeps on giving,' and the type of gift it keeps on giving is security vulnerabilities.... Probably a third of all Java vulnerabilities have involved serialization; it could be over half. It is an astonishingly fecund source of vulnerabilities, not to mention instabilities."

**Comment by TIHan** [comment]
Seems we are having the discussion here then.

In general, I agree of what's asked here; though, we need some concrete examples of exactly which bits of metadata are interesting to us, such as `unmanaged`.

@zpodlovics what are the differences for `unmanaged` in C# and F#? Based on what I was reading, F# doesn't consider a generic struct `unmanaged` in any circumstance. In C#, it's not documented, but when I tested it out, it doesn't allow a generic struct to conform to the `unmanaged` constraint.

**Comment by zpodlovics** [comment]
From C# blittable/unmanaged wiki page (https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/blittable.md)

"The language will introduce a new constraint named unmanaged. In order to satisfy this constraint a type must be a struct and all the fields of the type must fall into one of the following categories:

Have the type sbyte, byte, short, ushort, int, uint, long, ulong, char, float, double, decimal, bool, IntPtr or UIntPtr.
Be any enum type.
**Be a pointer type.**
Be a user defined struct that satsifies the unmanaged constraint.
"

There are no typed (from metadata point of view - I guess it will also the jit/aot will generate different code with this domain knowledge) pointers available in F# for example: sbyte*, byte*, short*, ushort*, int*, uint*, long*, ulong*, char*, float*, double*, decimal*, bool* and void* only native int with some F# "magic". Typed pointer definitions are avaialable as ```ilsigptr<'T>``` but I guess it's only used internally. As a result of this, it's not possible to create the same struct / method signature both in C# and F# if typed pointers involved (at least I did not yet found out the way to do it). I would be surprised if these different representation will be considered equalivalent (generics specialization, overloading, etc) by the runtime/jit/aot and will generate the same code.

What would be the matching concept of a C# fixed size buffer struct field (the backing code is generated by the C# compiler) of an unmanaged type in F# ?

Also even if structs are created with sequential layout by default, the layout packing attribute is not 1 but 0 by default so every platform could have different representation. As a result of this it will not safe for interop between different platforms or native due the missing pack=1 attribute check.

My original blittable constraint proposal and it have different goal - supporting types (including generics) that have the same native representation. https://github.com/fsharp/fslang-suggestions/issues/493

**Comment by TIHan** [comment]
Ok, I'm trying to understand what you are saying.

It seems F# doesn't emit, sbyte*, byte*, etc, pointers when making a field with type `nativeptr<_>`. Meaning, `nativeptr<byte>` will not compile as `byte*` for a field, but will compile as `IntPtr`. However in method, it will be a `byte*`. For interop scenarios, I can understand how that can be troublesome. But, F#'s unmanaged constraint does take into account `byte*`, `sbyte*`, etc when it was defined in C#, meaning it considers it unmanaged.

> What would be the matching concept of a C# fixed size buffer struct field (the backing code is generated by the C# compiler) of an unmanaged type in F# ?

I just tested it and it seems to work. F# treats it as unmanaged. If we want to make fixed sized structs in F#, we need to make a fslang suggestion.

> Also even if structs are created with sequential layout by default, the layout packing attribute is not 1 but 0 by default so every platform could have different representation. As a result of this it will not safe for interop between different platforms or native due the missing pack=1 attribute check.

What does this have to do with the unmanaged constraint?

**Comment by TIHan** [comment]
Perhaps this issue is way to general. Here we are talking about the `unmanaged` constraint, but the original issue wants to focus on more than that. I'll leave it be for now, but we may end up creating separate issues, For those issues, I strongly suggest they go in https://github.com/fsharp/fslang-suggestions because it might require extending or adding features to F# in order to make interop work.

**Comment by zpodlovics** [comment]
Interop - by definition - means not only consuming C# parts from F# but also consuming F# parts from C#. Before the Span implementation (which is still not yet available for .NET Core 2.1.x) expressing the void* type was not even possible. I would be happy to have a better interop story for F#! The pack=1 note was a warning to other developers in case somebody walk into this trap(assuming unmanaged=blittable).

A bit off topic, but still important. There are some things that is possible in C# but not yet possible in F#. at least not without creating a mutable local variable as a copy of value type data. Please note the example method argument is not passed as byref<'T> or nativeptr<'T>. The C# compiler generate ```ldarga``` to load the method argument address on the stack.

```csharp

        public unsafe static byte[] ComputeHash<T>(T data) where T : unmanaged
        {
            byte* bytes = (byte*)(&data);
            using (var sha1 = SHA1.Create())
            {
                var size = sizeof(T);
                using (var ms = new UnmanagedMemoryStream(bytes, size))
                {
                    return sha1.ComputeHash(ms);
                }
            }
        }
```

Compiled IL:

```
  .method public hidebysig static uint8[] 
          ComputeHash<valuetype .ctor (class [System.Runtime]System.ValueType modreq([System.Runtime.InteropServices]System.Runtime.InteropServices.UnmanagedType)) T>(!!T data) cil managed
  {
    .param type T 
    .custom instance void System.Runtime.CompilerServices.IsUnmanagedAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       60 (0x3c)
    .maxstack  2
    .locals init (uint8* V_0,
             class [System.Security.Cryptography.Algorithms]System.Security.Cryptography.SHA1 V_1,
             int32 V_2,
             class [System.Runtime.InteropServices]System.IO.UnmanagedMemoryStream V_3,
             uint8[] V_4)
    IL_0000:  ldarga.s   data
    IL_0002:  conv.u
    IL_0003:  stloc.0
    IL_0004:  call       class [System.Security.Cryptography.Algorithms]System.Security.Cryptography.SHA1 [System.Security.Cryptography.Algorithms]System.Security.Cryptography.SHA1::Create()
    IL_0009:  stloc.1
    .try
    {
      IL_000a:  sizeof     !!T
      IL_0010:  stloc.2
      IL_0011:  ldloc.0
      IL_0012:  ldloc.2
      IL_0013:  conv.i8
      IL_0014:  newobj     instance void [System.Runtime.InteropServices]System.IO.UnmanagedMemoryStream::.ctor(uint8*,
                                                                                                                int64)
      IL_0019:  stloc.3
      .try
      {
        IL_001a:  ldloc.1
        IL_001b:  ldloc.3
        IL_001c:  callvirt   instance uint8[] [System.Security.Cryptography.Primitives]System.Security.Cryptography.HashAlgorithm::ComputeHash(class [System.Runtime]System.IO.Stream)
        IL_0021:  stloc.s    V_4
        IL_0023:  leave.s    IL_0039

      }  // end .try
      finally
      {
        IL_0025:  ldloc.3
        IL_0026:  brfalse.s  IL_002e

        IL_0028:  ldloc.3
        IL_0029:  callvirt   instance void [System.Runtime]System.IDisposable::Dispose()
        IL_002e:  endfinally
      }  // end handler
    }  // end .try
    finally
    {
      IL_002f:  ldloc.1
      IL_0030:  brfalse.s  IL_0038

      IL_0032:  ldloc.1
      IL_0033:  callvirt   instance void [System.Runtime]System.IDisposable::Dispose()
      IL_0038:  endfinally
    }  // end handler
    IL_0039:  ldloc.s    V_4
    IL_003b:  ret
  } // end of method Program::ComputeHash
```

**Comment by dsyme** [comment]
This needs to be at https://github.com/fsharp/fslang-suggestions/

It's absolutely good to get alignment with CLR constraints where possible but it's hard to do post-hoc
