### ISSUE TITLE
VS2017 doesn't handle snake_case identifiers correctly

### ISSUE THREAD

**Issue by jdh30** [dotnet/fsharp#5444]
Intellisense no longer recognises identifiers in snake case correctly.

#### Repro steps

Fresh F# solution containing just:

    let new_foo = 3

    new_foo

Put the cursor in any of the first five caret positions in "new_foo" and hit CTRL+j to get incorrect suggestions from Intellisense.

#### Expected behavior

Value F# identifiers should be identified correctly by Intellisense so the suggestion should be for the `new_foo` variable.

#### Actual behavior

First four positions suggest `new` and the fifth suggests `abs`.

#### Known workarounds

Remove snake case identifiers from F# code (they are unidiomatic anyway). However, they are ubiquitous in OCaml code and I port a lot of OCaml code to F#.

#### Related information 

Provide any related information 

* Windows 10
* .NET Framework 4.7
* VS2017
* Not severe

**Comment by cartermp** [comment]
@jdh30 which VS 2017 version? There's still a usability issue here, but at least with 15.8 Preview 5, values are there - just not selected as they probably ought to be.

**When typing with autocomplete:**

* Note: **new** is not necessarily wrong here, but the fact that `new_foo` is not seen anywhere can be misleading.

<img width="472" alt="screen shot 2018-08-01 at 21 26 40" src="https://user-images.githubusercontent.com/6309070/43562522-efa49890-95d1-11e8-866d-b3f9b21d66ce.png">

* You need to type the `_` to have preselection hit the value

<img width="352" alt="screen shot 2018-08-01 at 21 31 19" src="https://user-images.githubusercontent.com/6309070/43562583-44454408-95d2-11e8-9e44-42c09e4ccd8b.png">

What should probably happen here (note: pending experimenting with completion item kind ordering) is that both `new` and `new_foo` should be near one another in the list. I'm fine with `new` being selected first, because it's not clear if it or `new_foo` is what the programmer wants.

**With ctrl+J:**

* Anywhere in `new`, the keyword is preselected

<img width="266" alt="screen shot 2018-08-01 at 21 32 47" src="https://user-images.githubusercontent.com/6309070/43562624-79eef892-95d2-11e8-8b8f-2df01692ca4d.png">

* Anywhere after `_`, the identifier is correctly preselected

<img width="195" alt="screen shot 2018-08-01 at 21 32 55" src="https://user-images.githubusercontent.com/6309070/43562651-9358362c-95d2-11e8-8a23-52873b93f8b5.png">

This is a similar issue, where completion item kind sorting has keywords at the bottom and the identifer at the top, but preselection has selected the item at the bottom.

I think this is a result of how preselection is playing into the current algorithm for sorting completion items. They're ordered by _kind_, which is to say that identifiers are given a higher priority in the list than keywords. However, especially with completion offering imports turned on, there can be a lot of items in the list separating the identifiers from the keywords. And when completion preselection picks the keyword, it selects an item at the end of a very long list.

This can be improved, though it may not necessarily be simple. For example, say we prefered the `new_foo` identifier to the keyword `new`, but the programmer actually wanted `use x = new`. Then preselection would always be at `new_foo` when the programmer wanted it to be at `new`! So maybe there is some experimentation needed.

I'll mark this as a feature improvement for now; however, that doesn't rule out the possibility of there being a bug.

**Comment by jdh30** [comment]
VS 15.7.5

"I'll mark this as a feature improvement for now; however, that doesn't rule out the possibility of there being a bug."

I use CTRL+J to see the inferred type of a variable without having to use the mouse. Due to this behaviour, I cannot see the type of any variable in snake_case that starts with a keyword when the caret is over that keyword. Note that this does not happen if the variable is not in snake_case.

**Comment by 0x53A** [comment]
![grafik](https://user-images.githubusercontent.com/4236651/43585703-08a10a60-9666-11e8-9e25-b838bb7a2ec0.png)

**Comment by vasily-kirichenko** [comment]
![untitled](https://user-images.githubusercontent.com/873919/43598435-5b640e9c-968d-11e8-8ef6-62f9332735af.gif)

**Comment by vasily-kirichenko** [comment]
![untitled](https://user-images.githubusercontent.com/873919/43598585-adc33852-968d-11e8-8580-fbda2157f409.gif)

**Comment by charlesroddie** [comment]
This is working for me in VS2019 16.6.0. So presumably it's implemented and can be closed @jdh30 @cartermp ?

**Comment by jdh30** [comment]
@charlesroddie Interesting. For me this is still broken (albeit in a slightly different way) in VS2019.

Furthermore, retrospectively it has been fixed and regressed several times.

**Comment by dsyme** [comment]
I just tried this and I'm still not sure what the current specific bug is 

* `n` then ctrl-space offers `new` (and not new_foo, OK, maybe a bug in priorities but not so bad, there are many possible completions for `n`)

* `ne` then ctrl-space offers `new` and `new_foo` and nothing else (seems ok)

I'll close this as I don't see any specific bugs around snake case, I've tried the various samples shown above.
