### ISSUE TITLE
Update symbols in referenced C# and VB projects without requiring recompilation

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#5771]
Apologize if this has been reported before; I expected it to be, but I couldn't find anything when searching.

When a C# project references code from another C# or VB project, symbols (is that the correct term?) are updated without requiring the referenced projects to be recompiled. For example, if C# project A uses `MyClass.MyProperty` in C# project B, and `MyProperty` is deleted in project B, then this change is immediately reflected in project A; no recompilation of B is necessary. While this works for C#-to-C#, C#-to-VB, VB-to-C#, VB-to-VB, and F#-to-F# references, it seems that any reference between an F# project and a C# or VB project requires recompilation of the referenced project before any change is visible in the referencing project.

Would it be possible to add support for updating symbols between F# and C#/VB (at least when referencing a C#/VB project from an F# project) without requiring recompilation of the referenced project?

**Comment by cartermp** [comment]
This is possible with C# <--> VB due to a number of things, including having a shared compilation model. I suspect we'd have to implement all of the Roslyn abstractions in our language service and expose them to make this work properly, which would be nontrivial work, especially since we don't want those leaking into other implementations of F# that use our language service like Fable.

**Comment by dsyme** [comment]
Closing as F#-to-C# no longer requires recompilation
