### ISSUE TITLE
Incomplete pattern matches on expression false positive

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5949]
No warnings in the following code:
```fsharp
let b = true
match Some () with
| None -> ()
| _ when not b -> ()
| Some n -> ()
```

If the first two patterns are combined, warning is produced.
```fsharp
let b = true
match Some () with
| None
| _ when not b -> ()
| Some n -> ()
```

```
warning scratch_29.fsx(2,7): warning FS0025:
  Incomplete pattern matches on this expression.
```

**Comment by cartermp** [comment]
There's some general weirdness here that may be by design, even though it maybe ought not to be. Logically, `None | _ when not ...` covers the `None` case, and `Some n` covers the Some` case, so it _should_ be seen as exhaustive. And when each is a distinct case, the compiler is happy, so there's a bit of a disconnect here.

**Comment by dsyme** [comment]
This is by design. Note `None | _ when not ...` does *not*  cover the None case as the guard is still executed - the precedence is `(None | _) when not ...`
