### ISSUE TITLE
Inconsistence in structness inference in pattern matching

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#6148]
![image](https://user-images.githubusercontent.com/873919/51789989-7ac92f80-21a0-11e9-8c24-e193125a4001.png)

**Comment by vasily-kirichenko** [comment]
@TIHan If it helps, F# 4.5 requires `struct` keyword in `match st ...`. It seems structness inference for tuples was added for anon records, and the fact that it works for tuples is an unexpected side effect. Also, the inconsistence is the result of the luck of pattern matching support for anon records.

**Comment by dsyme** [comment]
This is by design, but a fantastic example of how inconsistencies appear to arise in the user experience when we infer information from the known type, and why we've been very cautious about using this information in F#.

When analyzing the pattern `x,y` in `let x, y = ...` the known type is not yet a tuple type of any kind.  So we progress on the assumption that it's a reference tuple.  We do *not* create an inference parameter to represent the unknown kind of the tuple

So fundamentally this is a difference between the left-to-right nature of things in 

    let x, y = ...

and

   match ... with x,y -> ...

There could be an argument that the pattern in a simple `let` (as opposed to a `let rec`) should be analysed after analysing the expression being bound.  However this is a separate issue and would be a significant breaking change (because the left patter can cause type information to flow into the right pattern)
