### ISSUE TITLE
Find all references doesn't work for references in Controller file in ASP.NET template

### ISSUE THREAD

**Issue by Vlad-Stryapko** [dotnet/fsharp#6243]
#### Repro steps

1. Create a project using a built-in template for ASP.NET Core Web API

2. Create a file with the module with some function

3. Place the file above the controllers folder so that the module can be referenced

4. Reference the module in the controller file e.g. call the function

5. Find all references of the function

#### Expected behavior

Function is shown as used in the controller

#### Actual behavior

There are no references found

#### Known workarounds

Delete the Controller file and re-create it

#### Related information 

* OS: Win 7 and Win 10
* VS 2017 15.9.3 Community, VS 2017 15.9.4 Professional
* Example project is attached

[TestWeb.zip](https://github.com/Microsoft/visualfsharp/files/2877196/TestWeb.zip)

**Comment by cartermp** [comment]
Confusingly, this _will_ work if you invoke from a usage site.

So if I call it from `File.myFunction` rather than the definition, it will show. Here's what the results look like in the latest preview with a redefined `id` function:

![image](https://user-images.githubusercontent.com/6309070/90078202-f2927880-dcb8-11ea-8e82-2cad0c7ef017.png)

It's almost as if Find References is being ran twice.

**Comment by cartermp** [comment]
With https://github.com/dotnet/fsharp/pull/9934 it will work if I invoke from the definition site. However, the results are still weird:

![image](https://user-images.githubusercontent.com/6309070/90191906-a6a60900-dd76-11ea-91eb-5ca5df5e196d.png)

**Comment by TIHan** [comment]
According to @cartermp , this has been resolved.
