### ISSUE TITLE
VS2019 Preview 3.0 F1 help poor with F#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#6282]
VSF_TYPE_MARKDOWNAccessing help using F1 is poor when using F#.  Sometimes it works but for types such as Result (Microsoft.FSharp.Core.Result) it doesn't work.  Other examples include:

MailboxProcessor.PostAndReply
'match' keyword
'with' keyword

Yet oddly other keywords like 'function' does go to a page with info about keywords even if not specifically the 'function' keyword.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/468436/vs2019-preview-30-f1-help-poor-with-f.html
VSTS ticketId: 801585_
_These are the original issue comments:_

Visual Studio Feedback System on 2/25/2019, 06:11 PM (2 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
I'm not sure if this is an issue in the tools. It may be primarily due to not having an FSharp.Core API reference. So any types or functions added after F# 4.1 wouldn't be recognized.

However, `match` and `with` should certainly work since they should point to the keyword reference in the .NET conceptual docs. Perhaps the keywords registered with the docs system aren't fully updated. @mairaw do you know where I could do that?

**Comment by mairaw** [comment]
Do you know what's the query URL being sent to those topics?

You can add f1_keywords metadata to associate keywords with a certain topic:
https://github.com/dotnet/docs/search?q=f1_keywords&unscoped_q=f1_keywords

@dendeli-msft used to be the F1 PM. Not sure if he still is or not.

**Comment by KevinRansom** [comment]
@mairaw It's the help context service : https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Commands/HelpContextService.fs

We will check it out tomorrow.

**Comment by realparadyne** [comment]
I just checked with preview 4.1, _match_ and _with_ now go to the keywords help page.  But PostAndAsyncReply still goes to just the Visual Studio Documentation home page.

**Comment by stanciuadrian** [comment]
Pressing F1 on `List.reduce` in a `fsx` will open https://msdn.microsoft.com/visualfsharpdocs/conceptual/list.reduce%5b%27t%5d-function-%5bfsharp%5d which shows

```
Error
Sorry, this page is unavailable. Please try again later.
```

Using VS2019 Community Preview v16.6.0 Preview 2.0 with Visual F# Tools 10.9.1.0 for F# 4.7.

**Comment by cartermp** [comment]
Closing this one out. all F# keywoards will now go to the correct site, which was missing a lot of keywords in the documentation metadata. That should be resolved now when the site goes live in a day (might be live now?)

Separately, the F1 help problems with FSharp.Core constructs is due to an error in redirects for the MSDN reference. This one is currently being investigated but once resolved it will work as usual.
