### ISSUE TITLE
Using obsolete record field makes whole record construction expression obsolete

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#6370]
Origial issue: [RIDER-25876](https://youtrack.jetbrains.com/issue/RIDER-25876)
> Repro as seen on screenshot. Maybe it'll make more sense to highlight only field assignment?

![Screenshot from 2019-03-21 17-30-29](https://user-images.githubusercontent.com/3923587/54847590-cbb45a80-4cef-11e9-8612-229c0949901c.png)

**Comment by cartermp** [comment]
I think this one is tricky. There's no such thing as a "partially available" record, where one N fields are obsolete and M fields are not. If one field is obsolete, the whole thing is, so error recovery marks the whole thing as deprecated. I think the warning could be applied only to the field in question so it doesn't mislead about other fields, but since it's impossible to create a record without an obsolete field I can see why it marks the whole thing.

**Comment by TIHan** [comment]
Doesn't seem like a bug, but I agree with @cartermp . 

To me, `[<Obsolete;DefaultValue>]` on a field sort of makes sense since you can construct the record with providing that field, but `[<Obsolete>]` on its own does not.
