### ISSUE TITLE
Anonymous Record error in fsi

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#6411]
FSI has issues if on first use of an anonymous record an exception is thrown.

#### Repro steps

```fsharp
let a = {|A = 1|}
do failwith ""
```

Run the above twice in FSI. On first run an exception is thrown as exprected, on second run there's an error
```
C:\Users\User\AppData\Local\Temp\unknown(1,1): error FS3216: type '<>f__AnonymousType1324739542`1'' not found in assembly '<emitted>'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.
```

#### Expected behavior

Exception thrown both times. 

#### Actual behavior

Error FS3216.

#### Known workarounds

Reset FSI.

#### Related information 

Tested on VS2019 preview 4.4

**Comment by cartermp** [comment]
@dsyme FYI

**Comment by cartermp** [comment]
Confirmed as not resolved yet for VS 16.2.

**Comment by Happypig375** [comment]
Confirmed as not resolved yet for VS 16.3.2

**Comment by kevmal** [comment]
More specifically `IlxAssemblyGenerator` is maintaining a `AnonTypeGenerationTable`. State becomes inconsistent when a new type is added to the anonymous type table and an error is hit in user code here:

https://github.com/dotnet/fsharp/blob/ec5bad3a391357e03ff2286a264f0e4faf7d840d/src/fsharp/fsi/fsi.fs#L1154-L1166

**Comment by nhirschey** [comment]
This bug is problematic for interactive scripting. I wanted to use anonymous records for interactive scripting. I use failwith to help build up a data file processing script, using failwith to emit information about unhandled cases. This is a great use case for anonymous records, but this bug meant that I had to restart fsi every time I found and fixed an unhandled case. 

Restarting fsi frequently is unproductive with large data files, so I had to abandon using anonymous records in my script. Another example of kevmal's problem, but more specific to my use case.

```fsharp
// Failing version
match ({| A = "test" |}.A) with
| "tests" -> "success"
| fail -> failwith (sprintf "expected tests but got %s" fail)
// System.Exception: expected tests but got test
//   at <StartupCode$FSI_0002>.$FSI_0002.main@()
// Stopped due to error

// Fixed the match statement, but now I get
match ({| A = "tests" |}.A) with
| "tests" -> "success"
| fail -> failwith (sprintf "expected tests but got %s" fail)
(* 
 error FS3216: type '<>f__AnonymousType1324739542`1' not found in assembly '<emitted>'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the 
correct version.

*)
```

**Comment by bmitc** [comment]
I came across this today, and the error only shows up in FSI by using a script to load and open modules, as the solution and projects build without error and all tests pass.

I took working code and simply added the `[<Struct>]` attribute to a bunch of record definitions to do some performance testing with no other changes. Such as:

```
[<Struct>]
type Ray = { Origin: Point; Direction: Vector}
```

Upon doing so, I received an error, which I also didn't understand.

```
error FS0193: internal error: Could not load type 'FSI_0031.RayTracer.Ray' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

So I removed the `[<Struct>]` attribute from all the record mentioned and re-ran my load script. Then I started getting the anonymous type not found error. (It is also possible the error was reported along with the above error the first time, but I can't remember.) I am only using a single anonymous record in my code, and that's inside an exception definition:

```
exception InvalidDimension of {| Row: int; Column: int; Message: string |}
```

This issue is a bit tricky to reproduce, and I am actually now (at the moment at least) unable to do so after getting rid of it. To get rid of the error I removed all `[<Struct>]` attributes and reset FSI interactive. There's some strange interaction with FSI in my codebase and adding `[<Struct>]` to a bunch of types (or certain types) and these errors.

**Comment by drhumlen** [comment]
This is still an issue. For example the following still fails:

```fsharp
let j = {| dimming = {| brightness = 40. |}
           color = {| xy = {| x = 0.5; y = 0.5 |} |} |}
```

**Comment by abonie** [comment]
@dsyme are you still planning to look into this one?

**Comment by abonie** [comment]
The secondary issue mentioned above should be fixed by https://github.com/dotnet/fsharp/pull/15519
