### ISSUE TITLE
Some operators aren't parsed correctly in member constraints

### ISSUE THREAD

**Issue by kbattocchi** [dotnet/fsharp#670]
There appear to be some issues with parsing certain operators containing ‘>’ characters when they occur in constraints:
1. When using three ‘>’ followed by zero or more other characters (e.g. (>>>), (>>>&^), etc.) or just two ‘>’ characters by themselves (>>), the compiler generates a syntax error:
   
   ``` fsharp
   let inline f< ^a  when ^a : (static member (>>) : int*int -> int) > = 0
   // error FS0010: Unexpected symbol '>' in member signature. Expected ')' or other token.
   ```
2. When using any other operator that starts with ‘>’, the compiler generates a spurious warning:
   
   ``` fsharp
   let inline f< ^a  when ^a : (static member (>+) : int*int -> int) > = 0
   // warning FS1189: Type parameters must be placed directly adjacent to the type name, e.g. "type C<'T>", not     type "C   <'T>"
   ```

It is possible to work around this by using the compiled name for the operator (e.g. op_GreaterPlus for the second example), but this shouldn’t be necessary.

**Comment by dsyme** [comment]
@kbattocchi We'd better take this through the User Voice route, so please open a ticket there to do the right thing.  Consider it pre-approved.  

For F# 4.0 we'd document it as a limitation.  One reason I'm saying this is because I believe it might be a bit nasty to fix, since adjustments to lex-filtering will likely be involved, so it's best for us just to come clean and say "it's a limitation and here's the workaround".

**Comment by dsyme** [comment]
Closing this old issue which we resolved as a by-design known limitation
