### ISSUE TITLE
F# in LoB?

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/fsharp#6780]
_[Not allowed to ask this on StackOverflow, so hope it's OK here]_

Is there a concrete example of when you would really benefit from using F# instead of C# in a normal LoB application?

In most LoB Application  you respond in some way to an event from the GUI, which normally is either a "Do Something Event" or a "Show Something Event". No matter which, you pretty much do the same thing for both, with the difference that you somewhere in the "Do Something Event" include some kind of write-operation as well.
And with a LoB Application I mean something along the lines of an ERP system, CRM, Automated Manufacturing Integrations, think Dynamics, 

Basically this is what you do (could be spread out in different "layers"):
* De-localice event arguments
* Validate event arguments
* Get some data by using linq on a data source, mostly EF and SQL Server, based on the event arguments, current user roles, current application state/context and so on
* Verify that the user is allowed to do whatever the event is about with/on the data
* Check that no business rules will be violated
* If it's a "Do Something Event"
    * Start a transaction
    * "Do Something"
    * if success then commit and set Result = (true, "Do Something completed.")
    * else rollback and set Result=(false, getLocalizedEndUserErrorMessage(exception))"
    * Show Result to the User (probably a message box if something went wrong, else the GUI is enabled and the WaitCursor goes back to normal)
* If it's a "Show Something Event"
    * Process the data to the desired state. (could be converting/looking-up codes/IDs/states to text, aggregations, marking some data as read only, add metadata to color some data in special ways, figure out what operations are valid for this user on this data in this stage according to business rules and so on.
    * Transform data to match desired display format. (could be for use in a TreeView, GantChart, Master/detail and so on)
    * Localize data according to the users regional settings in windows (date format, currencey, list separators, time zone and so on)
    * Create some kind of display view for the data along with valid context specific operations possible to do on the various pieces of the data and show it to the User. (probably updating pre-existing somewhat dynamic WinForm, or popping up a new WinForm)
---
- Is there a place for F# in these kind of LoB applications? 
- If so, where and for what?
- How would you do it practically, add a F# library/dll project to the solution and export some methods that you call from C#?

**Comment by cartermp** [comment]
Generally these sorts of questions aren't appropriate for the repo (though we don't outright prohibit them 🙂), so I'll leave you with a few links that could help. The short answer is yes, F# is fully capable of what you're mentioning, and the bulk of F# developers are building LOB applications using F# to some extent. And due to being a .NET language, all you need to do is create an F# project in an existing solution, add a reference to it, and you've got callable code from C#.

https://fsharpforfunandprofit.com/posts/why-use-fsharp-intro//
https://fsharpforfunandprofit.com/posts/fsharp-is-the-best-enterprise-language/
https://pragprog.com/book/swdddf/domain-modeling-made-functional
https://www.manning.com/books/get-programming-with-f-sharp

I also highly recommend joining the F# Software Foundation and the FSSF slack: http://foundation.fsharp.org/join

It's a pretty big community and folks there should be able to help with some of the finer details of specific tasks.
