### ISSUE TITLE
Feature Request: Automatically find source files

### ISSUE THREAD

**Issue by hez2010** [dotnet/fsharp#6864]
# Feature Request
## Automatically find source files to compile
Currently we need to add all source files we want to compile in fsproj files, and we need to care about the order of each file which is really inconvenient.  
I propose that the F# project should automatically find sources to compile just like what C#/VB.NET project did.

**Comment by cartermp** [comment]
@hez2010 The order of files is something inherent to F#'s design as a language - it could probably be adjusted, but such a change is very large and unlikely to happen.

When using tooling such as VS, VSCode, or VS for Mac, are there issues with adding files that make things cumbersome for you? At least in VS we automatically order a newly-added file to the top of the scope it's been added to (unless you use `Add Above` or `Add Below`). This alleviates most issues with adding -> ordering that newcomers often struggle with. But that isn't a universally supported tooling feature.

I'll close this since we're declining the feature request as-written, but it would be good to know what you're struggling with today.
