### ISSUE TITLE
Improve Error Reporting: Internal error with badly defined anonymous record

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/fsharp#6872]
This caught me out today - the error message is not only misleading but shows as an "internal error" in the compiler.

**Repro steps**
Enter the following code in a script or code file:

```fsharp
type ContactMethod =
    | Telephone of telephoneNumber:string
    | Address of {| Line1 : string; Line 2 : string; Postcode : string |}
```

**Expected behavior**
Did you notice the error? There's a space between `Line` and `2`. I would expect the same error as for a "full" record:

```
error FS0010: Unexpected integer literal in field declaration. Expected ':' or other token
```

And the red squiggly is directly underneath the `2`.

**Actual behavior**
You get the error `internal error: empty tuple type` with a red squiggly underneath the **entire anonymous record definition**. This had me stumped for probably 2 or 3 minutes.

**Comment by cartermp** [comment]
I think there are two issues with this:

1. The message itself is bad; the internal error needs to not leak out and instead be replaced with a more friendly error message
2. The range reported by the error is too broad; it needs to be in the label declaration

**Comment by kurt-mueller-osumc** [comment]
Hello, this just bit me as well with the same complaints from the compiler.

I was creating an F# record with an anonymous nested record to handle a JSON response from calling an api:

```F#
type ErrorResponse =
    { error: {| type: string
                     message : string |} }
```

The compiler complains:

```
internal error: empty tuple type F# Compiler(73)
```
instead of pointing out to me that it doesn't like the `type` keyword used in the nested anonymous record.

**Comment by cartermp** [comment]
Interestingly this does not reproduce anymore, at least not the internal error:

![image](https://user-images.githubusercontent.com/6309070/99140866-4c794600-25fa-11eb-9387-dbb87faa789e.png)

You still need to hover near the `2` to see the real one though:

![image](https://user-images.githubusercontent.com/6309070/99140875-556a1780-25fa-11eb-9fb8-bded16bbbe79.png)

**Comment by KathleenDollard** [comment]
This feels like an unfortunate mismatch in the squiggle span for the two errors. In both the original and @kurt-mueller-osumc example, the correct issue was squiggled, but the broader squiggle hid it. I'm not quite sure how to resolve that because obviously knowing the exact position of the accidental literal, or the unexpected keyword is important. 

Any chance we could get the broader squiggle to communicate the inner squiggle with its position? Might need a bit more structure in our diagnostics to manage that. If that's not clear, something like 

```
FS0715: Anon...
   and at 25,25 FS0010: Unexpected...
```

Also, the error for type is `Incomplete structured construct at or before this point in field declaration. Expected identifier or other token.` I get it, but doesn't seem the nicest for inadvertently using a keyword as a symbol.
