### ISSUE TITLE
Static member constraint with NOT staticaly resolved type parameter

### ISSUE THREAD

**Issue by vslynko** [dotnet/fsharp#6896]
According to info from [Constraints - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/constraints):
```fsharp
// Member constraint with static member
type Class4<'T when 'T : (static member staticMethod1 : unit -> 'T) > =
class end
```
Something along these lines should work.
```fsharp
type XmlSerializable<'t when 't: (static member fromString: string -> 't)> (nonSerializable) =
    let mutable instance = nonSerializable

    [<Obsolete("Never use. Required for XmlSerialization.")>]
    new() = XmlSerializable(Unchecked.defaultof<'tough>)

    interface IXmlSerializable with
        member __.GetSchema() = null
        member __.ReadXml reader = 
            instance <- fromString (reader.ReadElementContentAsString()) 
            // here fromString is what needed
        member __.WriteXml writer = ()
            // hope to get away with ToString
```
but it gives `error FS0670: This code is not sufficiently generic. The type variable  ^t when  ^t : (static member fromString : string ->  ^t) could not be generalized because it would escape its scope.`

Is the a way to solve the issue other than remove first snippet from the documentation?

**Comment by cartermp** [comment]
The docs in this case need to get fixed, as generally that pattern should be avoided. Your code actually does use SRTP, it's just that the compiler accepts the `'` syntax as well.

Although it's technically possible, in some cases, to apply static constraints to types, generally it's not supported due to the use of inlining when applying those constraints. Even if it were applicable in your code, it would fail immediately at the interface implementation because you cannot inline interface members.

**Comment by cartermp** [comment]
https://github.com/dotnet/docs/pull/12570

As a note the whole section on constrains and SRTP is awful in the docs, it's on my backlog to rewrite
