### ISSUE TITLE
Add support for KaOS

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/fsharp#6952]
Hi there :hugs: 

I am happy to see that the installation options have improved. 

I currently use KaOS Linux, which is currently unsupported by FSharp. 
I am happy to help to add support. 

Which information is important for you to adjust the build script?
I read through it, while I found it a little bit confusing. 

Here is the error output that I get, when I currently compile into KaOS:

```
/home/shalokshalom/Dokumente/fsharp/artifacts/Bootstrap
/fsc/Microsoft.FSharp.Targets(277,9): error MSB6006: "dotnet" exited with code 134.
 [/home/shalokshalom/Dokumente/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj] 
```

This is the line struggling:

```target
       <Fsc  Condition=" '%(_CoreCompileResourceInputs.WithCulture)' != 'true' "
```

**Comment by cartermp** [comment]
Hey there, a few questions. Since I've never used KaOS I just wanted to make sure that all the bases are covered.

1. Just to clarify, are you looking to build this repository?
1. It looks like you have .NET Core on your machine. Were you able to acquire it via a .NET Core binary distribution, or did you build from source?
1. If the answer to (2) is yes, can you do `dotnet new console -lang F# -o test && cd test && dotnet run` and get a "Hello world" result?
1. If the answers to (1) and (3) are yes, can you try building the repo with ` -bl` as an argument to the build script? This will produce an MSBuild binary log. If you upload that here then we can take a look.

@KevinRansom @brettfo  FYI

**Comment by ShalokShalom** [comment]
1) Yes. 
2) I will do a source build soon. 

Question: Is this repository meant to build independently from .Net Core?
Since I see zero indication of it as a requirement on the Readme. 

Let me build .Net Core in order to answer your other questions. 
Thanks a lot for your support.

**Comment by cartermp** [comment]
Will close this out - we're taking the approach of being supported wherever the .NET SDK is supported (and conversely, not being supported anywhere the .NET SDK is not supported). Since F# is ultimately a component of the SDK it makes sense. So if .NET is not usable on KaOS then that seems like a valid suggestion here: https://github.com/dotnet/core/
