### ISSUE TITLE
Code inside `finally` inside Comp-expr is not Comp-expr

### ISSUE THREAD

**Issue by Heimdell** [dotnet/fsharp#7002]
Code in `finally` branch of `try ... finally ...` inside computational expression is *not* treated as computational expression.

Looks like inside the language parser for "finally" branch there is _expr_, not _cexpr_ parser.

To reproduce:
```fsharp
async {
  try
    return false
  finally
    return true  // <- error points on the start of that line
}
```

What expected:
I expect this code compile just fine.

What happens:
```
error FS0748: This construct may only be used within computation expressions. To return a value from an ordinary function simply write the expression without 'return'
```

As workaround, I wrap contents of `finally` inside `async { ... }`, like that:
```fsharp
async {
  try
    return false
  finally
    async { return true }
}
```

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524
```

**Comment by cartermp** [comment]
This is by design. See the signatures as defined in [the docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions#creating-a-new-type-of-computation-expression):

**TryFinally**: `M<'T> * (unit -> unit) -> M<'T>`

Contrast this with a `try..with` block:

**TryWith**: M<'T> * (exn -> M<'T>) -> M<'T>

The key thing there is that the `finally` block is `unit`-returning. This is because of the nature of `finally` blocks: to perform some effectful computation regardless of if an exception was thrown. It doesn't contribute to the type of the surrounding function. Given this, it cannot possibly give a `M<'T>`, otherwise that would imply that it _does_ contribute to whatever value the function it's contained within gives.

Additionally, even if we were inclined to change this, it would be a breaking change. Existing code would get a type mismatch error.
