### ISSUE TITLE
Fixpoint computational expression

### ISSUE THREAD

**Issue by Heimdell** [dotnet/fsharp#7157]
## Is your feature request related to a problem? Please describe.
I am porting an interpreter from Haskell prototype to F#.
In Haskell, I have this function:
```haskell
{-# language RecursiveDo #-}

evalDecls :: Map Name AST -> Eval Frame
evalDecls decls = mdo
  st <- view stack
  frame <- traverse (allocate . Closed (frame : st)) decls
  return frame
```
As you can see, the _monadic_ definition of `frame` refers to the `frame` itself.

The function allows me to perform mutually-recursive binding for `let`-expressions in modeled language.

This all thanks to the `RecursiveDo` Haskell language extension.

In F# I typed this (but was immediately struck by thought that this would not work):
```fsharp
let! rec frame = traverseMap (allocate << Closed (frame :: stack)) decls
```
and, yeah, `Unexpected keyword 'rec' in expression`.

---
## Describe the solution you'd like
I'd like to have an ability to do not only `let rec x = ... x ...`, which is implemented as `Lazy` value, but
```fsharp
let! rec frame = traverseMap (allocate << Closed (frame :: stack)) decls
```
as well. In case of haskell, they transpile their `mdo`-monadic notation into some `mfix :: (a -> m a) -> m a` calls. You can do the same. So, this would require a
```fsharp
member this.MFix(fixpoint) = ...
```
for a computational expression that does the thing.

---
## Describe alternatives you've considered
I will not try to implement `MFix` for my monad myself and use that directly. I'm concerned that may not fly as well.

**Comment by cartermp** [comment]
@Heimdell Thanks for the example, that's an interesting use case. I'll close this because this is a language suggestion, which should be directed here: https://github.com/fsharp/fslang-suggestions

Please file this as a suggestion there. We have some engaged community members who could probably give great feedback on this.

In the meantime, you can somewhat accomplish this by factoring out into another function. Example:

```fsharp
let foo f xs =
    async {
        let rec map f xs acc =
            async {
                match xs with
                | [] -> return acc
                | x :: xs ->
                    return! map f xs (f x :: acc)
            }

        let! result = map f xs []
        return result
    }
```

Alternatively, if you wanted to use the `map` function in other functions, you could also make it `private` so it's hidden from external callers.
