### ISSUE TITLE
Equality operator can't be used with left-hand symbols in method calls

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#7423]
Using the equality operator `=` in a method call with a symbol (correct term?) on the left-hand side causes a compiler error.

**Repro steps**

In the code below, I want to pass the bool expression `x = 3` to the `Foo.Bar` method.

```f#
type Foo =
    static member Bar(a: bool) = ()

  let x = 2
  let y = Foo.Bar(x = 3)
//                ^ The member or object constructor 'Bar' has
//                  no argument or settable return property 'x'
```

**Expected behavior**

No compiler error.

**Actual behavior**

Compiler error as described above.

**Known workarounds**

* Double parentheses: `Foo.Bar((x = 3))`
* Switch order: `Foo.Bar(3 = x)`

**Comment by cartermp** [comment]
The idea fix here is a a bit tricky:

* If there is a parameter `x` for the `Bar` overload, then `x = 3` needs to resolve to the optional parameter to remain compatible
* If there is not a parameter named `x` then `x = 3` can resolve to a bool-returning expression that could attempt to satisfy the parameter type in `Bar`

I think there's two potentially conflicting design goals here:

* Not surprise the user with behavior like compile errors when it makes sense logically
* Have a consistent behavior with respect to the syntax you use

As it exists today, the second point is what's really chosen here. The compiler attempts to resolve the call site as if it were specifying a named parameter since that's the syntax for it, but because there isn't a named parameter `x`, we error.

This is something we'll need to address for named and optional parameters for F# functions, so I think it's best to consider this more motivation behind this suggestion: https://github.com/fsharp/fslang-suggestions/issues/151

So I'll close this out and link this issue as further motivation.
