### ISSUE TITLE
Build issue missing .NET SDK

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#7475]
Building clean from master fails with VS 16.2.3, I'm not sure what the right fix is.

From a VS2019 16.2.3 command prompt:

    git checkout master
    git clean -xfd .
    .\build

I get:

```
Building bootstrap 'net472' compiler
C:\GitHub\dsyme\visualfsharp\src\buildtools\fslex\fslex.fsproj : error : Unable to locate the .NET Core SDK. Check that
 it is installed and that the version specified in global.json (if any) matches the installed version.
C:\GitHub\dsyme\visualfsharp\src\buildtools\fslex\fslex.fsproj : error MSB4057: The target "Restore" does not exist in
the project.
C:\GitHub\dsyme\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj : error MSB4057: The target "Restore" does not exist i
n the project.
C:\GitHub\dsyme\visualfsharp\src\buildtools\AssemblyCheck\AssemblyCheck.fsproj : error MSB4057: The target "Restore" do
es not exist in the project.
```
More: 
```
C:\GitHub\dsyme\visualfsharp>dotnet --version
3.0.100-preview8-013656

C:\GitHub\dsyme\visualfsharp>more global.json
{
  "tools": {
    "dotnet": "3.0.100-preview6-012264",
    "vs": {
      "version": "16.1",
      "components": [
        "Microsoft.Net.Core.Component.SDK.2.1",
        "Microsoft.VisualStudio.Component.FSharp"
      ]
    }
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19430.3",
    "Microsoft.DotNet.Helix.Sdk": "2.0.0-beta.19069.2"
  }
}


```
More error log
```
Build FAILED.

C:\GitHub\dsyme\visualfsharp\src\buildtools\fslex\fslex.fsproj : error : Unable to locate the .NET Core SDK. Check that
 it is installed and that the version specified in global.json (if any) matches the installed version.
C:\GitHub\dsyme\visualfsharp\src\buildtools\fslex\fslex.fsproj : error MSB4057: The target "Restore" does not exist in
the project.
C:\GitHub\dsyme\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj : error MSB4057: The target "Restore" does not exist i
n the project.
C:\GitHub\dsyme\visualfsharp\src\buildtools\AssemblyCheck\AssemblyCheck.fsproj : error MSB4057: The target "Restore" do
es not exist in the project.
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.20
Command failed to execute with exit code 1: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin\MSBuild.exe  /p:TreatWarningsAsErrors=true /nologo /nodeReuse:false /p:Configuration=Proto  /warnaserror /consoleloggerparameters:Verbosity=minimal;summary /m /restore /t:Publish C:\GitHub\dsyme\visualfsharp\src\buildtools\buildtools.proj
System.Management.Automation.RuntimeException: Command failed to execute with exit code 1: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin\MSBuild.exe  /p:TreatWarningsAsErrors=true /nologo /nodeReuse:false /p:Configuration=Proto  /warnaserror /consoleloggerparameters:Verbosity=minimal;summary /m /restore /t:Publish C:\GitHub\dsyme\visualfsharp\src\buildtools\buildtools.proj
at Exec-CommandCore, C:\GitHub\dsyme\visualfsharp\eng\build-utils.ps1: line 50
at Exec-Console, C:\GitHub\dsyme\visualfsharp\eng\build-utils.ps1: line 119
at Run-MSBuild, C:\GitHub\dsyme\visualfsharp\eng\build-utils.ps1: line 224
at Make-BootstrapBuild, C:\GitHub\dsyme\visualfsharp\eng\build-utils.ps1: line 240
at <ScriptBlock>, C:\GitHub\dsyme\visualfsharp\eng\build.ps1: line 319
at <ScriptBlock>, <No file>: line 1
```

**Comment by dsyme** [comment]
Separately I notice our build status badge in the README.md is red:

https://github.com/dotnet/fsharp

**Comment by dsyme** [comment]
I installed precisely version `3.0.100-preview6-012264` of the .NET SDK 3.0 from https://dotnet.microsoft.com/download/dotnet-core/3.0 and could then build

I'm not sure why I got a different version on my machine, it might be because I also have a preview of Visual Studio installed

**Comment by dsyme** [comment]
Actually I still get the failure. Here are the SDKs I have installed:
```
C:\GitHub\dsyme\visualfsharp>dotnet --list-sdks
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
2.1.800 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
2.2.203 [C:\Program Files\dotnet\sdk]
3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
```
and then this is still the error:
```
C:\GitHub\dsyme\visualfsharp>.\build
VisualFSharp.sln:
  Restore completed in 40 ms for C:\Users\dsyme\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19430.3\tools\To
  ols.proj.
C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5
): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or low
er, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\GitHub\dsyme\visualfsharp\tests\FSharp.Compiler.U
nitTests\FSharp.Compiler.UnitTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5
): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or low
er, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\GitHub\dsyme\visualfsharp\tests\fsharp\FSharpSuit
e.Tests.fsproj]
```

**Comment by dsyme** [comment]
Hmmmm I seem able to build if I use the command prompt for the preview install of VS I have on my machine:
```
** Visual Studio 2019 Developer Command Prompt v16.3.0-pre.2.0
** Copyright (c) 2019 Microsoft Corporation
```

**Comment by dsyme** [comment]
I'll close this as there is a workaround and open a separate issue about our red badge for master build

**Comment by realvictorprm** [comment]
This is definitely contributor pain here.

Facing the same issue, will try the workaround.

**Comment by realvictorprm** [comment]
OK I've investigated the build script (I guess there are reasons for it being so horrible complex).
It looks like that for building the compiler with tools it's required to use VS preview version & it's msbuild which explains why the workaround by @dsyme works.

**Comment by realvictorprm** [comment]
disclaimer: I don't want to be offensive in any kind, just asking to understand the current state :)
@brettfo Why is the build script a powershell script for Windows & a sh script for Linux? Is there a specific reason?

If there is no breaking or major reason for this I would happily convert the build scripts to F# scripts using FAKE.
My preference is F# with FAKE because:
- FAKE proofed to be solid & working for me
- I think it is easier to read and modify F# code for contributors especially in the repository containing the F# language and tools
- It could tackle Linux too without having seperate scripts for Windows & Linux (of course there would still be seperate code handling each OS but both would be written in the same language).

I'm aware that a minimal part of the build setup would still be written in ps for Windows and sh/bash for Linux to invoke FAKE.

PS:
@dsyme if you only want to work on the compiler without tools just run `build.cmd -noVisualStudio` and it will succeed outside of the preview developer command prompt.

**Comment by realvictorprm** [comment]
@jmarolf OK this is an understandable effort I can very relate to.

I helped out with getting the one-line-command-build-system of OpenTK working which uses F# with FAKE under the hood but has the exact same semantics. On windows you just invoke `build.cmd` (could be a ps too) and on Linux you just invoke `build.sh`.
https://github.com/opentk/opentk/blob/master/build.cmd
https://github.com/opentk/opentk/blob/master/build.sh
https://github.com/opentk/opentk/blob/master/build.fsx

All necessary tools for invoking FAKE are bootstrapped & FAKE itself is bootstrapped itself aswell.

**Comment by cartermp** [comment]
FAKE doesn't really solve any of the problems with contributing. The chief issue is requiring a globally-installed .NET Core 3.0 SDK if you're on Windows due to internal requirements, and nothing about FAKE eases that. All it would do is add yet another layer to deal with.

**Comment by realvictorprm** [comment]
If you say so ¯\_(ツ)_/¯

**Comment by Kavignon** [comment]
Knowing that we're right now in the F# compiler; doesn't it make sense to have a full support of the language for any kind of work we're trying to do? Knowing that the compiler uses F# for its build systems would be a great addition. We lack examples of using F# in the DevOps space when it's a fantastic language for it due to its feel of a dynamic language while being statically typed. This is an "issue" while typing your script because you may do "dumb" things during development that you will only see when you run your code. I feel that having .NET open source makes it easy for systems to have access to .NET and if it works for Powershell; it should also work for F#. That's my point of view. If something is lacking to make this work then we should create a specific issue to fix this and flesh out the requirements and solve the problem in a dedicated PR. Again, I feel having F# support in the DevOps space would be huge here. (Again, in my opinion)

**Comment by saul** [comment]
Can this be reopened? I've just got a new machine and I've tried to pull down and build this repo and I'm getting the same error:

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.2.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cd \code\visualfsharp

C:\Code\visualfsharp>build.cmd
Building bootstrap 'net472' compiler
C:\Code\visualfsharp\src\buildtools\fslex\fslex.fsproj : error : Unable to locate the .NET Core SDK. Check that it is i
nstalled and that the version specified in global.json (if any) matches the installed version.
C:\Code\visualfsharp\src\buildtools\fslex\fslex.fsproj : error MSB4057: The target "Restore" does not exist in the proj
ect.
C:\Code\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj : error MSB4057: The target "Restore" does not exist in the pr
oject.
C:\Code\visualfsharp\src\buildtools\AssemblyCheck\AssemblyCheck.fsproj : error MSB4057: The target "Restore" does not e
xist in the project.

Build FAILED.
```

This is *with* the VS developer command prompt - what is the work around here?

**Comment by brettfo** [comment]
@saul Check that you have the .NET SDK 3.0.100-preview6-012264 installed (`dotnet--list-sdks`) and also check this box in VS Tools -> Options.  As far as I know this option doesn't roam between installs:

![image](https://user-images.githubusercontent.com/926281/65359126-67942580-dbb0-11e9-9aed-aa80cc4fd261.png)

**Comment by saul** [comment]
I was confused as the first `build.cmd` that I ran indicated that it was downloading the necessary SDK. No idea what happened because it clearly didn't install. I just installed the preview VS and now I can build. It's worth putting this in the dev guide as at the moment there is no mention that any of this is necessary (unless I completely missed it).

**Comment by cartermp** [comment]
At this point it's likely not worth it, as the .NET Core 3 release is Monday and it won't require anything preview.
