### ISSUE TITLE
Missing FSharp.Compiler.Tools package for F# 4.7

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7777]
According to the package description, the last available package version only supports F# 4.5.
https://www.nuget.org/packages/FSharp.Compiler.Tools

Although this is a community-based package, according to the README in [fsharp/fsharp](https://github.com/fsharp/fsharp), issues should be created here instead. More specifically, in fsharp/fsharp#903 @cartermp says:
> Point people to the dotnet/fsharp repo.

**Comment by cartermp** [comment]
This package isn't supported. It's unfortunate that it was built from that repo giving the indication that it ever was.

**Comment by auduchinok** [comment]
@cartermp Has it actually ever been supported by Microsoft, being a community-based package?

What it is the current way of creating a non-SDK based F# project without requiring to have F# targets installed other than using this package?

Should I reopen the issue in fsharp/fsharp contrary to the README and the issue template?

**Comment by cartermp** [comment]
No, it's never been supported. I recommend installing the F# targets for non-SDK style projects. If you really prefer to use the package yourself, I believe you can build it from this repository since we imported bits from other F# repos. But I'd highly advise never encouraging anyone else to use that package, because even seasoned F# developers get confused whenever there's any lag between that package and their own toolset.

**Comment by cartermp** [comment]
There isn't an appropriate place here nor there, since this is not scenario we will consider any further than closing an issue about it. In other words, if this is something you wish to support having in projects in Rider, you'll need to build and package everything yourself. I believe it may still be possible to build from this repo (should produce a npkg) and from there you could likely rename and republish it. Nobody on our side has the rights to publish any updates to the package, so we can't really help on that front.

**Comment by forki** [comment]
I assume I could help with giving people the necessary rights if needed.

Phillip Carter <notifications@github.com> schrieb am Di., 29. Okt. 2019,
16:42:
