### ISSUE TITLE
Nameof function is available, when it is not available...

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7826]
See:

![image](https://user-images.githubusercontent.com/16015770/68352287-3e026f80-0106-11ea-8f12-2579adb63581.png)

**Repro steps**

When you don't specify a preview version, the `nameof` operator is available in the IDE of Visual Studio 2019 16.3.7 (not preview).

**Expected behavior**

If the function is not available, it should not be available in the prediction lists and tooltips.

**Actual behavior**

When typing `'\n'`, upon hitting the `n` and then wanting to type the next `'`, it gets auto-replaced by `'\nameof`, which surprised me (apart from the slightly annoying auto-replace inside the context of a `char`), because I didn't have preview mode on (I believe this can be done by setting the version in the project file somehow).

**Comment by TIHan** [comment]
Yes, the function should not be available.

**Comment by cartermp** [comment]
Note that it is not longer active in IntelliSense or tooltips if you specify an older langversion:

![image](https://user-images.githubusercontent.com/6309070/111572635-375a2280-8766-11eb-9a13-23d4dfcf681f.png)

![image](https://user-images.githubusercontent.com/6309070/111572645-3fb25d80-8766-11eb-8c9e-ba7cc46b8780.png)

But the quick fixer does suggest to try and open FSharp.Core.Operators.

I think that's fine and I highly doubt we'll ever fix that TBH. You can technically reference stuff from a core library if it's available, so that might be arguably by design? I guess we could special case things but I don't really think that's worth our time.

**Comment by abelbraaksma** [comment]
Thanks for taking care of this. On your last comment, it may surprise people, as after the quickfix the error won't go away. But I agree it's hardly worth fixing, until perhaps at some time we have a list of non reserved keywords that aren't really keywords and use that as filter...
