### ISSUE TITLE
Merely implementing the generic IComparable interface with CustomComparisonAttribute does not satisfy the "comparison" constraint.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#7945]
I think the title is descriptive enough.

Code sample:

``` fsharp
open System

[<StructuralEquality; CustomComparison>]
type MyType = MyType of int
with
  member x.Value = match x with MyType x -> x
  interface IComparable<MyType> with
    member x.CompareTo(x') =
      compare x.Value x'.Value

let mySet = Set.singleton <| MyType 521
```

At `MyType 521`, it presents the following compiler error:

```
error FS0001: The type 'MyType' does not support the 'comparison' constraint. For example, it does not support the 'System.IComparable' interface
```

`MyType` however implements the _generic_ `IComparable`. Why isn't that enough? Shouldn't the compiler provide an automatic implementation for the non-generic interface in cases like that?

On the other hand, the generic `IEquatable` interface is sufficient for the "equality" constraint.

**Comment by cartermp** [comment]
This is currently by design - the `comparison` constraint is satisfied by the `System.IComparable` interface, not the `System.IComparable<'T>` interface. I recommend filing a new language suggestion here to propose that the generic interface do this: https://github.com/fsharp/fslang-suggestions/issues
