### ISSUE TITLE
support for incremental recompilation of projects

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#8044]
**Is your feature request related to a problem? Please describe.**

Incremental recompilation is not something simple, yet I believe this is a significant impediment to adoption of F# for large codebases, which are prevalent in large applications and is defintely a space where F# has a role to play.

Many language toolchains support this (C/C++, rust, scala to name a few), C#, F# and VB.NET are notable exceptions, albeit F# is the most significantly impacted as it doesn't gob lines of codes nearly as fast as C# and VB.NET compilers, plus C# and VB.NET have some support of edit and continue.

In large dotnet projects, tools like Resharper or Rider already support incremental recompilation at solution/project level, shaving off a lot of time spent on building the solution, even when a project depended upon is changed, it won't recompile the depending projects unless there is top level API surface change.

I've seen criticism and frustration around those issues, I can reasonably say this single improvement would change experience of every single F# developer and help with adoption in places with large codebases that rely mostly on fast compile time or incremental compilation.

There is even prior art in F# landscape AFAIU with Fable.

**Describe the solution you'd like**

When I change a .fs file, only code that directly depend on it in the project should be recompiled. the rest could be cached/linked in the output assembly.

**Describe alternatives you've considered**

practical: work with .fsx and only pull the subset of what you are working with, but that workflow doesn't translate well depending the type of projects / structure of the code.

hypothetical: one project per file + resharper build / hacking msbuild & fsc task infrastructure to rely on netmodules and ilmerge those, this won't work well / be supported with existing tooling.

**Additional context**

https://blog.jetbrains.com/dotnet/2015/10/15/introducing-resharper-build/
https://www.scala-sbt.org/1.x/docs/Understanding-Recompilation.html
https://github.com/fable-compiler/Fable/issues/1648
https://doc.rust-lang.org/edition-guide/rust-2018/the-compiler/incremental-compilation-for-faster-compiles.html

**Comment by NatElkins** [comment]
These issues and PRs may be related:

Incremental builder re-write - https://github.com/dotnet/fsharp/pull/8040
[WIP] Compilation Model for TryDotNet - https://github.com/dotnet/fsharp/pull/7441
[WIP] [Prototype] Compilation Model - https://github.com/dotnet/fsharp/pull/6947
Compilation Model Prototype - Information / Discussion / Proposed Plans - https://github.com/dotnet/fsharp/issues/7077

Does anybody understand how much IncrementalBuild accomplishes this functionality?

**Comment by TIHan** [comment]
In the context of build and not tooling, I don't know enough about the pros/cons of this specific mechanism to warrant an opinion on it. I would need to learn more about it and talk with the C# team to understand their perspective.

--

To increase build/compile time performance, there are many alternatives that are much cheaper to do. We are addressing them now. With each iteration, we get a little better.

How we are addressing performance today:

- Eliminating any LOH allocations
- Reducing allocations in general
- Analyze CPU stacks and determine what low-hanging fruit item can be addressed

Specifically build times, we have a potential candidate in the list:

- Compiler-Server
   - Has the potential of up to 30% increase of performance for build times based on a prototype. Though, it's not always the case depending on the solution. Some solutions show no change in build times while others do. Depends on how many projects are built in parallel.
   - Requires the compiler to undergo changes to enable building entire projects in parallel in a single compiler process. Correctness is key here rather than performance, as the compiler was not built with parallelism in mind.
   - Is not planned as of yet

> Does anybody understand how much IncrementalBuild accomplishes this functionality?

Our `IncrementalBuilder` is really meant for tooling purposes rather than build/output, though it's not impossible to mold it to do that - I've done this in the compilation prototype. 
It's job is simple: 

- Keep in memory the type-checker's environment result of each file in a project.
- If a single file has changed, do not re-type-check the files that do not depend on it. Such as the files above it from file ordering. However, it will always invalidate all files below it.
- Can invalidate itself due to type-providers or if a source or assembly file on disk has changed.

**Comment by cartermp** [comment]
Incremental _builds_ are already used in F#/C#/etc. tooling with MSBuild's up to date checker. It's a heuristic that can often fail since MSBuild is not deterministic, though. Should MSBuild ever support a deterministic mode, then this would be more reliable and act as a basis for lots of interesting experiences. We've seen 30% or more of total build time in large solutions be attributed to MSBuild tasks getting run when they shouldn't be. Tools like ReSharper Build can help with this a bit but they're still not perfect. After spending some time looking at builds for larger solutions I honestly think addressing this directly in MSBuild is more impactful.

Incremental recompilation of source files is an interesting proposal but I'm not sure it helps total build time and I'm also not completely convinced that it's the source of tooling performance woes when making changes across files and wanting to see those changes reflected. F# does not have any heuristics to see if a change in a dependent project requires that everything in a dependency chain needs to be typechecked again. C# does have these heuristics and it's why (in most cases) seeing changes reflected anywhere in your codebase is generally quite fast. Doing this for F# would be very impactful from a tooling standpoint, but I also think it's bordering on a research area too. It's something we've spoken about a lot but we don't have a definitive solution. Part of the issue is that F# tooling today does not have the necessary pieces needed to safely and efficiently calculate if something needs to be typechecked again. @tihan's work with the Compilation Model prototype adds some of the necessary infrastructural changes to allow something like that.

**Comment by baronfel** [comment]
@cartermp that sounds like something that the FSharp.Data.Adaptive model would be suited to, at least in the overall shape of the problem as described. Modeling values/bindings/scopes as adaptive values and chaining them together in more reactive ways, etc.

**Comment by charlesroddie** [comment]
> @cartermp Incremental _builds_ are already used in F#/C#/etc. tooling with MSBuild's up to date checker. It's a heuristic that can often fail since MSBuild is not deterministic, though. Should MSBuild ever support a deterministic mode...

Is this tracked anywhere? When I search on google everything says that MSBuild supports deterministic builds since VS2017. (Or possibly VS2015.)

**Comment by smoothdeveloper** [comment]
> Incremental recompilation of source files is an interesting proposal but I'm not sure it helps total build time and I'm also not completely convinced that it's the source of tooling performance woes when making changes across files and wanting to see those changes reflected. 

@cartermp, this ticket is about building and running code after it was changed, right now, however small is the change, the rebuild time of a given single project is identical to a cold build, and for projects of significant size, that time is much larger than with C# / VB.NET projects of similar size line of code wise.

I see all the good things happening in terms of optimizing F# tooling (type checking and advanced editor support up to date after edits) and don't want to detract anything from this work.

Changing code in many places before a rebuild is a valid but specific use case, the time to perform such changes offsets build time, compile taking a bit long is fine here.

The use cases I'm refering to are those that Microsoft has invested to make it easy and fast to run a solution / the code after changes (pressing F5 in visual studio), generally a mix of those:

* fast compile time (VB.NET/C#)
* edit and continue (VB.NET/C#/C++)
* incremental recompilation (C++)

In many other ecosystems, things like hotreloading is important to make workflow smooth, enabling small edits and seeing the effect quickly, see https://github.com/hasura/awesome-live-reloading for examples.

> I'm not sure it helps total build time

I hope my explanation helps in changing your view a bit, if you need an extreme example on small codebase, take FSharpPlus project, changing anything in the test project (not the library), building that project alone takes close to 2 minutes (i7-2860QM hyperthreading off), maybe you can get 1 minute on top specced CPU.

It can be argued that FSharpPlus is particularly taxing on the compiler, but it is important to understand that even a vanilla F# codebases will exhibit those issues, I assume the main reasons are:

* codebase being many times larger 
* much larger set of dependencies, having an impact during type checking
* fsc.exe is spawned per project, everything done from cold

> C# does have these heuristics

Is it type checking and code editing you are refering to? AFAIK, when you change a C# file in a project, it will rebuild the whole project and all the dependent projects (unless using the tooling mentioned), the heuristics you mention are true in the editor tooling.

I understand the impact of incremental rebuild, or edit and continue support (probably related to some degree) will require a lot of engineering efforts, and I just wanted to make an explicit request about it, I perfectly understand if it doesn't fit the current roadmap.

The great thing about incremental rebuild versus other approaches (that shouldn't be dismissed), is that it works for any kind of codebases, I could think about hypothetical ways to optimize repeated time consuming overload resolutions by not performing the full resolution when the arguments are rigid, but I'm sure it won't yield homogeneous results as proper incremental rebuild.

It will also pave the way to features related to type checking that may be put aside with the concern it could drastically improve compile time.

A simple approach to this feature would be to cache the files that are depended upon for each compilation unit, and treat each compilation unit conceptually as a separate project, but this won't scale as much as a fine grained approach at symbol level in non recursive scope and optimization such as looking at the API surface change and many others.

Thanks @cartermp and all others for the feedback so far.

**Comment by jmarolf** [comment]
@charlesroddie 

> Is this tracked anywhere? When I search on google everything says that MSBuild supports deterministic builds since VS2017. (Or possibly VS2015.)

The compilers (fsc and csc) are deterministic, however msbuild loads and runs _many_ other build tasks that are not verified to be deterministic (and many which we know to not be). So a better way to phrase this is that the F# build toolchain is not deterministic at this time and therefore incremental compilation is a best effort heuristic.

**Comment by 0x53A** [comment]
Roslyn/MsBuild added support for reference assemblies, would be great if fsc also supported this.

Here is a good writeup from the MsBuild side: https://github.com/dotnet/project-system/issues/2254

This is not directly related to the incremental build of a single assembly, but having this would enable to skip a lot of redundant recompilations.

**Comment by cartermp** [comment]
Reference assembly support is another good (also challenging) thing to add. Another benefit is a significant reduction in memory usage - for very large projects it could be upwards of 10% or less.

Incremental compilation is very different from the other techniques discussed here. I think it's best to think of it as entirely separate from everything else with its own set of benefits.

It's probably achievable on a per-module basis once we know what the dependency graph looks like. I'm just not sure how expensive that would be to implement. Certainly worth doing though.

**Comment by charlesroddie** [comment]
What is language-specific about reference assemblies? The [spec](https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#definition-of-ref-assemblies) says these are just normal assemblies with various parts taken out. Everything appears to be straightforward operations on IL so it's not clear to me why C# and VB have specific support.

Does https://github.com/ImperialPlugins/ReferenceAssemblyGenerator look any good as an `standard IL assembly -> reference assembly` function?

**Comment by cartermp** [comment]
A compiler needs to know how to read and write them, and also flow the right information to the right places depending on the operation. This is not necessarily straightforward work in a compiler, though the spec is now very stable so it won’t take as long to implement correctly as it did for C# and VB.

**Comment by charlesroddie** [comment]
OK, but am I right that in theory a reference assembly can be generated from a standard CIL assembly?

**Comment by cartermp** [comment]
In theory, the open source project you link could produce reference assemblies (though I cannot speak towards it's quality). This doesn't buy us anything, though, since the compiler still needs to know how to read them.

**Comment by jmarolf** [comment]
FSharp has special metadata that would need to be preserved, such as what is required for [inline functions](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/inline-functions). So doing this would a little bit of work to figure out how inline functions should interact with reference assemblies.


> This is not directly related to the incremental build of a single assembly, but having this would enable to skip a lot of redundant recompilations.

@0x53A  I don't understand where a claim that reference assemblies will improve incremental compilation comes from though. The compiler would still need to do the same amount of work to determine if the public surface area has changed or not. This could be elided if fsi files were being used but that can be done today. In the C# compiler reference files / skeleton assemblies are about error recovery and library distribution size, not performance.

**Comment by charlesroddie** [comment]
> @cartermp This doesn't buy us anything, though, since the compiler still needs to know how to read them.

Sounds like this would be a great improvement. The discussion in https://github.com/dotnet/fsharp/issues/7077 suggests to me that interdependencies between F# projects are the cause of a lot of existing performance problems, and also related to interop inconsistencies (F# to F# easier than F# to C#), and being able to analyze some compiled version of an F# project - or even better to take as an input a reference assembly of any .Net project, would fix that. So although I don't understand the details, these issues all seem very related.

> @jmarolf The compiler would still need to do the same amount of work to determine if the public surface area has changed or not.

If the reference assembly file has stayed the same, the public surface area is the same, and most changes that keep the public surface area the same should keep the reference assembly the same. So you just need to compare file hashes surely?

**Comment by cartermp** [comment]
@charlesroddie P2P (project to project) dependencies are an enormous problem in F# tooling, yes. If the compiler can read (and emit) these assemblies, especially if we can figure out a way to trim the very heavy F# metadata format, that would improve things. But there are other issues, including:

* O(n^2) memory usage for P2P references, since the current Incremental Build system has no ability to share symbols across compilations. This is a very complex topic though, since uniquely identifying a symbol and where it came from gets extremely difficult when shared. In Roslyn they have a whole new concept called a "Retargeting Symbol" to deal with this problem.
* Too many Incremental Builders are resident in memory, but statically or dynamically reducing the number in memory results in excessive recomputations of symbols (with the current tooling architecture), leading to more CPU and memory usage than just storing everything in memory in the first place
* No ability to tell if we need to re-typecheck a dependent project in a chain of dependencies or not, leading to excessive re-checking for correctness' sake
* Nothing runs out of process or has a separate store for symbols, leading to tools like Ionide having to implement entirely new compiler service hosting infrastructure for storing and querying symbols for Find Refs/Rename and managing how that storage gets hydrated over time in a way that is correct, responsive, and not too memory-intensive. This is a tractable but also difficult thing to do for VS because VS is 10x more complicated than VSCode in just about every way imaginable, especially when separate processes are concerned

These are just the big issues related to references and symbols; there are many more. The architecture of F# tooling was not designed for large solutions with many projects, and it starts to show when you have 100k+ LoC and 75+ projects in a solution. We're working through it but there definitely isn't an easy win to be found once we're finished addressing some of the egregious cases of needless allocations tracked here: https://github.com/dotnet/fsharp/issues/6866

**Comment by TIHan** [comment]
>  Roslyn they have a whole new concept called a "Retargeting Symbol"

The F# compiler does have a concept of retargeting symbols, but is not exactly the same as how Roslyn does it. Internally, these are not called symbols, but called "entities" and "vals". It's also called "rescoping" and not "retargeting" for us. The difference is that we do not share any entities/vals across compilations except for framework related entities, but I don't know how much of that is true for .NET Core.

However, there is data sharing of IL metadata between separate entities/vals, even if they are in different compilations. But, pieces of IL metadata do get rescoped if they need to, look for `rescopeILType` in the compiler.

When it comes to compilation-to-compilation referencing, F# serializes the signature of the compilation and another compilation referencing it deserializes the signature data and rebuilds the data, that includes rebuilding entities. When the entities are re-constructed they are also rescoped at the same time, but it's only to handle the case of ILScopeRef.Local -> ILScopeRef.Assembly rescoping on IL metadata.

**Comment by TIHan** [comment]
More info on roslyn's retargeting: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/ReferenceManager.cs

I'm still not wholly familiar with the mechanism and I might be wrong on my assumptions. I know that Rolsyn tries not to keep symbols around because they are going to be rebuilt anyway due to a user changing their code.

**Comment by smoothdeveloper** [comment]
@charlesroddie, as I mentionned you can achieve what reference assembly ought to achieve today by using resharper or rider build.

> Build with surface heuristics started at ...

This doesn't solve long compile time of a project, say taking 2 minutes to compile, however small the change, which always take 2 minutes, incremental recompilation of single project which this issue discuss ought to achieve fast recompilation by recompiling only code which depends on the files which changed between two compilations.

**Comment by TIHan** [comment]
Also, regarding reference assemblies:

We will gain nothing when it comes to F#-to-F# referencing in tooling since we do not even build assembly data anyway. Our "reference assembly" in this case is the signature metadata. But, if we were to have better integration with C#/VB projects, it would be nice.

**Comment by cartermp** [comment]
Since this topic came up in a separate place I'd like to acknowledge that this would be a pretty great feature of the compiler to have. @smoothdeveloper what are your thoughts on what a core design could look like?

**Comment by smoothdeveloper** [comment]
Disclaimer: a stab in the dark.

@cartermp the rust team has put an interesting summary of their approach

* https://blog.rust-lang.org/2016/09/08/incremental.html 
* https://github.com/rust-lang/rustc-dev-guide/blob/master/src/queries/incremental-compilation.md

A key point of their implementation is that the dependency graph is automatically infered by (1) setting "current node" and (2) using query functions to access the dependencies, calling the query function implicitly establishes an edge in the graph with the result of the query.

in F# compiler infrastructure, three important areas would take part in the graph:

* AST (using a representation discarding the ranges may be relevant)
* TAST (existing concepts of `ValRef`, `CompilationPath`, `ResolutionInfo` may be relevant)
* Ccu/IL (existing concepts of `Entity` and `CcuThunk` albeit, not sure the granularity is fine enough)

If the rust approach seems relevant, the work could be split in phases:
* establishing the querying seams by moving/encapsulating the current querying code
* experimental in-memory implementation of those seams with a backing graph structure (could be put in use in the tooling)
* serialization/deserialization in a compilation cache and adjusting the seam implementation to rely on it

I'd be excited to have ground truth assessment from the compiler team of what it would take to make this approach viable or if any alternative looks more reasonable.

F# language specific pitfalls:
* adding/removing overloads in code or references should invalidate the TAST using the same member name
* inlined functions
* quirks with type providers

Implementation pitfalls:
* increased code complexity / indirection required versus current implementation
* performance impact on cold compilation

**Comment by cartermp** [comment]
Would love to get @dsyme's view on this

**Comment by jzabroski** [comment]
@cartermp [said](https://github.com/dotnet/fsharp/issues/8044#issuecomment-573913341):
> These are just the big issues related to references and symbols; there are many more.

Indeed.  Twice in two days I've run into the following simultaneous FSharp "Oops, I Spilled The Tea" errors (that I had to manually type out here because when I get these errors, it completely freezes Visual Studio):

FS0229: Error opening binary file 'D:\Users\John.Zabroski\source\Portfolio\trunk\Source\Portfolio.Resources\bin\Debug\net48\Portfolio.Resources.dll': Not enough storage is available to process this command.
FS3160: Problem reading assembly 'D:\Users\John.Zabroski\source\Portfolio\trunk\Source\Portfolio.Resources\bin\Debug\net48\Portfolio.Resources.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file 'D:\Users\John.Zabroski\source\Portfolio\trunk\Source\Portfolio.Resources\bin\Debug\net48\Portfolio.Resources.dll': Not enough storage space is available to proces this command.
)  *Yes, there really is a random trailing parenthesis here.  I don't think I hand-typed it wrong.*

These errors seem to surface and repeat in every *.fs file in the project, starting with AssemblyInfo.fs, and then lexicographically ascending from CodeWasReviewingOnAttribute.fs, Program.fs, Test.fs, and Utilities.fs

Portfolio.Resources.dll is a simple C# assembly that just contains ~300 files:
* *.xlsx Excel templates (for Aspose)
* *.lic Aspose license file
* *.rtf rich text format files
* 4 *.resx and *.Designer.cs code-behind files that link the above resources as strongly typed references


@cartermp What are the odds that these errors are fallout from my last set of problems reported to you last year, just with better error messages surfaced?

**Comment by cartermp** [comment]
@jzabroski I'm not sure these are related to other issues other than VS going OOM. Since build does spin up an MSBuild process I doubt your issue is related to the act of building itself. The error messages are indicative of not having enough memory (I think)

**Comment by jzabroski** [comment]
@cartermp Only happens when editing F# code.  Never happens otherwise.  The errors are FS errors not CS errors, so its strange for me to hear you triage as "it's not an F# issue"?  Or am I misreading your comments?  Are you saying its an F# issue but F# + 32-bit devenv process issue? If you think its exclusively a 32-bit devenv process issue, how come I only run into it when editing F# code?  It indicates to me there is some kind of memory leak in the F# toolchain, whereas the C# toolchain is rock solid.

**Comment by jzabroski** [comment]
Also, I don't know if this is a language barrier thing, but since the error is an FS error, can you please update the word storage to say memory.  I don't know if this is a UK vs. US thing and brits say storage to refer to memory, but I'm most used to refering to OOM as memory and not storage.

**Comment by cartermp** [comment]
@jzabroski Sorry if this wasn't clear. What I'm saying is that the problem you're seeing is not related to the actual build/compile of F# code due to how that works. It's likely due to VS just going OOM. F# tooling does use a lot of memory, but there's no memory leak that we're aware of. It's unfortunately not too uncommon to see process memory limits getting reached with massive solutions and/or extensions like R# also getting involved. But none of this would really be helped by incremental compilation since we just shell out to an MSBuild process when building your codebase.

**Comment by jzabroski** [comment]
OK, but this feels a bit like "hot potato" - is there a way I can pinpoint the amount of memory used by R#, F#, etc within devenv.exe?  I used to have the Microsoft Premiere Support memory dump instructions and know how to roll them up using tools, but honestly I can't keep so many technologies in my head these days.  None of my other coworkers are running into this problem and we're all running identical Amazon Workspace instances with identical VS 2019 version, with identical solutions, all with Resharper running.  I'm not trying to push this onto you to fix, but if it is R# for example I'd like to file a bug report with them instead.

**Comment by cartermp** [comment]
I'll defer to https://github.com/dotnet/fsharp/issues/9175 where it sounds like you have what you're after :)

**Comment by jzabroski** [comment]
Thanks - please feel free to hide these comments as off-topic.  Thanks for your help.

**Comment by jzabroski** [comment]
Hi @cartermp - I actually suspect this problem may be in F# after all, and has nothing to do with the fact I'm using Resharper.  It seems like there is a string constant folding somewhere in some compiler (C# or F#) that only is triggered when the changed project graph includes a Resources assembly.  I found a C# bug fix by Neil Gafter for string constant folding (based on my guess as to what could cause exponential memory explosion on incremental compiles), but my code stack is using his fix and I still have this memory explosion issue.   I haven't nailed it down just yet, but also nobody from Microsoft Visual Studio replied to my crash reports.  Is it possible F# uses some similar string constant folding logic to the one prior to Neil's fix.

I'm almost done porting my F# code to C#, so it doesn't really effect me, but I hope this helps make a better product.  Thank you.

**Comment by TIHan** [comment]
Hey @jzabroski , I apologize that we haven't looked at the crash reports. We take your issues seriously, and we want to have a better product.  While we don't know if it is really caused by constant folding with strings, you have at least highlighted a problem that we should fix.

In F#, we do constant folding with strings; I implemented it last year when I was optimizing string concatenations to use the `String.Concat` overloads. Looks like C# did the same thing until it was fixed, Neil has a small post describing the problem with a solution: http://gafter.blogspot.com/2019/08/accidentally-quadratic-constant-folding.html

I did the naive way of doing constant folding and looks like that can bite us. The easiest solution is just not to do constant folding with strings, or just limit the amount.

**Comment by jzabroski** [comment]
@TIHan Glad my intuition was correct and helpful in pinpointing the problem. I never for once took any offense to any discussion I've had with Microsoft. I'm easy going.  Glad I can help improve F#.  I see a bright future for .NET where we can all have a peaceful ecosystem of awesome language features.  Rock on, Will.

**Comment by NatElkins** [comment]
Just going to throw this into the mix for inspiration (although it more specifically deals with incremental parsing) https://diekmann.co.uk/diekmann_phd.pdf

**Comment by smoothdeveloper** [comment]
@cartermp / @TIHan, seeing there are tracked tickets/experiments on incremental builder and that a thought came to better scope a potential first iteration on incremental recompilation.

The caching would be happening at the source file level in terms of coarseness, and working on the infrastructure around `.fsi` signatures files.

cache outputs per file:
* `.fsi` file if not existing, the compiler generates a transient one
* `.netmodules` / `.obj` files ([net module docs](https://docs.microsoft.com/en-us/cpp/build/reference/choosing-the-format-of-netmodule-input-files?view=msvc-160))
* `.fscmetadata` extra metadata

for `.fsi` and `.netmodules` / `.obj` I believe there is already some support in the compiler code.

for `.fscmetadata` it could be based on future effort to have a non breaking API for the AST & CheckedAST a compiler specific implementation with what's easiest to do to serialize/read those from current types.

related: #10445 #10217 #10211 #7077

if any of those tickets could invest some effort towards coming in the direction of this issue, I think it will be helpful for eventually reaching the goal of this issue.
