### ISSUE TITLE
F# intellisense (sometimes) suggests names when it shouldn't

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8473]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/726793/f-intellisense-sometimes-suggests-names-when-it-sh.html)._

---
Start typing a union case:

type License =
    | (etc...)

Later I add a new case, which I want to be first, so I open up a new line after "type License =" and type "| " and I am ready to add my new name - but intellisense now wants to suggest names for me, which it really shouldn't.

Very intermittent.

---
#### jimfoye2 on 9/7/2019, 02:35 PM: 

Sorry, I need to edit this. After typing the "| " then the first letter of a new name, that's when Intellisense kicks in with suggestions. So actually I don't think this is intermittent.
#### Visual Studio Feedback System on 9/9/2019, 03:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/17/2019, 10:03 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by voroninp** [comment]
I also see Intellisense showing me protected overridden method as public.

```FSharp
type TestHandler() = 
    inherit HttpMessageHandler()
    override this.SendAsync(request, cancellationToken) = base.SendAsync(request, cancellationToken)
```
<img width="405" alt="Screenshot 2020-03-14 at 10 29 11" src="https://user-images.githubusercontent.com/9202028/76679290-a47d2a00-65df-11ea-9038-e9b996db9bad.png">

**Comment by cartermp** [comment]
@voroninp What you're seeing is by design, as the F# language does not support the `protected` modifier. This issue tracks it: https://github.com/fsharp/fslang-suggestions/issues/157

**Comment by voroninp** [comment]
@cartermp Though visible, it is not accessible as `public` method would be. Is it also by design?

**Comment by jimfoye** [comment]
I'm sure bumping issues is frowned upon, but I was just getting ready to report this again, as I had forgotten that I had actually already reported it nearly two years ago. Any chance of changing the priority? 

Here's an example of how this causes problems. Let's say I want to create a case, using a name that just happens to partially match something in Intellisense. As I start typing, Intellisense pops up (which is a little jarring at this point). Now I finish typing in the name of the case:

```
open System.Net

type MyEventType =
    | DownloadDataCompleted

```
There should be two possibilities for me now: if the case has data, I can press Space and then the type (of course at that point Intellisense appears again, and it is most welcome). If there is no data, then I can press Enter and go to the next line.

Since DownloadDataCompleted partialy matches DownloadDataCompletedEventArgs, I cannot press either Space or Enter, as both will "complete" my case name to DownloadDataCompletedEventArgs. I have to press Esc to clear Intellisense first. 

ONTH, suppose my case name is "DownloadDataCompletedSlowly" instead of "DownloadDataCompleted". At some point that stops matching anything in Intellisense, which then disappears, so that Space and Enter both work as expected.

The result of this is that every single time I create case names, I feel like I'm in a battle with the editor and I have to slow down and think about which keystrokes are "legal" for me after I've finished typing the case name. It's actually even worse than that, because as I'm typing the case name, I'm already watching the list of suggestions in Intellisense shrink, while my mind is playing the game of "Will I get there all the way? Will Intellisense disappear on its own?"

I'm going to give another example of an Intellisense issue here, but only because I don't know if it is due to the same root problem or not. If it's different, I'm happy to create a separate issue for it.

Let's say I need a for loop. So I type

`for i in 0..100 do
`

The Intellisense window is open here. Should it be? I think it is also unneeded here (though maybe there is a reason and I don't know it). If it needs to be open, then at least "do" should be the top entry. I tested this in Rider, and "do" appears first. So in Rider I can hit Enter once to accept the "do", and Enter again to go to the next line. That's still one Enter too many, but at least it doesn't do what VS does here. It proposes "double"! So when I hit Enter, this is what I get.

`for i in 0..100 double
`

Argh! I have done this more times than I can count.

**Comment by cartermp** [comment]
@jimfoye evidently the type declaration cases are covered here, which should likely be in the next VS update: https://github.com/dotnet/fsharp/pull/12351

And I believe the `do` case is covered here, similarly should be available in a forthcoming VS update https://github.com/dotnet/fsharp/pull/12318

@dsyme I think this one can be closed

**Comment by jimfoye** [comment]
@cartermp  Excellent, thanks!
