### ISSUE TITLE
F# file build order changes not recognized unless you restart

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8476]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/756695/f-file-build-order-changes-not-recognized-unless-y.html)._

---
When working on an F# project selecting move up or move down on a file, the new order is not recognized by visual studio unless you save the project and close and restart visual studion.  Visual studio 2019 with lates update (as of last night, 10/1/2019)

---
#### Visual Studio Feedback System on 10/3/2019, 03:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/7/2019, 07:31 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Explicitly tagging as `needs repro` since we've not seen this happen

**Comment by abelbraaksma** [comment]
I have seen this happen from time to time, actually, and I think it had to do with the solution not being saved. If save-before-each-build is on, this shouldn't happen.

But at the moment I cannot repro it anymore either. It never really worried me, as it only seemed to happen intermittently, not always, and there was an easy workaround (either ctrl-shift-S, do an extra move if the file, or change the file's contents to force the dirty flag).

(it may also be hard to detect since not every rearrangement would lead to a failure (or lift a failure) on compiling).

**Comment by cartermp** [comment]
Closing due to no repro
