### ISSUE TITLE
First class dprint* functions

### ISSUE THREAD

**Issue by jimfoye** [dotnet/fsharp#8522]
I have an implementation of dprintfn in all my projects:
```

open System.Diagnostics

let dprintfn format =
    Printf.ksprintf Debug.WriteLine format

```
I don't know if this is the best approach, but it works for me.

Why don't we have a dprint* family of functions out of the box? I found a signature file in the repo, ildiag.fsi, which has signatures for three dprint* functions, but I don't see anything anywhere else.

**Comment by abelbraaksma** [comment]
The problem with this approach is that (curried) functions and their arguments are not erased when the `DEBUG` flag is set, leading to overhead. Since your function is curried, it will never be erased (only the call to `Debug.WriteLine` will be removed, arguments are still processed advance evaluated).

An alternative that I use is to define class members with the proper attributes and some overloads using tupled arguments instead. But you'll lose currying. With some creativity, however, you can still get the behavior of `sprintf` with in-string highlighting and type safety. But it requires some work.

**Comment by jimfoye** [comment]
I see what you're saying about there being overhead, but it's only overhead if you decide to use it. There is also overhead if you just fall back to calling System.Debug.WriteLine(); even in a release build, though the message is not output, the call is there (unless you wrap it in #ifdef DEBUG - which you could also do with dprintfn(), if you were really concerned about performance).

**Comment by abelbraaksma** [comment]
@jimfoye, actually, no. There's really zero overhead and the method is not called at all. And according to the F# spec, the expressions that form its arguments are also removed. See documentation:

> Applying ConditionalAttribute to a method indicates to compilers that a call to the method should not be compiled into Microsoft intermediate language (MSIL) unless the conditional compilation symbol that is associated with ConditionalAttribute is defined.

And those debug methods are marked with that attribute. If you check the MSIL, you will see that the calls are not there at all. 

That's why using this technique is so powerful. I use it with both `DEBUG` and `TRACE` for several methods in my code. No need to use `#if DEBUG` each time you call such methods.

**Comment by jimfoye** [comment]
Learn something new every day! I didn't know about ConditionalAttribute.
