### ISSUE TITLE
Unable to reference enclosing type's generic arguments for constructorless types

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8527]
This is problematic for structs. 

I'm not sure why the restriction exists in the first place if inference doesn't take it into account as well.

```fs
type Foo<'T> = interface end

// Flexible type allows referencing enclosing 'T (this is not compiled as a new arg on the method).
type [<Struct>] Bar<'T> =
    member __.Invoke(x: #Foo<'T>) = ()
        
// Cannot express this explicitly in a constructorless type though.
// error FS0039: The type parameter 'T is not defined.        
type [<Struct>] Bar2<'T> =
    member __.Invoke<'a when 'a :> Foo<'T>>(x: 'a) = ()
```
This attempt at a workaround doesn't work (as expected)
```fs
// Structs cannot have empty constructors either.
// error FS0081: Implicit object constructors for structs must take at least one argument
type [<Struct>] Bar3<'T>() =
    member __.Invoke<'a when 'a :> Foo<'T>>(x: 'a) = ()
```
These workarounds do work 
```fs
// An empty constructor does fix the issue for classes.
type Bar4<'T>() =
    member __.Invoke<'a when 'a :> Foo<'T>>(x: 'a) = ()

// Workaround by adding a dummy ctor.
type [<Struct>] Bar5<'T>(x: obj) =
    member __.Invoke<'a when 'a :> Foo<'T>>(x: 'a) = ()
```

**Comment by abelbraaksma** [comment]
>     // Cannot express this explicitly in a constructorless type though.
>     // error FS0039: The type parameter 'T is not defined.

Since a constructorless type cannot be instantiated, not inherited from (you can inherit, but still cannot add constructors), it makes some sense that you get an error here, since you use instance members and not static members. 

I've often found it odd that in F#, you can create instance methods on a type that cannot be instantiated. But since no instance is available, I think the type resolution got confused.

That's probably why the workaround for classes works. It may be something similar with the structs, since they have a default constructor always, even if it's omitted, and somehow the compiler applies the same algorithm as for classes and gets confused again. 

Though while you may not be able to call the members, the syntax seems valid and I don't see any technical requirement for errors in this case.

**Comment by NinoFloris** [comment]
This is of course not true for structs, hence me opening this issue

**Comment by abelbraaksma** [comment]
Got it, seems like I skipped the first line in your OP ;).

**Comment by dsyme** [comment]
There is no reason for this restriction, it should be fixed, thanks

**Comment by dsyme** [comment]
This got fixed somewhere along the way - tried it on F# 6.0 and it works just fine.
