### ISSUE TITLE
Cyclic constructor call should emit a compiler error

### ISSUE THREAD

**Issue by Szer** [dotnet/fsharp#8623]
F# compiler should not allow to create cyclic constructor calls, because they will always end up with Stack Overflow.

C# compiler for example emits an error:
```csharp
class Foo {
  public Foo(): this() { }
}
// Program.cs(11, 27): [CS0516] Constructor 'Program.Foo.Foo()' cannot call itself
```

**1. Steps to reproduce**

This fails in runtime:
```fsharp
type Foo = new () = Foo()
Foo() //StackOverflow
```

**2. Expected**

Example above should fail in compile time

**3. Environment**
Pretty sure it's irrelevant, but still: 
.NET SDK used - 3.1.100 with corresponding F# compiler
OS - MacOS 10.15.3 (Catalina)

**Comment by abelbraaksma** [comment]
I agree that it _should be_ an error, but since this has been allowed behavior for some time (at least, I assume this wasn't disallowed before), there may be legitimate code out there that explores this behavior (I can't think of any, though, but it just might). 

As such, I suggest to make it a highest level (as in: most severe) warning instead. And possibly, for new projects, add it to the "warnings as errors" list as we already do with some other warnings. Then you can still opt out if you want the old behavior for some reason.

**Comment by markpattison** [comment]
Related: #2321

**Comment by dsyme** [comment]
Will close as a duplicate of https://github.com/dotnet/fsharp/issues/8623

**Comment by abelbraaksma** [comment]
@dsyme, which duplicate? You referred to this issue itself (i.e., `#8623`)...

**Comment by dsyme** [comment]
This one https://github.com/dotnet/fsharp/issues/2321
