### ISSUE TITLE
[loc][Query][fsharp] Localizability of files

### ISSUE THREAD

**Issue by PDostalek** [dotnet/fsharp#8814]
Hi,

please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.

File Name Live Page Extended | String Resource ID | Full Source String | Query | Answer Needed
-- | -- | -- | -- | --
fsharp\xlf\FSComp.txt.xlf | 0; "featureAndBang" | and bang | We need more context for this   string, what does bang mean in this context? Assuming some kind of code and   therefore left it as it is.      Please clarify string. Is bang localizable? |  
fsharp\xlf\FSComp.txt.xlf | 0;   "featureImplicitYield" | implicit yield | Would   you please confirm that ""yield"" is to be left in EN as   a yield statement? |  
fsharp\xlf\FSComp.txt.xlf | 0;   "featureRelaxWhitespace" | whitespace relexation | Could you please explain what   this means? We were unable to find any reference. What specifically is being   relaxed?     does relexation here have the same meaning of that in "relexation   labeling"?     "Would you please confirm ""relexation"" is   supposed to be ""relaxation"" with the meaning of   mitigation? |

**Comment by cartermp** [comment]
Hey @PDostalek, here's the information:

**and bang** - 'bang' refers to the `!` character. This feature corresponds to a new keyword, `and!` and some new behavior it carries along. I will rename this since it is confusing and I can't think of a useful way to disambiguate it.

**implicit yield** - `yield` is a keyword, so that should be left alone, yes.

**whitespace relaxation** - this is referring to a previous requirement in code that was unnecessarily strict about how programmers used whitespace. This requirement is now relaxed/softened a bit.

Does that help?

**Comment by cartermp** [comment]
@PDostalek https://github.com/dotnet/fsharp/pull/8826 should resolve this issue re: `and!`

The term "applicative" that is going in is a distinct term: https://www.wikiwand.com/en/Applicative_functor

And "computation expression" is also a distinct term in F#. Hopefully this helps.

**Comment by PDostalek** [comment]
Thank you @cartermp
