### ISSUE TITLE
Syntax coloring fails when using `delegate of`

### ISSUE THREAD

**Issue by GratianPlume** [dotnet/fsharp#8910]
![image](https://user-images.githubusercontent.com/5526875/78849595-7e647180-7a47-11ea-8295-44634825752c.png)

**Comment by cartermp** [comment]
@greatim Can you provide some more info? VS version, etc. I don't see any apparent syntax coloring in the latest VS preview.

Light mode:

![image](https://user-images.githubusercontent.com/6309070/78919222-7821c580-7a46-11ea-9958-ae839b030be8.png)

Dark mode:

![image](https://user-images.githubusercontent.com/6309070/78919263-866fe180-7a46-11ea-968c-e4598acbfda7.png)

**Comment by greatim** [comment]
I found it's normal, after I changed a PC. 
I try many way, and find that, if I change the color of  'F# function/method ' in option 'font and color' .
The error  reproduce.  It can't be any other color than default.

**Comment by greatim** [comment]
@cartermp 
It's Vs2019.
Set `F# function/method` color, it show:

![image](https://user-images.githubusercontent.com/5526875/84745797-aa701600-afe7-11ea-8084-aed23b54d69d.png)

![image](https://user-images.githubusercontent.com/5526875/84745854-c1166d00-afe7-11ea-8be0-f570c2aa738d.png)

When the color of  `F# function/method`  didn't set, it show:
(Triggering conditions: a space before `B` or any other char)
![image](https://user-images.githubusercontent.com/5526875/84745572-5f560300-afe7-11ea-954e-3081d2bc702a.png)

![image](https://user-images.githubusercontent.com/5526875/84746012-f3c06580-afe7-11ea-83d9-815b5e5c0915.png)

**Comment by Happypig375** [comment]
That name tho

**Comment by cartermp** [comment]
@greatim Thanks for the repro

https://github.com/dotnet/fsharp/pull/9511 addresses a lot of color-related things, and the current system for handling "F# function/method" coloring is now different and uses some more standard definitions for things. Since the custom colorization for functions will go away with PR, I suspect this should be resolved. Here's what it looks like for the default BTW

![image](https://user-images.githubusercontent.com/6309070/85188024-e2ca5b00-b258-11ea-8701-04f2d28de16a.png)
