### ISSUE TITLE
Mark inline functions with the AggressiveInlining attribute

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#9052]
The title is descriptive enough. Inline functions have their body replaced where they are called, but their actual method definition does not have the `[<MethodImpl(MathodImplOptions.AggressiveInlining)>]` attribute.

Applying it would better convey the intent of having this function inlined in C# users of a library.

---

A better (and maybe breaking) idea is to __just apply the attribute without actually inlining the function__. It is simpler, does not increase the compiled assembly's size and moves the burden of inlining the function to the JIT. Moreover it will fix issues like #8348.

As for SRTPs, we might still resort to the traditional inlining, or define many instances of the method in the assembly, depending on the type parameters.

**Comment by abelbraaksma** [comment]
> A better (and maybe breaking) idea is to just apply the attribute without actually inlining the function. It is simpler,

When you inline a function, you're basically doing SRTP already in most cases. Something simple like `let inline f x = int64 x + 1L` would fail to work in many scenarios (remove 'inline' and you get the dreaded 'cannot unify types' error). The difference being compile-time constraints (SRTP) vs runtime constraints (generics).

I doubt adding `AggressiveInlining` will have much effect, since the body of the function simply doesn't exist: it's injected in-place in F# code. Inline functions like that cannot be called from C# anyway, regardless whether that attribute is present. Te reason is simple: C# doesn't do compile-time inlining. 

It may make more sense adding that attribute for small functions that are runtime-generic.

**Comment by dsyme** [comment]
I agree with @abelbraaksma's analysis here - the actual IL methods are present mainly for reflective execution and so don't need this attribute.
