### ISSUE TITLE
Conflict between unit of measure and function name

### ISSUE THREAD

**Issue by mathias-brandewinder** [dotnet/fsharp#9067]
Please provide a succinct description of the issue.

When creating a unit of measure with a certain name, it shadows functions using the same name, making the function unusable. See example below: creating a UoM named `min` makes the `min` function disappear.
 
**Repro steps**

``` fsharp
let x = min 1 2 // works just fine
[<Measure>]type min
let y = min 1 2 // error FS1133: No constructors are available for the type 'min'
```

**Known workarounds**

... avoid using UoM named similarly to existing functions.

* Operating system

dotnet core 3.1 / Windows, using `dotnet fsi` in the terminal.

**Comment by TheJayMann** [comment]
This issue appears not to be with unit of measure types specifically, but with class types.  If you were to instead declare `type min = class end` without adding the `Measure` attribute, or even writing a proper class type, you would see the same effect.  This is likely because a class type's constructors are exposed as an overloaded set of static methods which return an instance of the class.  This allows the class to be used like a function in a typical function pipeline rather than having to use the `new` keyword.

**Comment by abelbraaksma** [comment]
@TheJayMann, while that may be true, there's no conflict when they're in a different module. This works:

```f#
open System

module Foo =
  let pos x = x + 10

  [<Measure>]
  type pos

module Bar =
  open Foo
  let y = pos 12
  let x = 4<pos>
```

**Comment by cartermp** [comment]
This issue is by design. The `min` name in the measure shadows the `min` function in that scope.

Code like this can work:

```fsharp
module Foo =
  [<Measure>]
  type min

  let min (x: int<min>) = ()


module Bar =
  open Foo
  let y = min 12<min>
```

Because the compiler can distinguish between the `min` as a type argument vs. the `min` as a function. Note that here, the built-in `min` is shadowed.

Another workaround here is to explicitly qualify your call to the FSharp.Core `min` function like so:

```fsharp
Microsoft.FSharp.Core.Operators.min 1 2
```
