### ISSUE TITLE
support .fsproj.user for debugging settings and such, like c# projects

### ISSUE THREAD

**Issue by damageboy** [dotnet/fsharp#91]
In c#, there's always a .csproj.user along side the .csproj file that containts stuff like the startup directory and arguments for debugging.
This makes sense as those files are usually NOT checked into to vcs, and therefore reduces the amount of friction between developers sharing the code on their machines through a vcs system, while no overwriting each others debug settings...

It would be nice if .fsproj projects could get the same amount of love... :)

**Comment by rojepp** [comment]
+1

Old uservoice suggestion [here](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6568436-move-user-settings-out-of-fsproj-file), moved from [fslang uservoice](http://fslang.uservoice.com/forums/245727-f-language/suggestions/6564576-move-user-settings-out-of-fsproj-file)

**Comment by dsyme** [comment]
+1, 

Since it's a tooling suggestion strictly speaking it belongs on the User Voice and so this might get closed (see CONTRIBUTING.md).   What we really need is someone to take a crack at a PR to add this? Or to give pointers on what needs to be changed?

**Comment by damageboy** [comment]
I'd love to take a crack at this, but would also really love some sort of pointer to where the .fsproj parsing happens

**Comment by dsyme** [comment]
@latkin @KevinRansom  - any pointers into the Visual F# Tools codebase?

**Comment by latkin** [comment]
@rojepp [opened this on UserVoice](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6568436-move-user-settings-out-of-fsproj-file) a while back, maybe he is getting impatient :sweat_smile: 

Yes, much of the lower-level projsys stuff is in VB. If my VF# history serves me, a lot of the VS tooling stack started life as a general-purpose sample project system, created millenia ago by some random Microsoft team, and VB happened to be the implementation language.  In VS 2010 timeframe, VF# team took that sample as a starting point and adjusted/amended as needed to get F# running.  Fast forward to today, and we've still got a large chunk of this legacy code, with various F# features/fixes hacked in with more or less polish.

@vladima is probably the best expert on history and details here, maybe he can comment on the scope of this feature.

Does [PTVS](http://pytools.codeplex.com/SourceControl/latest) support this? If so, that might be a decent open source reference.  Otherwise we would have to take a look at the C# project system, which is unforunately private and all C++.

**Comment by forki** [comment]
Are you saying this stuff is not open sourced yet and nobody is really owning that part? 

(me and my team would switch to VS 2015 today if this would work)

**Comment by latkin** [comment]
> Are you saying this stuff is not open sourced yet

Correct, the C# and VB project systems are, for now, fully private. So any "porting" of this feature would need to be done significantly by Redmond people.  Unless another open source project system happens to have the feature already (I would suggest PTVS as the first place to look).

> and nobody is really owning that part

Not sure I understand.

**Comment by rojepp** [comment]
Installing PTVS right now to see if it behaves. Would a PR for this have a chance at getting into F# 4.0 even though it is late in the game?

**Comment by forki** [comment]
Ok if we can't fix it, then how can we raise awareness inside of MS?

**Comment by rojepp** [comment]
Sadly, PTVS doesn't behave. Neither does IronPython, Nemerle. Any other ideas for projects to look at?

**Comment by forki** [comment]
My question is: is the F# part open source? If not, how can we raise awareness inside of MS. This is super annoying.

**Comment by rojepp** [comment]
If I understand @latkin correctly, the F# parts are all open source, but the examples of how to implement this (C#, VB) are not, so there's nothing to look at for reference.

**Comment by forki** [comment]
Ok. That sounds much better than what I understood. Thanks.

**Comment by latkin** [comment]
> Would a PR for this have a chance at getting into F# 4.0 even though it is late in the game?

IMO, no. This is at least a medium-size feature, which has major back-compat and round-trip implications (need to spec out how VS 2015 handles, say VS 2013 projects - moving everything out of .fsproj will break downlevel usage) and is not particularly easy to test.  Needs to integrate properly with source control systems, with cloud-synced user settings, etc.

It's a nice feature that I would personally be in favor of adding, but it's too late for F# 4.0. It would be great for an update release.

> is the F# part open source?

The point is, the F# projsys doesn't have this particular part :-) But yes, the entire project system is here.  The VF# codebase (compiler+IDE) is now about 99% open, in this repo. The only remaining private stuff is our horrific setup and loc build infrastructure :scream:

**Comment by vladima** [comment]
F# project system\language services started as a fork of [MPF](https://mpfproj12.codeplex.com/) but significantly diverged from the original implementation. AFAIR MPF does not support persistence in user files a well.

[IVsBuildPropertyStorage interface](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsbuildpropertystorage.aspx) is used by the VS to store and load user settings. I have not touched related parts of code for a while. Will try to look into this issue next week

**Comment by rojepp** [comment]
It seems the functionality is meant to be implemented, but that it just doesn't work. 
The relevant properties do have the `PersistedInProjectUserFile` flag set [here](http://pytools.codeplex.com/SourceControl/latest)

**Comment by dungpa** [comment]
I found an example that supports *.user files at https://github.com/tunnelvisionlabs/MPFProj10.

Hi @sharwell, can you give some hints how to implement the feature? Thanks in advance.

**Comment by dsyme** [comment]
This may be the relevant commit (not sure though) https://github.com/tunnelvisionlabs/MPFProj10/commit/11c7d9930e11e890dec7921284372f53480e7642

**Comment by damageboy** [comment]
@dsyme, @dungpa thanks for the pointers, this definitely looks very relevant...
No harm in trying.. :)

**Comment by damageboy** [comment]
I'm trying to port the MPF feature into the F# version, there's a lot of additional input validation on, well basically everything over there, would it be a good idea to "port" that too, or should that be separate commits?

**Comment by damageboy** [comment]
So short progress report, I've kind of completed the porting, but the commit @dsyme pointed to doesn't seem to be the end of the story, it looks like there is additional work put into this in the MPF project.

Also, while on the same subject, the current MPF project looks MUCH better than the FSharp version is right now, and lots of work seems to have been put into it, perhaps a much more serious rework of the fsharp version is in order...

Will keep you posted as I understand what goes on...

**Comment by sharwell** [comment]
Does the F# project system use MPFProj as the base? If so, then it would make sense to replace it with the build of MPFProj that I've been working on. It's pretty easy since it's now distributed via NuGet, but the steps aren't particularly well documented. I'd be glad to help you evaluate it as a potential long-term solution.

If you aren't using some form of MPFProj as the base for the project system, then I'm not sure the work I did would be useful.

**Comment by damageboy** [comment]
@sharwell it uses a very old, version of it, from the little I can tell, i.e. your updates haven't made it in.
I'm currently having a problem testing my port of that specific commit, which might actually be enough to solve the issue.

If people would like to, I wouldn't mind working afterwards, one porting the project system to the newer NuGet distributed one, as it does look like you have improved it a lot... :)

The only issue I see, is that because F#'s version seems to be some sort of a mix between F# and C# code, they have changed the code the replace all kinds of internal/protected members to be public so the F# code would be able to consume/mutate them...

My current issue, right now, is that I simply am not succeeding in runnign my own rolled build in the experimental hive..., I'm kind of new to VS extension / development...

**Comment by sharwell** [comment]
Thanks for the update. I'll try to take a look this week.

**Comment by dsyme** [comment]
Yeah, I'm afraid we use an old version, and it's been modified it a fair bit since circa 2008. I didn't actually realize there was any work going on to improve the base.

I recall that the Visual F# Tools team:
- chopped out features we weren't using
- fixed bugs
- added some functionality
- moved some functionality to F#

There are three paths forward

1. cherry pick improvements (as we're doing here)
2. achieve convergence

Given what I've experienced of the very high bar for stability requirements for Visual Studio-shipped components, I do think route 1 is going to be a more likely path.

To achieve route no. 2 we'd probably need to first identify a common base between the two project system implementations.  I could try to dig that out but it could be a hard slog even from there - they diverged quite a long time ago now. 

@sharwell - do you know the history of the codebase?

**Comment by sharwell** [comment]
@dsyme I not only know the history of the codebase, but I have the ability to diff a modified codebase against the ongoing work to figure out if it includes any new features I haven't addressed yet.

**Comment by damageboy** [comment]
@dsyme, @sharwell from the very little inspection I've made to `ProjectNode.cs` and `ConfigProvider.cs`, it seems like at the very least there are many more input validation checks and well as code-deduplication that @sharwell has put into the code base.

Cherry-picking could definitely work, and gradually minimize the difference while providing real benefits on a feature-by-feature basis... For example, while I was porting the .user changes, I could easily "shove" many more input validation checks, and follow @sharwell footsteps in de-duplicating some of the code, this would create a overly sized commit, but most of these changes would be very fail-fast-ish by nature, and would reduce the difference between both code bases...

If this would be repeated for a few key-improvements from MPFProj, the code bases would ever-so-slowly converge...

I'm still a bit lost in getting my branch/fork to run, for some reason I can't get it to load up in Visual Studio, I definitely don't waste any of your time, @dsyme, but could you point me towards someone that would be able to help me get the tooling running in VS?

**Comment by latkin** [comment]
@KevinRansom should be able to help/advise on running private-built IDE bits

**Comment by dsyme** [comment]
Hi @damageboy  - @latkin and @KevinRansom should be able to help you get your stuff running.

If you implement the .user feature, make the changes minimal, per [the contribution guidelines](https://github.com/Microsoft/visualfsharp/blob/fsharp4/CONTRIBUTING.md#mimimum-bar-for-code-cleanup-pull-requests). Submit the validation checks in a separate PR.  

The fail-fast nature of the checks will be of concern to the Visual Studio team w.r.t. stability and it is likely they would at very least put off accepting the PR until the Visual F# Tools for F# 4.0 in Visual Studio 2015 are done and dusted.

**Comment by damageboy** [comment]
@dsyme thanks for responding so quickly, I did read the guide, and I think I have followed it, I've linked to my pretty minimal commit before in this thread:

https://github.com/damageboy/visualfsharp/commit/4db1d9bc99d81ba390ac3bd85bc702ae7e97bccd

@KevinRansom, how do I get in touch with you? I'm reachable through [dans@houmus.org](mailto:dans@houmus.org)

**Comment by latkin** [comment]
A contribution for this would be gladly welcomed. Please draft a speclet somewhere describing the intended behavior, though, so it's explicit exactly what's changing and what compatibility breaks (if any) users should be aware of.  In particular, how to handle various project upgrade and round-trip scenarios.

A few examples, off the top of my head
- Upgrading VS 2013/2012 project which has settings in the .fsproj
  - Are settings moved out, or left in for round-trip support?
  - What if VS 2015 user adds/changes settings, are the new settings stored in .user file?
  - Is behavior different if no settings are found?
- What happens when settings are found in both the .fsproj and the .user file?
  - When they agree, are they du-duped?
  - When they conflict, which one wins? (or does, say, .user always win)
  - Any warnings issued in this case?

I don't think most of these are unique to F#, I assume any of these situations could occur for a C# project, too. Our behavior should match that of C# unless there is a compelling reason not to.

**Comment by damageboy** [comment]
@latkin OK, I guess I have some work cut out for me... :) I'll try and figure out how it works in c# and then I'll make sure that it replicated into f#, when you say `draft a speclet somewhere`, where is somewhere? Is this issue thread appropriate, or do you want some sort of a gist?

**Comment by sharwell** [comment]
@damageboy Do you want to do the initial implementation, or would you like me to attempt the initial transition and then you help with evaluating/tuning the result?

**Comment by latkin** [comment]
@damageboy a gist would be fine. Does not need to be super formal, just a starting point for testing/discussion, and something to refer to later on.

Also - before accepting any contribution, we'll need you to submit a CLA. See https://cla.msopentech.com/

**Comment by dsyme** [comment]
This is implemented by the current project system, and example of the file is here: https://github.com/yatli/fvim/blob/master/fvim.fsproj.user
