### ISSUE TITLE
Debugger can only partially display F# Option value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9149]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1008875/debugger-can-only-partially-display-f-option-value.html)._

---
[regression] [worked-in:15.5 (I think)]
F# specific. The debugger won't display the value, but rather "CS1546: ...", though if you expand the tooltip, you can see what the value actually is. Same for watch window, whatever. See screenshot for details.

---
#### jimfoye2 on 4/27/2020, 09:34 AM: 

Full message is &quot;CS1546: Property, indexer, or event &#39;FSharpOption&lt;T&gt;.DebugDisplay&#39; is not supported by the language; try directly calling accessor method &#39;FSharpOption&lt;T&gt;.get_DebugDisplay(FSharpOption&lt;T&gt;)&#39;	Microsoft.FSharp.Core.FSharpOption&lt;string&gt;&quot;
#### jimfoye2 on 4/27/2020, 09:54 AM: 

Of course I meant 16.5, not 15.5.
#### Visual Studio Feedback System on 4/27/2020, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jimfoye** [comment]
![image](https://user-images.githubusercontent.com/4249676/81485758-389cf380-9215-11ea-9dee-35b23fc632d0.png)

**Comment by cartermp** [comment]
Tagging, perhaps unintuitively, as a feature request since this is related to other issues where we don't have an F#-specific Expression Evaluator.

**Comment by ForNeVeR** [comment]
Actually, nope, it's a bug, though I'm not sure which ecosystem component is bugged in this particular case.

`FSharpOption` is unusual type which has unusual treatment from the compiler. Take a look at this: https://github.com/dotnet/fsharp/blob/31b338ed35fc06c5210cd70756cc60a3847d55e5/src/fsharp/FSharp.Core/prim-types.fs#L3438-L3439

So, `FSharpOption` is a type with `CompilationRepresentationFlags.UseNullAsTrueValue`, which uses `DebugDisplay` as an expression to generate its debug presentation.

And then take a look at the `DebugDisplay` property itself: https://github.com/dotnet/fsharp/blob/31b338ed35fc06c5210cd70756cc60a3847d55e5/src/fsharp/FSharp.Core/prim-types.fs#L3463-L3466

Looks pretty simple, right? Well, nope. The compiler will generate it as _a static parametrized property_ (which is nonsense for C#), because it has `UseNullAsTrueValue` flag. Otherwise, the property will fail when called on a `null` value (which is the runtime representation of `None`!).

I believe, that in earlier versions of VS, it was using some simple (and maybe even hacked) debug representation generator which was able to somehow call this "static parametrized property" when seing a `"DebugDisplay"` inside of a `DebuggerDisplayAttribute`. But no more: in modern times, everyone uses Roslyn as the expression evaluator, and Roslyn isn't able to call `DebugDisplay` in this case.

It should be easy to fix though: we could just write the right code to call this property: `get_DebugDisplay(this)`. I'll send a PR soon.

**Comment by cartermp** [comment]
Oh, nice analysis. This used to work, glad it's just a little magic string. Though it is worth noting that the roslyn expression evaluator does need to know about F# types to be able to display them as best as possible. The DebugDisplay thing is kind of a hack around that fact. Just another item on the long list of things to support...
