### ISSUE TITLE
Indexer/propery is allowed to have mismatched value type

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#9232]
No warnings/errors are produced for the following code:
```fsharp
type T() =
    member x.Item
        with get (index: int): string = ""
        and set (index: int) (value: float) = ()
```

There's a wrong signature for the setter in `fsi`:
<img width="362" alt="Screenshot 2020-05-19 at 20 53 46" src="https://user-images.githubusercontent.com/3923587/82361023-eb8a0000-9a12-11ea-872a-6e586b8c68b7.png">

A tooltip for the property doesn't show the setter at all:
<img width="418" alt="Screenshot 2020-05-19 at 20 53 59" src="https://user-images.githubusercontent.com/3923587/82361028-ecbb2d00-9a12-11ea-996e-f8e49d2870eb.png">

**Comment by dsyme** [comment]
This was never particularly intended, though I was aware since F# 1.x that it was possible.  We should have added a check back then.

I'm sure there is some code that gives wrong types but I think we can consider this a bug.  I'd propose we emit a warning and consider protecting it with a langversion switch

It's possible that this would be considered a breaking change, though I'd take the position that it's a bug fix for unintended behaviour.  Because it is a benign problem (the types are still checked on each use) I think it's better to emit a warning for this than an error.

**Comment by edgarfgp** [comment]
@vzarytovskii Any thought on raising an error vs warning on this issue ? . Personally I think an error is what I would expect

**Comment by vzarytovskii** [comment]
> @vzarytovskii Any thought on raising an error vs warning on this issue ? . Personally I think an error is what I would expect 

Good question. I suppose we can. Make it a warning for preview version  which is treated as error, and promote it to error in future version, this way we will error out by default in next version, but people will still be able to opt out.
