### ISSUE TITLE
Suggestion: Tab support for visually impaired people

### ISSUE THREAD

**Issue by aspnetde** [dotnet/fsharp#9424]
Since reading [that post](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/) I've been certain to start new codebases with tabs instead of spaces (which I personally did prefer all the time). Until I realized that that's not really an option for F#, except when using [verbose syntax](https://fsharpforfunandprofit.com/posts/fsharp-syntax/). Which probably will not go nicely with the sparse tooling support we enjoy right now.

So my only option would be to ignore it and hope for the best. But then again:

> from that moment onward, i couldn't imagine writing code in spaces under the presumption that "nobody with visual impairment will ever need to work with this code, probably", it's just a ridiculous way to think, especially in open-source

I do not expect a quick solution, if there's a way to solve this at all. But maybe it can be considered and discussed.

Cheers

**Comment by Happypig375** [comment]
https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/esmxzrd
>deanykg: One of my best friends is a visually-impaired (legally blind) programmer and he prefers spaces. /shrug
>>vicarofyanks: Obviously. Losing sight doesn’t effect your sense of taste

**Comment by abelbraaksma** [comment]
The discussion on Reddit is primarily for languages that are not whitespace sensitive. It's true that a whitespace sensitive language is hard for the visually impaired. I think that's something that should be fixed in tooling, as the tab width can be detected from the AST.

Yes, verbose syntax can help you here, but in light syntax this is not likely to change. Because it's "been decided before", because it would be incredibly difficult to do this unambiguously, and because you would lose certain language features like single-space or double-space outdenting (valid on the next line if it starts with an operator). In other words, making this possible would mean changing the language beyond compatibility.

On the other hand, tooling can be created that auto expands consecutive lh spaces to smaller or larger widths. And tooling could, at some point, allow a screen reader that's capable of correctly addressing indentation.

**Comment by dsyme** [comment]
This should go on fslang-suggestions please

**Comment by cartermp** [comment]
Closing this out, @aspnetde could you file a language suggestion here? https://github.com/fsharp/fslang-suggestions
