### ISSUE TITLE
When trialling preview features the built FSharp.Core is not used

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9574]
Consider the following:

```fsharp
open FSharp.Linq.RuntimeHelpers
let eval q = LeafExpressionConverter.EvaluateQuotation q
let inline negate x = -x
<@ negate 1.0 @> |> eval |> printfn "%A"
```

Paste this code into an F# script file.

Ensure you have the latest .NET 5 preview 6, and evaluate it with `dotnet fsi --langversion:preview script.fsx`.

You will see `-1` as the output. This is also the case in notebooks.

Now evaluate the same code in a new console app, with the LangVersion set to preview. The result is the old exception:

```
Unhandled exception. System.NotSupportedException: Dynamic invocation of op_UnaryNegation is not supported
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\Linq.fs:line 849
   at Quotations.eval(FSharpExpr q) in C:\Users\phcart\source\repos\fs5preview\fsharp\Quotations.fs:line 5
   at Quotations.improvedQutations() in C:\Users\phcart\source\repos\fs5preview\fsharp\Quotations.fs:line 18
   at Program.main(String[] _arg1) in C:\Users\phcart\source\repos\fs5preview\fsharp\Program.fs:line 19
```

**Comment by cartermp** [comment]
cc @dsyme

**Comment by KevinRansom** [comment]
To the best of my knowledge all of our deployed dll's are built at the same time.   The SDK and VS are built separately and so there are periods when they can be different.  Anyway .. I can take a look at this for you.  The notebook preview is usually a few days behind VS and DotNet sdk insertions, because it's not automated.  And usually comes from the FSharp5 branch rather than the next preview branch.

**Comment by KevinRansom** [comment]
I expect this, happens because it is not using the correct F# core. I imagine it is using the RTM FSharp.Core rather than the latest.

**Comment by dsyme** [comment]
> I expect this, happens because it is not using the correct F# core. I imagine it is using the RTM FSharp.Core rather than the latest.

I believe this is the problem.

**Comment by KevinRansom** [comment]
Oh goodness ...
So ... the automagic has been updated.
The way this is supposed to work now, and if it doesn't work then there is a bug is this:

The code is in the dev16.8 branch not main.  But we ship from 16.8 so that is the right place.

When using preview tools, the tooling will use a preview FSharp.Core from:  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

When using RTM tools the tooling will use a RTM from nuget.org.  Which obviously hasn't been shipped yet, because we are previewing.

**Comment by tebeco** [comment]
see :
https://github.com/dotnet/fsharp/issues/10033#issuecomment-682880042
