### ISSUE TITLE
Parsing of func args incorrect

### ISSUE THREAD

**Issue by whb07** [dotnet/fsharp#9602]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

```fsharp
// doesnt compile
let rec fib n =
    if n < 2 then 1 
    else fib(n -1) + fib(n -2)
```

```fsharp
// DOES compile
let rec fib n =
    if n < 2 then 1 
    else fib(n - 1) + fib(n - 2)
```

**Expected behavior**

Both functions are identical 

**Actual behavior**

The first function  doesn't compile and provides the error "error FS0003: This value is not a function and cannot be applied"

**Known workarounds**

Bash head against wall trying to see  whats wrong, then fiddle with spacing and parenthesis in different spots.

**Related information**

Possibly related [Improve error reporting: Need parentheses on arguments ](https://github.com/dotnet/fsharp/issues/5475)

Provide any related information (optional):

* Operating system MACOSX
* .NET Runtime CORE 3.1
* VSCode

**Comment by Tarmil** [comment]
The problem is that with the original spacing, the compiler recognizes `-2` as a single token representing a negative number, and so it thinks you want to pass it as argument to `n`.

The behavior certainly won't be changed, it's actually useful once you know what's going on and there's probably a bunch of code in the wild that depends on it. But a better error message would be quite nice. The issue you linked is indeed very relevant here.

**Comment by cartermp** [comment]
This is a by-design parsing ambiguity. This issue tracks an improvement that can be made: https://github.com/dotnet/fsharp/issues/5475
