### ISSUE TITLE
Using a union case as a function should accept a derived type

### ISSUE THREAD

**Issue by brianberns** [dotnet/fsharp#9608]
When a union case is used as a function, it should accept a derived type, not just the base type:

    type Base<'t>(value : 't) = class end
    type Derived<'t>(value : 't) = inherit Base<'t>(value)
    type Sum<'t> = Case of Base<'t>

    let test () =
        let good = Case (Derived(1))   // success
        let bad = Case <| Derived(1)   // error FS0001: This expression was expected to have type 'Base<'a>' but here has type 'Derived<int>'
        0

I would expect the two uses (`good` and `bad`) to be semantically identical. Instead, the compiler insists that `Case` accepts only a `Base` when used as a function.

Note that the following also works:

    let toSum = Case
    let ok = toSum <| Derived(1)

Since `toSum` is clearly equivalent to `Case` as a function, they should be behave the same, but they don't.

**Comment by dsyme** [comment]
The question here is whether subsumption-flexibility is introduced for uses of union cases.  

In short, it isn't, and that's currently by design, though it would make sense if it were, and it's reasonable to expect these to be consistent.

This would need an RFC, I've opened a design suggestion here: https://github.com/fsharp/fslang-suggestions/issues/915
