### ISSUE TITLE
New F# library (.NET Core or .NET Standard) does not kick off implicit restore

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9667]
Using 16.6

1. Create library (.NET Core or .NET Standard)

Top is .NET Core, bottom is .NET Standard
![image](https://user-images.githubusercontent.com/6309070/87187543-2cc7bf00-c2a2-11ea-832c-072cbf032e8e.png)

Explicit restore from the command-line fixed this.

**Comment by cartermp** [comment]
Note: this could be related to having a .NET 5 SDK on the machine

**Comment by cartermp** [comment]
Restarting VS fixed this. It seems unreliable.

**Comment by cartermp** [comment]
@davkean this feels like a project system issue to me - implicit restore was not getting kicked off for an F# library project. If I restart VS or explicitly restore from the command-line, everything is fine.

It's also unreliable. I could reproduce it a few moments ago, but can't reproduce it now.

**Comment by abelbraaksma** [comment]
I've seen this often (the yellow markers), and a reliable way to get to see them is to clean bin and obj directories (which will also show "unresolved symbols" in code). I'm not sure why this is dependent on the obj dir, maybe that's by design, but I would expect it not to matter. 

I haven't been needing an explicit restore though, a build, or sometimes rebuild, was enough to fix it. Sometimes the solution compiles, but the yellow markers stay a while longer.

**Comment by cartermp** [comment]
Haven't seen this in a while + it was unreliable. Closing.
