### ISSUE TITLE
F# compiler still treats FSharpFunc as sealed in generic constraints

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9692]
```fs
type C() =
    member _.M<'f, 'a, 'b when 'f :> FSharpFunc<'a, 'b>>(f: 'f) = ()
```

```
    error FS0698: Invalid constraint: the type used for the constraint is sealed, which means the constraint could only be satisfied by at most one solution
    error FS0663: This type parameter has been used in a way that constrains it to always be '('a -> 'b)'
```

And a sharplab link
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBH4bYDCAFAJTYC8V2X2pZARugBO2APoA6ALIAeAORgo2GQEMFMvtgDuACyyKw2EAD5sAMVxalg1CYCumAMayVivocOMwIPazbYWQA=

The idea behind using a constraint like this is to strongly box an FSharpFunc inside a struct so it can be devirtualized and potentially inlined as a result – as `'f` is now a known sealed implementation for the JIT.

Partial fix mentioned in: 
https://github.com/dotnet/fsharp/issues/3737

**Comment by TIHan** [comment]
@dsyme will need look at it.

`FSharpFunc` isn't technically sealed and you can inherit from it. Therefore, I would not expect the constraint error; I'm guessing it's to prevent this type of pattern.

I'm not sure what problem you are trying to solve. What problem requires this type of pattern?

**Comment by TIHan** [comment]
To note: AFAIK, de-virtualization will only happen if the concrete implementation is a struct, it does not do it for reference types.

**Comment by NinoFloris** [comment]
Mostly I was experimenting. It's to get the JIT to devirt and then inline a whole bunch of boilerplate virtual calls (lenses that must be function values in this case). 

Devirtualization happens when the concrete type is known, say a visible newobj or generic specialization of a method that has a bound and is a sealed class.

Generic specialization happens if there is at least one value type involved in the generic method call.

Most likely though, bounding this example to something like:

```fs
[<Struct>]
type FuncBox<'t, 'u,'v when 't :> FSharpFunc<'u,'v>> = FuncBox of 't
    interface IFuncBox
```

would be my obvious choice, however, the constraint still wouldn't be accepted by the compiler today.

**Comment by TIHan** [comment]
// cc @AndyAyersMS

**Comment by NinoFloris** [comment]
@TIHan any question for Andy (or me?)

**Comment by dsyme** [comment]
I'll treat this as a spec/design issue rather than saying this was ever intended to work as things stand today

* The F# type system treates tuple and function types as "special".  For example, it doesn't consider function types to be unsealed.  And for tuples, it doesn't consider them comparable unless their element types are comparable.  

* The compilation representations System.Tuple, System.ValueTuple and FSharpFunc are usable directly, e.g. you can inherit from FSharpFunc.  When present in .NET assemblies or F# source code these are generally de-compiled to the F# forms - we don't allow the compilation representations to really be used with the properties of the compilation representations.  This is by-design as an attempt to prevent mixtures of original and representation types.

* In this instance, the use of FSharpFunc is being decompiled to an F# function type.  This is because of the following

```
    // Try to decode System.Tuple --> F# tuple types etc.
    let ty = g.decompileType tcref actualArgTys
```

This means the unsealed nature of the representation is lost to the F# programmer.

**Comment by dsyme** [comment]
I've recorded this in the list of issues where precise language spec clarifications are needed: https://github.com/fsharp/fsfoundation/issues/841
