### ISSUE TITLE
Anonymous record type not recognized in recursive namespace

### ISSUE THREAD

**Issue by brianberns** [dotnet/fsharp#9885]
The following code doesn't compile:

```
namespace rec MyNs

module MyMod =

    let test (myType : MyType) =
        myType.Record.Field   // error FS0072: Lookup on object of indeterminate type

type MyType =

    member __.Record =
        {| Field = "field "|}
```

Reordering the code works fine:

```
namespace MyNs

type MyType =

    member __.Record =
        {| Field = "field "|}

module MyMod =

    let test (myType : MyType) =
        myType.Record.Field
```

Using a named record type also works fine:

```
namespace rec MyNs

module MyMod =

    let test (myType : MyType) =
        myType.Record.Field

type MyRecord =
    {
        Field : string
    }

type MyType =

    member __.Record =
        { Field = "field "}
```

**Comment by cartermp** [comment]
Note this isn't related to recursive namespaces or modules. Any recursively-defined entities will show this. Feels like a bug.

```fsharp
type Derp() =
    member _.M(mt: MyType) = mt.Record.Field

and MyType =
    member __.Record =
        {| Field = "field "|}
```

**Comment by dsyme** [comment]
This is by design according to the rules of F# type inference.

In a recursive scope, the information extracted before expression bodies are processed is this:

```
type Derp() =
    member _.M(mt: MyType) = *

and MyType =
    member __.Record = *
```

This the implementation of the `Record` property is not taken into account before processing `mt.Record.Field` - the type of `mt` is known but the return type of `mt.Record` is not known.  This has always been the case and is not related to anonymous records

You can add a type annotation if you need to:

```
type Derp() =
    member _.M(mt: MyType) = mt.Record.Field

and MyType =
    member __.Record : {| Field: string |} =
        {| Field = "field "|}
```
