### ISSUE TITLE
#r "nuget: ... " is the wrong interface for scripting 

### ISSUE THREAD

**Issue by shishini** [dotnet/fsharp#9956]
Using F# for scripting compared to other languages is challenging 
But the proposed enhancement of using an in-script command[ #r "nuget: ..." ](https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/)is in my opinion the wrong solution 

For scripting , packages should be installed in a central directory, system wide or per user
this should be achieved by using

`Install-Package`
or 
`Install-Package -Scope CurrentUser`

Dependency resolution should be done on the command line

`dotnet fsi script.fsx`

Should read the read the script, analyze dependencies and raise warning about missing dependencies
the user should should receive warnings about which packages are not installed, 
the the warning message should guide him how to resolve it, and how to install the missing dependencies

Additional command line options can be use to automatically install missing dependencies
For example

`dotnet fsi script.fsx --Install-Dependencies -Scope CurrentUser`

or to test dependcies

 ` dotnet fsi script.fsx --Check-Dependencies`
 
And raise the warnings, without attempting to run the script

The line

 `#r “nuget: Newtonsoft.Json”`
Looks redundant specially when the following line is
 ` open Newtonsoft.Json`

The script should not include instruction to install anything, this is probably unsafe and even if safe is not the right thing to do
Control should be given to the command line runner, and installation of packages should be in a central directory/folder and controlled by the system admin

**Comment by cartermp** [comment]
What you're describing is more of a system administrator's view of software that is not applicable to the scenarios that F# Interactive is for. FSI is a development tool, now using NuGet (also a development tool) to perform package resolution. That makes these points a nonstarter:

> The script should not include instruction to install anything, this is probably unsafe and even if safe is not the right thing to do
Control should be given to the command line runner, and installation of packages should be in a central directory/folder and controlled by the system admin

and

> And raise the warnings, without attempting to run the script

Note that the following is in direct conflict with what you proposed at the end:

> Should read the read the script, analyze dependencies and raise warning about missing dependencies
the user should should receive warnings about which packages are not installed,
the the warning message should guide him how to resolve it, and how to install the missing dependencies

Either FSI should help a developer with how to install missing dependencies or it shouldn't. We choose to help them, so we'll suggest the correct way to specify `#r "nuget:..."` if it is mistyped, since this is a standard practice in developer tooling.

> Looks redundant specially when the following line is [...]

There is no other (reasonable) way for this to work. You need to tell FSI what you're depending on and then since it's .NET, you need to open a namespace that contains the things you want access to.

Package scopes isn't something that's relevant for FSI itself, since FSI is not a general administration tool like PowerShell. Packages are installed into the nuget directory, which I believe you can configure based on your organization's needs.

I will resolve this as by design because the requests are not inline with using FSI as a developer tool, which is what it is.
